/*
  Psychology - AQA A-level (7182).

  Topic strings in FLASHCARDS / MCQ / EXAM must match the titles in GROUPS
  exactly. scripts/check-content.mjs enforces this.
*/

export const PSYCHOLOGY_GROUPS = [
  {
    label: 'Paper 1: Introductory Topics',
    subgroups: [
      {
        label: 'Core Topics',
        topics: ['Social Influence', 'Memory', 'Attachment', 'Psychopathology'],
      },
    ],
  },
  {
    label: 'Paper 2: Psychology in Context',
    subgroups: [
      {
        label: 'Approaches and Biopsychology',
        topics: ['Approaches in Psychology', 'Biopsychology'],
      },
      { label: 'Research Methods', topics: ['Research Methods', 'Data Handling and Statistics'] },
    ],
  },
  {
    label: 'Paper 3: Issues and Options',
    subgroups: [
      { label: 'Issues and Debates', topics: ['Issues and Debates'] },
      { label: 'Options', topics: ['Schizophrenia', 'Forensic Psychology'] },
    ],
  },
]

export const PSYCHOLOGY_FLASHCARDS = [
  // Social Influence
  { front: 'Name the three types of conformity', back: 'Compliance (public change only), identification (change while with the group), and internalisation (genuine private and public change)', topic: 'Social Influence' },
  { front: 'What are the two explanations for conformity?', back: 'Normative social influence (wanting to be liked/accepted) and informational social influence (wanting to be right, especially in ambiguous situations)', topic: 'Social Influence' },
  { front: 'Summarise Asch’s line study and its baseline finding', back: 'Participants judged which comparison line matched a standard line while confederates gave wrong answers. 36.8% of critical trials produced conformity, and 75% conformed at least once', topic: 'Social Influence' },
  { front: 'Give three variables Asch found affect conformity', back: 'Group size (rising up to about 3 confederates then levelling off), unanimity (a dissenter reduces conformity sharply), and task difficulty (harder tasks increase conformity via informational influence)', topic: 'Social Influence' },
  { front: 'What did Zimbardo’s Stanford Prison Experiment suggest?', back: 'That people conform readily to social roles: guards became increasingly brutal and prisoners passive and distressed, ending the study after 6 of the planned 14 days', topic: 'Social Influence' },
  { front: 'Give the headline finding of Milgram’s obedience study', back: '65% of participants administered the full 450 volts, and 100% went to at least 300 volts', topic: 'Social Influence' },
  { front: 'Name three situational variables affecting obedience in Milgram’s research', back: 'Proximity (obedience fell to 40% in the same room), location (47.5% in run-down offices vs 65% at Yale), and uniform (20% when the experimenter was an ordinary member of the public)', topic: 'Social Influence' },
  { front: 'Explain agentic state and autonomous state', back: 'In the agentic state a person acts as an agent for an authority figure and feels no personal responsibility; in the autonomous state they act on their own principles and feel responsible', topic: 'Social Influence' },
  { front: 'What is the authoritarian personality?', back: 'Adorno’s dispositional explanation: people with rigid beliefs, respect for authority and hostility to lower-status groups, measured on the F-scale, arising from harsh parenting', topic: 'Social Influence' },
  { front: 'What two factors explain resistance to social influence?', back: 'Social support (an ally breaks unanimity) and locus of control (internals, who believe they control their own lives, resist better than externals)', topic: 'Social Influence' },
  { front: 'What conditions help a minority influence the majority?', back: 'Consistency (agreement over time and between members), commitment (the augmentation principle, e.g. personal risk) and flexibility (willingness to compromise)', topic: 'Social Influence' },

  // Memory
  { front: 'Describe the multi-store model of memory', back: 'Atkinson and Shiffrin: sensory register (very brief, modality specific) to short-term memory (5 to 9 items, 18 to 30 seconds, acoustic) via attention, to long-term memory (unlimited, lifetime, semantic) via rehearsal', topic: 'Memory' },
  { front: 'Give the capacity, duration and coding of STM and LTM', back: 'STM: 5 to 9 items (Miller), 18 to 30 seconds (Peterson and Peterson), acoustic coding. LTM: potentially unlimited, up to a lifetime (Bahrick), semantic coding (Baddeley)', topic: 'Memory' },
  { front: 'Name the three types of long-term memory', back: 'Episodic (personal events, time-stamped), semantic (facts and knowledge), and procedural (skills and actions, hard to explain in words)', topic: 'Memory' },
  { front: 'Name the components of the working memory model', back: 'Central executive (limited capacity, allocates attention), phonological loop (auditory, with phonological store and articulatory process), visuo-spatial sketchpad (visual and spatial), and episodic buffer (integrates and links to LTM)', topic: 'Memory' },
  { front: 'Explain the two explanations for forgetting', back: 'Interference (proactive: old disrupts new; retroactive: new disrupts old, worse when materials are similar) and retrieval failure (absence of cues, encoding specificity principle)', topic: 'Memory' },
  { front: 'What are context-dependent and state-dependent forgetting?', back: 'Context-dependent: recall is worse when the external environment differs from encoding (Godden and Baddeley, divers). State-dependent: recall is worse when internal state differs (Carter and Cassaday)', topic: 'Memory' },
  { front: 'How does misleading information affect eyewitness testimony?', back: 'Leading questions alter recall (Loftus and Palmer: "smashed" gave a mean estimate of 40.5 mph vs "contacted" 31.8 mph) and post-event discussion causes memory conformity', topic: 'Memory' },
  { front: 'What are the four stages of the cognitive interview?', back: 'Report everything, reinstate the context, reverse the order, and change perspective', topic: 'Memory' },

  // Attachment
  { front: 'What are reciprocity and interactional synchrony?', back: 'Reciprocity is a two-way turn-taking interaction where each responds to the other; interactional synchrony is caregiver and infant mirroring actions and emotions in a coordinated way', topic: 'Attachment' },
  { front: 'Name Schaffer’s four stages of attachment', back: 'Asocial (0 to 6 weeks), indiscriminate (2 to 7 months), specific attachment (around 7 months), and multiple attachments (by around 1 year)', topic: 'Attachment' },
  { front: 'What did Lorenz’s geese study show?', back: 'Imprinting: goslings followed the first moving object seen during a critical period, and this was irreversible and affected later mate preference (sexual imprinting)', topic: 'Attachment' },
  { front: 'What did Harlow’s monkey study show?', back: 'Contact comfort matters more than food: infant monkeys spent most time with a cloth-covered mother even when a wire mother provided milk, and maternally deprived monkeys showed lasting social problems', topic: 'Attachment' },
  { front: 'Explain learning theory of attachment and one criticism', back: 'Attachment forms through classical conditioning (caregiver associated with food) and operant conditioning (crying reinforced). Criticised as "cupboard love": Harlow and Schaffer show comfort and responsiveness matter more than feeding', topic: 'Attachment' },
  { front: 'Outline Bowlby’s monotropic theory', back: 'Attachment is innate and adaptive; there is one primary attachment (monotropy); social releasers elicit caregiving; there is a critical period of about 2.5 years; the internal working model shapes later relationships', topic: 'Attachment' },
  { front: 'Name the three attachment types from Ainsworth’s Strange Situation', back: 'Secure (about 66%, moderate distress, easily comforted), insecure-avoidant (about 22%, little distress, avoids contact), insecure-resistant (about 12%, high distress, resists comfort)', topic: 'Attachment' },
  { front: 'What did Van Ijzendoorn’s meta-analysis find?', back: 'Secure attachment was the most common in all cultures; insecure-avoidant was most common in individualist Germany, insecure-resistant in collectivist Japan and Israel. Variation within countries was 1.5 times that between countries', topic: 'Attachment' },
  { front: 'What is Bowlby’s theory of maternal deprivation?', back: 'Continuous care from a mother figure is essential in the critical period; deprivation risks intellectual delay and affectionless psychopathy (an inability to feel guilt or empathy)', topic: 'Attachment' },
  { front: 'What did the Romanian orphan studies show?', back: 'Rutter: the later the adoption, the lower the IQ (adopted after 2 years, mean IQ 77) and the higher the rate of disinhibited attachment, showing effects of institutionalisation', topic: 'Attachment' },

  // Psychopathology
  { front: 'Name the four definitions of abnormality', back: 'Statistical infrequency, deviation from social norms, failure to function adequately, and deviation from ideal mental health', topic: 'Psychopathology' },
  { front: 'Give the behavioural, emotional and cognitive characteristics of phobias', back: 'Behavioural: panic, avoidance, endurance. Emotional: anxiety, fear, unreasonable emotional response. Cognitive: selective attention to the stimulus, irrational beliefs, cognitive distortions', topic: 'Psychopathology' },
  { front: 'Explain the two-process model of phobias', back: 'Phobias are acquired by classical conditioning (association of a neutral stimulus with fear, as in Little Albert) and maintained by operant conditioning (avoidance is negatively reinforced by reducing anxiety)', topic: 'Psychopathology' },
  { front: 'How does systematic desensitisation work?', back: 'Counterconditioning through an anxiety hierarchy, relaxation training and gradual exposure. It relies on reciprocal inhibition, since relaxation and fear cannot coexist', topic: 'Psychopathology' },
  { front: 'Outline Beck’s negative triad', back: 'Depression involves negative views of the self, the world and the future, maintained by faulty information processing and negative self-schemas', topic: 'Psychopathology' },
  { front: 'Explain Ellis’s ABC model', back: 'An Activating event leads to a Belief (rational or irrational) which leads to a Consequence. Irrational beliefs such as musturbation produce unhealthy emotions. REBT adds Dispute and Effect', topic: 'Psychopathology' },
  { front: 'What is the biological explanation and treatment for OCD?', back: 'Genetic (candidate genes COMT and SERT, polygenic, diathesis-stress) and neural (low serotonin, abnormal frontal lobe and basal ganglia function). Treated with SSRIs, which increase serotonin in the synapse', topic: 'Psychopathology' },

  // Approaches
  { front: 'What are the assumptions of the behaviourist approach?', back: 'Only observable behaviour should be studied, we are born a blank slate, and learning occurs through classical conditioning (Pavlov) and operant conditioning (Skinner) using reinforcement and punishment', topic: 'Approaches in Psychology' },
  { front: 'Outline social learning theory', back: 'Learning through observation and imitation of models, mediated by attention, retention, motor reproduction and motivation, with vicarious reinforcement and identification. Supported by Bandura’s Bobo doll studies', topic: 'Approaches in Psychology' },
  { front: 'What are schemas in the cognitive approach?', back: 'Mental frameworks of beliefs and expectations built from experience that help process information quickly, but can distort interpretation and lead to errors', topic: 'Approaches in Psychology' },
  { front: 'Outline the biological approach', back: 'Behaviour has a physical basis: genes (twin studies comparing MZ and DZ concordance), neurochemistry, and evolution through natural selection. Distinguishes genotype from phenotype', topic: 'Approaches in Psychology' },
  { front: 'Name Freud’s three parts of the personality', back: 'Id (pleasure principle, present at birth), ego (reality principle, from about 2 years, uses defence mechanisms), and superego (morality principle, from about 5 years after the phallic stage)', topic: 'Approaches in Psychology' },
  { front: 'Name Freud’s psychosexual stages', back: 'Oral, anal, phallic, latency, genital. Unresolved conflict causes fixation, for example the Oedipus/Electra complex in the phallic stage', topic: 'Approaches in Psychology' },
  { front: 'What are the key ideas of humanistic psychology?', back: 'Free will, self-actualisation at the top of Maslow’s hierarchy, congruence between self and ideal self, and conditions of worth. Rogers used client-centred therapy with unconditional positive regard', topic: 'Approaches in Psychology' },

  // Biopsychology
  { front: 'Divide the nervous system into its parts', back: 'Central (brain and spinal cord) and peripheral. Peripheral divides into somatic and autonomic; autonomic divides into sympathetic (fight or flight) and parasympathetic (rest and digest)', topic: 'Biopsychology' },
  { front: 'Describe the fight or flight response', back: 'The hypothalamus activates the sympathetic branch, the adrenal medulla releases adrenaline, giving increased heart rate, dilated pupils and inhibited digestion. The parasympathetic branch then returns the body to rest', topic: 'Biopsychology' },
  { front: 'Explain synaptic transmission', back: 'An action potential triggers vesicles to release neurotransmitter into the synaptic cleft; it diffuses across and binds to receptors on the post-synaptic membrane, then is reuptaken or broken down. Summation determines whether the neuron fires', topic: 'Biopsychology' },
  { front: 'What are Broca’s and Wernicke’s areas?', back: 'Broca’s area in the left frontal lobe controls speech production (damage gives slow, laboured speech); Wernicke’s area in the left temporal lobe controls language comprehension (damage gives fluent but meaningless speech)', topic: 'Biopsychology' },
  { front: 'What did Sperry’s split-brain research show?', back: 'With the corpus callosum severed, information to the right hemisphere could not be verbalised but could be drawn with the left hand, showing lateralisation of language to the left hemisphere', topic: 'Biopsychology' },
  { front: 'Compare fMRI, EEG, ERPs and post-mortem examinations', back: 'fMRI: good spatial resolution, non-invasive, but poor temporal resolution and expensive. EEG/ERPs: excellent temporal resolution but poor spatial. Post-mortem: detailed anatomy but no causal certainty and consent issues', topic: 'Biopsychology' },
  { front: 'What are endogenous pacemakers and exogenous zeitgebers?', back: 'Endogenous pacemakers are internal body clocks such as the suprachiasmatic nucleus; exogenous zeitgebers are external cues such as light and social cues that entrain them', topic: 'Biopsychology' },

  // Research Methods
  { front: 'Distinguish an aim, a hypothesis and the two types of hypothesis', back: 'An aim states the purpose of the research. A hypothesis is a precise testable statement. Directional (one-tailed) predicts the direction; non-directional (two-tailed) predicts a difference without direction', topic: 'Research Methods' },
  { front: 'Name the three experimental designs with one strength and weakness each', back: 'Independent groups (no order effects but participant variables), repeated measures (controls participant variables but has order effects, solved by counterbalancing), matched pairs (both benefits but time consuming)', topic: 'Research Methods' },
  { front: 'What are demand characteristics and investigator effects?', back: 'Demand characteristics: cues that lead participants to guess the aim and change behaviour. Investigator effects: any unintended influence of the researcher on the outcome. Both are reduced by a double blind procedure', topic: 'Research Methods' },
  { front: 'Distinguish internal and external validity', back: 'Internal validity is whether the study measured what it intended without confounding variables. External validity is whether findings generalise, including ecological, population and temporal validity', topic: 'Research Methods' },
  { front: 'Name five sampling methods', back: 'Random (equal chance, unbiased but time consuming), systematic (every nth), stratified (proportional subgroups, most representative), opportunity (convenient but biased), volunteer (self-selecting, gives volunteer bias)', topic: 'Research Methods' },
  { front: 'List the main ethical issues and how they are dealt with', back: 'Informed consent (consent form, or presumptive/retrospective consent), deception and protection from harm (full debrief), confidentiality (anonymity), and the right to withdraw', topic: 'Research Methods' },
  { front: 'Distinguish reliability and validity, and give a way to check each', back: 'Reliability is consistency, checked by test-retest, inter-observer reliability (correlation above +0.80) or split-half. Validity is accuracy, checked by face, concurrent, and construct validity', topic: 'Research Methods' },
  { front: 'What are the features of a science?', back: 'Objectivity, empirical method, replicability, falsifiability (Popper), theory construction and hypothesis testing, and paradigms with paradigm shifts (Kuhn)', topic: 'Research Methods' },

  // Data handling
  { front: 'Name the three measures of central tendency and when each is best', back: 'Mean (uses all data, but distorted by outliers), median (unaffected by outliers, good for skewed data), mode (only option for categorical data)', topic: 'Data Handling and Statistics' },
  { front: 'What does standard deviation tell you?', back: 'The average spread of scores around the mean. A large standard deviation means more variation and less consistency in the data', topic: 'Data Handling and Statistics' },
  { front: 'What are the three levels of measurement?', back: 'Nominal (categories/counts), ordinal (ranked but unequal intervals), interval (equal, standardised units)', topic: 'Data Handling and Statistics' },
  { front: 'When do you use a Chi-squared test?', back: 'When testing for a difference or association, with independent groups, and nominal data', topic: 'Data Handling and Statistics' },
  { front: 'When do you use a Spearman’s rho and a Pearson’s r?', back: 'Both for correlations: Spearman’s rho for ordinal data, Pearson’s r for interval data', topic: 'Data Handling and Statistics' },
  { front: 'What does p ≤ 0.05 mean, and what are Type I and Type II errors?', back: 'A 5% probability the result is due to chance. A Type I error is a false positive (rejecting a true null, more likely if p is too lenient); a Type II error is a false negative (accepting a false null)', topic: 'Data Handling and Statistics' },
  { front: 'What are the three types of distribution shape?', back: 'Normal (symmetrical, mean = median = mode), positively skewed (long tail to the right, mode < median < mean), negatively skewed (long tail to the left, mean < median < mode)', topic: 'Data Handling and Statistics' },

  // Issues and debates
  { front: 'What is α bias and β bias?', back: 'Alpha bias exaggerates differences between genders; β bias minimises or ignores them. Androcentrism treats male behaviour as the standard', topic: 'Issues and Debates' },
  { front: 'What is cultural bias, ethnocentrism and cultural relativism?', back: 'Cultural bias is judging behaviour by one culture’s standards. Ethnocentrism treats one’s own culture as superior. Cultural relativism says behaviour can only be understood within its own cultural context', topic: 'Issues and Debates' },
  { front: 'Distinguish hard determinism, soft determinism and free will', back: 'Hard determinism says all behaviour has a cause and free will is an illusion. Soft determinism says behaviour is constrained but there is some conscious choice. Free will says we choose our own behaviour', topic: 'Issues and Debates' },
  { front: 'What is the holism versus reductionism debate?', back: 'Holism says behaviour must be studied as a whole. Reductionism explains it by simpler components: biological reductionism (genes, neurochemistry) and environmental reductionism (stimulus-response)', topic: 'Issues and Debates' },
  { front: 'What is the idiographic versus nomothetic debate?', back: 'Idiographic studies individuals in depth using qualitative methods (case studies); nomothetic seeks general laws using large samples and quantitative methods', topic: 'Issues and Debates' },
  { front: 'What are socially sensitive research and its implications?', back: 'Research with potential social consequences for participants or the group they represent. Researchers must consider the research question, dealing with participants, and how findings may be used', topic: 'Issues and Debates' },

  // Schizophrenia
  { front: 'Distinguish positive and negative symptoms of schizophrenia', back: 'Positive symptoms are additions to normal experience: hallucinations and delusions. Negative symptoms are losses: avolition (loss of motivation) and speech poverty (alogia)', topic: 'Schizophrenia' },
  { front: 'What are the two issues in classifying schizophrenia?', back: 'Reliability (poor inter-rater agreement between ICD and DSM) and validity (symptom overlap with other conditions, co-morbidity, gender bias and culture bias)', topic: 'Schizophrenia' },
  { front: 'Explain the dopamine hypothesis, original and revised', back: 'Original: hyperdopaminergia in the subcortex (excess dopamine in Broca’s area linked to hallucinations). Revised: hypodopaminergia in the prefrontal cortex explains negative symptoms', topic: 'Schizophrenia' },
  { front: 'What are the psychological explanations of schizophrenia?', back: 'Family dysfunction (schizophrenogenic mother, double-bind theory, expressed emotion) and cognitive explanations (dysfunctional thought processing, metarepresentation and central control deficits)', topic: 'Schizophrenia' },
  { front: 'Compare typical and atypical antipsychotics', back: 'Typical (chlorpromazine) are dopamine antagonists that block D2 receptors and mainly treat positive symptoms, with a risk of tardive dyskinesia. Atypical (clozapine, risperidone) act on dopamine and serotonin with fewer side effects', topic: 'Schizophrenia' },
  { front: 'What is the interactionist approach to schizophrenia?', back: 'The diathesis-stress model: a vulnerability (genetic or from early trauma) combined with a stress trigger (such as cannabis use or family stress) produces the disorder. Treatment combines medication and CBT', topic: 'Schizophrenia' },

  // Forensic
  { front: 'Compare top-down and bottom-up offender profiling', back: 'Top-down (FBI) uses pre-existing templates to classify offenders as organised or disorganised. Bottom-up (British) builds a picture from systematic evidence analysis, using investigative psychology and geographical profiling', topic: 'Forensic Psychology' },
  { front: 'What is Lombroso’s atavistic form?', back: 'A historical biological explanation claiming criminals are genetic throwbacks with distinct physical features such as a strong jaw and high cheekbones. Criticised as scientifically racist and confounded by poverty', topic: 'Forensic Psychology' },
  { front: 'Outline Eysenck’s theory of the criminal personality', back: 'Criminals score high on extraversion (underactive nervous system so they seek stimulation), neuroticism (unstable and unpredictable) and psychoticism (cold and unemotional), measured by the EPQ', topic: 'Forensic Psychology' },
  { front: 'What is differential association theory?', back: 'Sutherland: offending is learned through interactions with others, from pro-criminal attitudes and the learning of specific techniques. It predicts offending from the frequency, intensity and duration of exposure', topic: 'Forensic Psychology' },
  { front: 'Give the four aims of custodial sentencing', back: 'Deterrence, incapacitation, retribution and rehabilitation', topic: 'Forensic Psychology' },
  { front: 'What is restorative justice?', back: 'A survivor-focused process where the offender meets the victim to understand the impact of the crime and make reparation, focusing on healing rather than punishment', topic: 'Forensic Psychology' },
]

export const PSYCHOLOGY_MCQ = [
  { question: 'Publicly agreeing with a group but privately disagreeing is', options: ['internalisation', 'identification', 'compliance', 'obedience'], answer: 2, explanation: 'Compliance is a public change only, which stops when the group is absent.', topic: 'Social Influence' },
  { question: 'In Asch’s baseline study, the conformity rate on critical trials was about', options: ['13%', '36.8%', '65%', '75%'], answer: 1, explanation: '36.8% of critical trials showed conformity; 75% conformed at least once.', topic: 'Social Influence' },
  { question: 'What percentage of Milgram’s participants gave the full 450 volts?', options: ['35%', '47.5%', '65%', '100%'], answer: 2, explanation: '65% went to the maximum 450 volts.', topic: 'Social Influence' },
  { question: 'Conforming because you believe the group is right is', options: ['normative social influence', 'informational social influence', 'compliance', 'obedience'], answer: 1, explanation: 'Informational social influence is about wanting to be correct.', topic: 'Social Influence' },
  { question: 'Someone with an internal locus of control is', options: ['more likely to conform', 'more likely to resist social influence', 'more obedient', 'unaffected'], answer: 1, explanation: 'Internals believe they control their own outcomes, so they resist pressure better.', topic: 'Social Influence' },
  { question: 'The duration of short-term memory is about', options: ['2 seconds', '18 to 30 seconds', '2 minutes', 'unlimited'], answer: 1, explanation: 'Peterson and Peterson found 18 to 30 seconds without rehearsal.', topic: 'Memory' },
  { question: 'Which type of long-term memory stores knowledge of facts?', options: ['Episodic', 'Semantic', 'Procedural', 'Sensory'], answer: 1, explanation: 'Semantic memory holds facts and general knowledge.', topic: 'Memory' },
  { question: 'Which component of working memory has a limited capacity and allocates attention?', options: ['Phonological loop', 'Central executive', 'Episodic buffer', 'Visuo-spatial sketchpad'], answer: 1, explanation: 'The central executive directs attention to the slave systems.', topic: 'Memory' },
  { question: 'Old learning disrupting new learning is', options: ['retroactive interference', 'proactive interference', 'retrieval failure', 'displacement'], answer: 1, explanation: 'Proactive interference is old disrupting new.', topic: 'Memory' },
  { question: 'In Loftus and Palmer, which verb produced the highest speed estimate?', options: ['Contacted', 'Hit', 'Collided', 'Smashed'], answer: 3, explanation: '"Smashed" gave a mean estimate of 40.5 mph.', topic: 'Memory' },
  { question: 'Caregiver and infant mirroring each other in a coordinated way is', options: ['reciprocity', 'interactional synchrony', 'imprinting', 'monotropy'], answer: 1, explanation: 'Interactional synchrony is coordinated mirroring of action and emotion.', topic: 'Attachment' },
  { question: 'Harlow’s monkeys preferred the cloth mother, showing the importance of', options: ['food', 'contact comfort', 'imprinting', 'operant conditioning'], answer: 1, explanation: 'Contact comfort outweighed the provision of food.', topic: 'Attachment' },
  { question: 'In the Strange Situation, an infant showing little distress and avoiding contact is', options: ['secure', 'insecure-avoidant', 'insecure-resistant', 'disorganised'], answer: 1, explanation: 'Insecure-avoidant infants show low stranger and separation anxiety and avoid reunion contact.', topic: 'Attachment' },
  { question: 'Bowlby’s idea of one special attachment is called', options: ['monotropy', 'imprinting', 'reciprocity', 'the internal working model'], answer: 0, explanation: 'Monotropy is the idea of one primary attachment figure.', topic: 'Attachment' },
  { question: 'Which definition of abnormality is most affected by changing social attitudes?', options: ['Statistical infrequency', 'Deviation from social norms', 'Failure to function adequately', 'Deviation from ideal mental health'], answer: 1, explanation: 'Social norms change over time and between cultures, so this definition lacks temporal validity.', topic: 'Psychopathology' },
  { question: 'In the two-process model, phobias are maintained by', options: ['classical conditioning', 'operant conditioning through avoidance', 'social learning', 'genetics'], answer: 1, explanation: 'Avoidance is negatively reinforced by reducing anxiety.', topic: 'Psychopathology' },
  { question: 'Beck’s negative triad consists of negative views of', options: ['past, present, future', 'self, world, future', 'self, others, past', 'family, work, self'], answer: 1, explanation: 'Negative views of the self, the world and the future.', topic: 'Psychopathology' },
  { question: 'In Ellis’s ABC model, B stands for', options: ['Behaviour', 'Belief', 'Bias', 'Baseline'], answer: 1, explanation: 'Activating event, Belief, Consequence.', topic: 'Psychopathology' },
  { question: 'SSRIs treat OCD by increasing levels of', options: ['dopamine', 'serotonin', 'adrenaline', 'GABA'], answer: 1, explanation: 'SSRIs prevent reuptake, increasing serotonin in the synapse.', topic: 'Psychopathology' },
  { question: 'Which approach argues we are born a blank slate?', options: ['Biological', 'Behaviourist', 'Psychodynamic', 'Humanistic'], answer: 1, explanation: 'Behaviourism holds that all behaviour is learned from the environment.', topic: 'Approaches in Psychology' },
  { question: 'Bandura’s Bobo doll study supports which approach?', options: ['Cognitive', 'Social learning theory', 'Biological', 'Psychodynamic'], answer: 1, explanation: 'It demonstrated observational learning and imitation of a model.', topic: 'Approaches in Psychology' },
  { question: 'In Freud’s theory, which part operates on the reality principle?', options: ['Id', 'Ego', 'Superego', 'Unconscious'], answer: 1, explanation: 'The ego mediates between the id and superego using the reality principle.', topic: 'Approaches in Psychology' },
  { question: 'Self-actualisation sits at the top of', options: ['the negative triad', 'Maslow’s hierarchy of needs', 'the ABC model', 'the working memory model'], answer: 1, explanation: 'Maslow placed self-actualisation at the apex of his hierarchy.', topic: 'Approaches in Psychology' },
  { question: 'The fight or flight response is triggered by which branch?', options: ['Somatic', 'Parasympathetic', 'Sympathetic', 'Central'], answer: 2, explanation: 'The sympathetic branch of the autonomic nervous system triggers arousal.', topic: 'Biopsychology' },
  { question: 'Damage to Broca’s area causes difficulty with', options: ['understanding speech', 'producing speech', 'seeing', 'hearing'], answer: 1, explanation: 'Broca’s aphasia gives slow, laboured, non-fluent speech production.', topic: 'Biopsychology' },
  { question: 'Which technique has the best temporal resolution?', options: ['fMRI', 'EEG', 'Post-mortem', 'CAT scan'], answer: 1, explanation: 'EEG records electrical activity in real time to the millisecond.', topic: 'Biopsychology' },
  { question: 'The suprachiasmatic nucleus is an example of', options: ['an exogenous zeitgeber', 'an endogenous pacemaker', 'an infradian rhythm', 'a neurotransmitter'], answer: 1, explanation: 'It is the internal body clock in the hypothalamus.', topic: 'Biopsychology' },
  { question: 'A hypothesis predicting a difference without stating direction is', options: ['directional', 'non-directional', 'null', 'alternative only'], answer: 1, explanation: 'A non-directional (two-tailed) hypothesis predicts a difference but not its direction.', topic: 'Research Methods' },
  { question: 'Counterbalancing is used to deal with', options: ['participant variables', 'order effects', 'demand characteristics', 'sampling bias'], answer: 1, explanation: 'It controls order effects in a repeated measures design.', topic: 'Research Methods' },
  { question: 'Which sampling method is most representative?', options: ['Opportunity', 'Volunteer', 'Stratified', 'Systematic'], answer: 2, explanation: 'Stratified sampling reflects subgroup proportions in the population.', topic: 'Research Methods' },
  { question: 'Inter-observer reliability is generally acceptable above a correlation of', options: ['+0.20', '+0.50', '+0.80', '+0.95'], answer: 2, explanation: 'A correlation of +0.80 or above is the usual threshold.', topic: 'Research Methods' },
  { question: 'Which measure of central tendency is most affected by outliers?', options: ['Mean', 'Median', 'Mode', 'Range'], answer: 0, explanation: 'The mean uses every score, so extreme values distort it.', topic: 'Data Handling and Statistics' },
  { question: 'Data in ranked order with unequal intervals is', options: ['nominal', 'ordinal', 'interval', 'ratio'], answer: 1, explanation: 'Ordinal data is ranked but the gaps between ranks are not equal.', topic: 'Data Handling and Statistics' },
  { question: 'A Type I error means', options: ['accepting a false null hypothesis', 'rejecting a true null hypothesis', 'using the wrong test', 'a small sample'], answer: 1, explanation: 'A Type I error is a false positive, rejecting a null hypothesis that was actually true.', topic: 'Data Handling and Statistics' },
  { question: 'For a test of difference with nominal data and independent groups you would use', options: ['Chi-squared', 'Spearman’s rho', 'Wilcoxon', 'Related t-test'], answer: 0, explanation: 'Chi-squared is for nominal data with independent groups.', topic: 'Data Handling and Statistics' },
  { question: 'Exaggerating differences between genders is', options: ['β bias', 'α bias', 'androcentrism', 'ethnocentrism'], answer: 1, explanation: 'Alpha bias exaggerates; β bias minimises.', topic: 'Issues and Debates' },
  { question: 'Judging other cultures by the standards of your own is', options: ['cultural relativism', 'ethnocentrism', 'α bias', 'determinism'], answer: 1, explanation: 'Ethnocentrism treats one culture as the standard or superior.', topic: 'Issues and Debates' },
  { question: 'Studying individuals in depth using case studies is', options: ['nomothetic', 'idiographic', 'reductionist', 'deterministic'], answer: 1, explanation: 'The idiographic approach focuses on the individual in depth.', topic: 'Issues and Debates' },
  { question: 'Hallucinations and delusions are classed as', options: ['negative symptoms', 'positive symptoms', 'cognitive deficits', 'side effects'], answer: 1, explanation: 'Positive symptoms are additions to normal experience.', topic: 'Schizophrenia' },
  { question: 'The revised dopamine hypothesis proposes hypodopaminergia in the', options: ['subcortex', 'prefrontal cortex', 'hippocampus', 'cerebellum'], answer: 1, explanation: 'Low dopamine in the prefrontal cortex is linked to negative symptoms.', topic: 'Schizophrenia' },
  { question: 'The diathesis-stress model of schizophrenia argues that', options: ['genes alone cause it', 'stress alone causes it', 'vulnerability plus a stress trigger causes it', 'it is entirely random'], answer: 2, explanation: 'A vulnerability must be combined with a stressor for the disorder to develop.', topic: 'Schizophrenia' },
  { question: 'The FBI approach to offender profiling is described as', options: ['bottom-up', 'top-down', 'geographical', 'investigative'], answer: 1, explanation: 'The American top-down approach classifies offenders into pre-existing templates.', topic: 'Forensic Psychology' },
  { question: 'Eysenck argued criminals score highly on', options: ['agreeableness', 'extraversion, neuroticism and psychoticism', 'openness only', 'conscientiousness'], answer: 1, explanation: 'His criminal personality is high E, high N and high P.', topic: 'Forensic Psychology' },
]

export const PSYCHOLOGY_EXAM = [
  { question: 'Outline and evaluate research into conformity to social roles.', marks: 8, markScheme: ['AO1: Zimbardo randomly assigned 21 male students to guard or prisoner roles in a mock prison at Stanford', 'AO1: Guards became increasingly brutal and prisoners passive and distressed; the study was stopped after 6 days rather than 14', 'AO3 strength: high control over variables such as emotionally stable participant selection increases internal validity', 'AO3 limitation: lack of realism, as Banuazizi and Movahedi argued participants were play-acting to stereotypes', 'AO3 limitation: major ethical issues, as Zimbardo’s dual role as superintendent compromised the right to withdraw', 'AO3 limitation: exaggerates the power of roles, since only about a third of guards behaved brutally', 'Final answer: describe the procedure and findings, then evaluate control, realism, ethics and dispositional influences'], topic: 'Social Influence' },
  { question: 'Explain the difference between normative and informational social influence, with an example of each.', marks: 4, markScheme: ['Normative social influence is conforming to be liked or accepted by the group, driven by the need for approval', 'Example: agreeing with friends about music taste to fit in, usually leading to compliance', 'Informational social influence is conforming because you believe others are right, driven by the need to be correct', 'Example: copying others in an ambiguous or unfamiliar situation, usually leading to internalisation', 'Final answer: NSI is about acceptance, ISI is about accuracy'], topic: 'Social Influence' },
  { question: 'Outline the working memory model.', marks: 6, markScheme: ['The central executive has a very limited capacity and allocates attention to the slave systems', 'The phonological loop deals with auditory information, subdivided into the phonological store (what you hear) and the articulatory process (rehearsal)', 'The visuo-spatial sketchpad handles visual and spatial information, subdivided into the visual cache and inner scribe', 'The episodic buffer integrates information from all stores into a single time-sequenced record and links to long-term memory', 'Each store has its own limited capacity, which explains why two tasks using the same store interfere with each other', 'Final answer: four components, each with its own function and limited capacity'], topic: 'Memory' },
  { question: 'Explain how misleading information can affect the accuracy of eyewitness testimony.', marks: 4, markScheme: ['Leading questions can alter recall through the wording used, as the verb suggests a speed', 'Loftus and Palmer found "smashed" produced a mean estimate of 40.5 mph compared with 31.8 mph for "contacted"', 'Post-event discussion causes memory conformity, where witnesses incorporate each other’s accounts', 'Gabbert found 71% of witnesses who discussed the event recalled details they had not actually seen', 'Final answer: leading questions and post-event discussion both distort the original memory'], topic: 'Memory' },
  { question: 'Describe the procedure of Ainsworth’s Strange Situation.', marks: 6, markScheme: ['A controlled observation with a two-way mirror, in eight episodes of about three minutes each', 'Behaviours assessed: proximity seeking, exploration and secure base behaviour, stranger anxiety, separation anxiety and response to reunion', 'The caregiver and infant enter, the infant explores, a stranger enters and interacts', 'The caregiver leaves, then returns and comforts the infant', 'The infant is left alone, then the stranger returns, then the caregiver returns again', 'Findings gave three attachment types: secure (66%), insecure-avoidant (22%) and insecure-resistant (12%)', 'Final answer: eight episodes measuring five behaviours, producing three attachment types'], topic: 'Attachment' },
  { question: 'Discuss the influence of early attachment on later relationships.', marks: 8, markScheme: ['AO1: Bowlby’s internal working model acts as a template for future relationships based on the first attachment', 'AO1: Hazan and Shaver’s love quiz found securely attached adults had longer lasting, more trusting relationships', 'AO1: Attachment type also predicts parenting style, with continuity across generations', 'AO3 limitation: most studies use retrospective self-report, which risks inaccurate recall and social desirability bias', 'AO3 limitation: correlational data means a third factor such as temperament could explain both', 'AO3 limitation: it is overly deterministic, since many people with poor early attachments form good later relationships', 'Final answer: describe the internal working model and supporting evidence, then evaluate methodology and determinism'], topic: 'Attachment' },
  { question: 'Outline the behavioural approach to explaining phobias.', marks: 6, markScheme: ['The two-process model states phobias are acquired by classical conditioning and maintained by operant conditioning', 'Acquisition: a neutral stimulus is paired with an unconditioned stimulus that causes fear', 'The neutral stimulus becomes a conditioned stimulus producing a conditioned response of fear', 'Watson and Rayner demonstrated this with Little Albert and a white rat paired with a loud noise', 'Maintenance: avoiding the phobic stimulus reduces anxiety, which negatively reinforces the avoidance behaviour', 'This prevents the fear from being extinguished, so the phobia persists', 'Final answer: classical conditioning acquires the phobia, operant conditioning maintains it via avoidance'], topic: 'Psychopathology' },
  { question: 'Explain how systematic desensitisation is used to treat phobias.', marks: 4, markScheme: ['An anxiety hierarchy is constructed with the client, ranking situations from least to most frightening', 'The client is taught relaxation techniques such as deep breathing or progressive muscle relaxation', 'The client works up the hierarchy, staying relaxed at each stage before moving on', 'This works through reciprocal inhibition, as it is impossible to be relaxed and afraid at the same time', 'Final answer: hierarchy, relaxation and gradual exposure using reciprocal inhibition'], topic: 'Psychopathology' },
  { question: 'Outline the psychodynamic approach to explaining human behaviour.', marks: 6, markScheme: ['Behaviour is driven largely by the unconscious mind, which can be accessed through dreams and slips of the tongue', 'The personality has three parts: the id (pleasure principle), the ego (reality principle) and the superego (morality principle)', 'The ego uses defence mechanisms such as repression, denial and displacement to manage conflict', 'Development occurs through five psychosexual stages: oral, anal, phallic, latency and genital', 'Unresolved conflict at a stage causes fixation, carrying behaviours into adulthood', 'The Oedipus complex in the phallic stage explains gender identity development through identification', 'Final answer: unconscious drives, tripartite personality, defence mechanisms and psychosexual stages'], topic: 'Approaches in Psychology' },
  { question: 'Describe the process of synaptic transmission.', marks: 4, markScheme: ['An action potential arrives at the presynaptic terminal, causing vesicles to fuse with the membrane', 'Neurotransmitter is released into the synaptic cleft and diffuses across it', 'It binds to complementary receptors on the postsynaptic membrane, causing excitation (EPSP) or inhibition (IPSP)', 'Summation of these signals determines whether the postsynaptic neuron fires; the neurotransmitter is then reuptaken or broken down', 'Final answer: release, diffusion, binding, summation, then reuptake'], topic: 'Biopsychology' },
  { question: 'Explain two limitations of using fMRI to study the brain.', marks: 4, markScheme: ['Poor temporal resolution: there is a lag of about 5 seconds behind the neural activity, so it cannot capture the exact timing', 'It measures blood flow rather than neural activity directly, so it only gives an indirect measure', 'It is expensive and requires the participant to stay completely still, limiting the tasks that can be studied', 'Final answer: any two limitations, each explained'], topic: 'Biopsychology' },
  { question: 'A researcher wants to investigate whether background music affects revision performance. Identify a suitable experimental design and explain one strength and one limitation.', marks: 4, markScheme: ['A repeated measures design, where each participant revises both with and without music', 'Strength: participant variables are controlled, since the same people do both conditions, reducing individual differences', 'Limitation: order effects, as participants may improve through practice or worsen through fatigue', 'This can be addressed by counterbalancing, with half doing music first and half doing silence first', 'Final answer: repeated measures, controlling participant variables but risking order effects'], topic: 'Research Methods' },
  { question: 'Explain what is meant by demand characteristics and describe one way of dealing with them.', marks: 3, markScheme: ['Demand characteristics are cues in a study that allow participants to guess the aim of the research', 'Participants may then change their behaviour, either to help (the please-U effect) or to hinder (the screw-U effect)', 'A single blind procedure, where participants do not know the condition or aim, reduces this', 'Final answer: cues that reveal the aim, addressed by a single or double blind procedure'], topic: 'Research Methods' },
  { question: 'A study produces scores of 4, 5, 5, 6, 30. Explain which measure of central tendency is most appropriate and why.', marks: 3, markScheme: ['The median is most appropriate', 'The score of 30 is an extreme outlier that would distort the mean, pulling it up to 10 which is unrepresentative', 'The median of 5 is unaffected by the outlier and better reflects the typical score', 'Final answer: the median, because it is not distorted by the extreme value'], topic: 'Data Handling and Statistics' },
  { question: 'Explain what is meant by free will and determinism, and outline the interactionist position.', marks: 4, markScheme: ['Free will suggests we are self-determining and able to choose our own thoughts and actions, as argued by the humanistic approach', 'Determinism suggests behaviour is caused by internal or external factors beyond our control, with hard determinism denying free will entirely', 'Soft determinism argues behaviour is constrained by factors but people still exercise some conscious choice', 'The interactionist position, as in the diathesis-stress model, holds that a biological vulnerability interacts with environmental triggers', 'Final answer: define both, then explain soft determinism or diathesis-stress as the middle ground'], topic: 'Issues and Debates' },
  { question: 'Discuss the dopamine hypothesis as an explanation for schizophrenia.', marks: 8, markScheme: ['AO1: The original hypothesis proposed hyperdopaminergia, an excess of dopamine in subcortical areas such as Broca’s area, linked to hallucinations', 'AO1: The revised version proposes hypodopaminergia, abnormally low dopamine in the prefrontal cortex, explaining negative symptoms', 'AO3 strength: supported by drug evidence, since amphetamines increase dopamine and induce symptoms, while antipsychotics reduce it and relieve them', 'AO3 limitation: correlation is not causation, as raised dopamine could be a consequence rather than a cause', 'AO3 limitation: it is biologically reductionist and ignores family dysfunction and cognitive factors', 'AO3 limitation: clozapine acts on serotonin as well, suggesting other neurotransmitters are involved', 'Final answer: outline both versions, then evaluate drug evidence, causation, reductionism and other neurotransmitters'], topic: 'Schizophrenia' },
  { question: 'Outline the top-down approach to offender profiling.', marks: 4, markScheme: ['Developed by the FBI from interviews with 36 convicted serial killers', 'Offenders are classified into organised (planned, high intelligence, socially competent) or disorganised (spontaneous, lower intelligence, socially isolated)', 'Profilers work from pre-existing templates, matching the crime scene evidence to a category', 'The stages are data assimilation, crime scene classification, crime reconstruction and profile generation', 'Final answer: pre-existing organised/disorganised templates applied through four stages'], topic: 'Forensic Psychology' },
]

export const PSYCHOLOGY_NOTES = {
  'Social Influence': '<h3>Conformity</h3><p>Types: compliance, identification, internalisation. Explanations: NSI (want to be liked) and ISI (want to be right).</p><p>Asch: 36.8% conformity; affected by group size, unanimity and task difficulty.</p><h3>Obedience</h3><p>Milgram: 65% to 450V. Situational variables: proximity, location, uniform. Explanations: agentic state, legitimacy of authority, authoritarian personality.</p><p class="exam-tip">Exam tip: always link a study back to whether it explains conformity or obedience, and name the variable it manipulated.</p>',
  Memory: '<h3>Models</h3><p>MSM: sensory register, STM (5-9 items, 18-30s, acoustic), LTM (unlimited, lifetime, semantic).</p><p>WMM: central executive, phonological loop, visuo-spatial sketchpad, episodic buffer.</p><h3>Forgetting and EWT</h3><p>Interference (proactive and retroactive) and retrieval failure. EWT affected by leading questions, post-event discussion and anxiety. Cognitive interview has four stages.</p>',
  Attachment: '<h3>Key studies</h3><p>Lorenz (imprinting), Harlow (contact comfort), Schaffer and Emerson (four stages), Ainsworth (Strange Situation).</p><h3>Bowlby</h3><p>Monotropy, social releasers, critical period, internal working model. Maternal deprivation gives risk of affectionless psychopathy.</p><p>Romanian orphan studies: later adoption means worse outcomes.</p>',
  Psychopathology: '<h3>Definitions</h3><p>Statistical infrequency, deviation from social norms, failure to function adequately, deviation from ideal mental health.</p><h3>Disorders</h3><ul><li>Phobias: two-process model; treated by systematic desensitisation or flooding</li><li>Depression: Beck’s negative triad and Ellis’s ABC; treated by CBT/REBT</li><li>OCD: genetic and neural; treated with SSRIs</li></ul>',
  'Approaches in Psychology': '<h3>The approaches</h3><ul><li>Behaviourist: classical and operant conditioning</li><li>Social learning: observation, imitation, mediational processes</li><li>Cognitive: schemas, inference, cognitive neuroscience</li><li>Biological: genes, neurochemistry, evolution</li><li>Psychodynamic: unconscious, id/ego/superego, psychosexual stages</li><li>Humanistic: free will, self-actualisation, congruence</li></ul>',
  Biopsychology: '<h3>Nervous system</h3><p>CNS and peripheral; peripheral splits into somatic and autonomic; autonomic into sympathetic and parasympathetic.</p><h3>Localisation</h3><p>Broca (speech production, frontal), Wernicke (comprehension, temporal). Sperry showed lateralisation via split-brain research.</p><h3>Scanning</h3><p>fMRI (good spatial, poor temporal), EEG/ERP (good temporal, poor spatial), post-mortem.</p>',
  'Research Methods': '<h3>Design</h3><p>Independent groups, repeated measures (counterbalance order effects), matched pairs.</p><h3>Sampling</h3><p>Random, systematic, stratified (most representative), opportunity, volunteer.</p><h3>Validity and reliability</h3><p>Internal vs external validity; test-retest, inter-observer (+0.80), split-half.</p>',
  'Data Handling and Statistics': '<h3>Descriptives</h3><p>Mean (distorted by outliers), median (good for skew), mode (categorical). Standard deviation shows spread.</p><h3>Choosing a test</h3><p>Depends on: difference or correlation, design (related or independent), and level of measurement (nominal, ordinal, interval).</p><p class="exam-tip">Exam tip: p ≤ 0.05 is the standard. Type I = false positive, Type II = false negative.</p>',
  'Issues and Debates': '<h3>The debates</h3><ul><li>Gender bias: α, β, androcentrism</li><li>Culture bias: ethnocentrism vs cultural relativism</li><li>Free will vs determinism (hard, soft, biological, environmental, psychic)</li><li>Nature vs nurture, and the interactionist diathesis-stress model</li><li>Holism vs reductionism</li><li>Idiographic vs nomothetic</li><li>Ethical implications and socially sensitive research</li></ul>',
  Schizophrenia: '<h3>Symptoms</h3><p>Positive (hallucinations, delusions) and negative (avolition, speech poverty).</p><h3>Explanations</h3><p>Biological: genetics, dopamine hypothesis (original hyper subcortical, revised hypo prefrontal), neural correlates. Psychological: family dysfunction, cognitive deficits.</p><h3>Treatment</h3><p>Typical vs atypical antipsychotics, CBT, family therapy, token economies. Interactionist: diathesis-stress.</p>',
  'Forensic Psychology': '<h3>Profiling</h3><p>Top-down (FBI, organised/disorganised templates) vs bottom-up (British, investigative psychology and geographical profiling).</p><h3>Explanations</h3><p>Biological: atavistic form, genetics, neural. Psychological: Eysenck’s criminal personality, cognitive distortions, differential association, psychodynamic.</p><h3>Dealing with offending</h3><p>Custodial sentencing, behaviour modification, anger management, restorative justice.</p>',
}
