/*
  Sociology - AQA A-level (7192).

  Topic strings in FLASHCARDS / MCQ / EXAM must match the titles in GROUPS
  exactly. scripts/check-content.mjs enforces this.
*/

export const SOCIOLOGY_GROUPS = [
  {
    label: 'Paper 1: Education with Theory and Methods',
    subgroups: [
      {
        label: 'Education',
        topics: [
          'Role of Education',
          'Class Differences in Achievement',
          'Ethnicity and Gender in Education',
          'Education Policy',
        ],
      },
      { label: 'Theory and Methods', topics: ['Research Methods', 'Sociological Theory'] },
    ],
  },
  {
    label: 'Paper 2: Topics in Sociology',
    subgroups: [
      { label: 'Families and Households', topics: ['Family Structures and Roles', 'Childhood and Demography'] },
      { label: 'Beliefs in Society', topics: ['Religion and Social Change', 'Secularisation'] },
    ],
  },
  {
    label: 'Paper 3: Crime and Deviance',
    subgroups: [
      {
        label: 'Crime and Deviance',
        topics: ['Theories of Crime', 'Class, Ethnicity and Gender in Crime', 'Control, Punishment and Victims'],
      },
    ],
  },
]

export const SOCIOLOGY_FLASHCARDS = [
  // Role of Education
  { front: 'What is the functionalist view of education?', back: 'Education performs positive functions: Durkheim argued it creates social solidarity and teaches specialist skills; Parsons saw it as a bridge between family and wider society, applying universalistic standards', topic: 'Role of Education' },
  { front: 'Explain Parsons’ idea of meritocracy', back: 'School is a bridge between the particularistic standards of the family and the universalistic standards of society. Status is achieved through effort and ability rather than ascribed', topic: 'Role of Education' },
  { front: 'What is Davis and Moore’s role allocation theory?', back: 'Education sifts and sorts people into the roles best suited to their abilities. Unequal rewards for different jobs motivate people to compete for the most functionally important positions', topic: 'Role of Education' },
  { front: 'What is Althusser’s view of education?', back: 'Education is an Ideological State Apparatus that reproduces class inequality by failing working-class pupils, and legitimates it by making inequality appear fair and inevitable', topic: 'Role of Education' },
  { front: 'What is the correspondence principle?', back: 'Bowles and Gintis argued the hidden curriculum mirrors the workplace: hierarchy, acceptance of authority, extrinsic rewards and fragmented subjects produce an obedient workforce', topic: 'Role of Education' },
  { front: 'What did Willis find in Learning to Labour?', back: 'Twelve working-class "lads" formed a counter-school culture rejecting school values. Their resistance ironically prepared them for the manual labour they ended up in', topic: 'Role of Education' },

  // Class differences
  { front: 'Distinguish material and cultural deprivation', back: 'Material deprivation is a lack of physical resources such as housing, diet and money for equipment. Cultural deprivation is a lack of the values, attitudes and skills needed for success', topic: 'Class Differences in Achievement' },
  { front: 'What is Bernstein’s speech code theory?', back: 'Working-class pupils use a restricted code (context-bound, limited vocabulary); middle-class pupils use an elaborated code (context-free, wider vocabulary) which schools use, giving them an advantage', topic: 'Class Differences in Achievement' },
  { front: 'What is cultural capital?', back: 'Bourdieu’s term for the knowledge, tastes and attitudes of the middle class that schools reward. Combined with economic and educational capital, it reproduces class advantage', topic: 'Class Differences in Achievement' },
  { front: 'What is the self-fulfilling prophecy in education?', back: 'A teacher labels a pupil, the pupil internalises that label, and their behaviour changes to match it. Rosenthal and Jacobson’s "spurters" study demonstrated this experimentally', topic: 'Class Differences in Achievement' },
  { front: 'What is streaming and how does it link to labelling?', back: 'Placing pupils in ability groups. Ball found lower streams were taught by less experienced teachers and entered for lower tier exams, creating polarisation into pro- and anti-school subcultures', topic: 'Class Differences in Achievement' },
  { front: 'What did Douglas find about parental interest?', back: 'Working-class parents visited school less often and showed less interest, which he linked to lower achievement. Criticised because attendance may reflect shift work rather than lack of interest', topic: 'Class Differences in Achievement' },

  // Ethnicity and gender
  { front: 'Give internal and external explanations for ethnic differences in achievement', back: 'Internal: labelling and teacher racism, pupil subcultures, institutional racism, an ethnocentric curriculum. External: cultural deprivation, family structure, material deprivation and racism in wider society', topic: 'Ethnicity and Gender in Education' },
  { front: 'What is institutional racism?', back: 'Discrimination built into the routine ways an institution operates, such as an ethnocentric curriculum, assessment practices, and selection and streaming decisions', topic: 'Ethnicity and Gender in Education' },
  { front: 'Give three external reasons for girls’ improved achievement', back: 'The impact of feminism, changes in the family (more divorce and female-headed households), and changes in women’s employment and ambitions. Sharpe found girls’ priorities shifted from marriage to careers', topic: 'Ethnicity and Gender in Education' },
  { front: 'Give three internal reasons for girls’ improved achievement', back: 'Equal opportunities policies such as GIST and WISE, positive role models among female teachers, and GCSE coursework favouring girls’ organisation. Removal of gender stereotyping from textbooks also helped', topic: 'Ethnicity and Gender in Education' },
  { front: 'Why do some boys underachieve?', back: 'Decline of traditional manual "male" jobs causing an identity crisis, lower literacy from less reading at home, and laddish subcultures where achievement is seen as feminine (Epstein)', topic: 'Ethnicity and Gender in Education' },

  // Education policy
  { front: 'What was the tripartite system and why was it criticised?', back: 'The 1944 Act allocated pupils by 11+ to grammar, secondary modern or technical schools. Criticised for reproducing class and gender inequality, since the pass mark was set higher for girls', topic: 'Education Policy' },
  { front: 'What is marketisation and which act introduced it?', back: 'The 1988 Education Reform Act. It created competition between schools through league tables, formula funding, Ofsted and open enrolment, on the principle of parentocracy', topic: 'Education Policy' },
  { front: 'What is the "A to C economy" and educational triage?', back: 'Gillborn and Youdell: league tables push schools to focus resources on pupils on the C/D borderline, categorising others as hopeless cases, which disadvantages working-class and black pupils', topic: 'Education Policy' },
  { front: 'What is the myth of parentocracy?', back: 'Ball argues marketisation only appears to give all parents choice. Middle-class parents have the cultural and economic capital to be skilled choosers, so choice reproduces inequality', topic: 'Education Policy' },
  { front: 'Give two New Labour policies aimed at reducing inequality', back: 'Education Action Zones and Aim Higher targeted deprived areas; EMA paid students from low income families to stay in education; Sure Start supported early years', topic: 'Education Policy' },

  // Research methods
  { front: 'What does PET stand for in evaluating methods?', back: 'Practical (time, cost, access), Ethical (consent, harm, confidentiality, deception) and Theoretical (validity, reliability, representativeness) factors', topic: 'Research Methods' },
  { front: 'Compare positivism and interpretivism', back: 'Positivists want objective, quantitative data, reliability and generalisable laws, favouring questionnaires and official statistics. Interpretivists want qualitative data and verstehen, favouring unstructured interviews and observation', topic: 'Research Methods' },
  { front: 'Give strengths and limitations of participant observation', back: 'Strengths: high validity, verstehen, and it can uncover behaviour hidden from other methods. Limitations: time consuming, hard to replicate so low reliability, risk of going native, and ethical issues if covert', topic: 'Research Methods' },
  { front: 'Give strengths and limitations of questionnaires', back: 'Strengths: cheap, quick, large representative samples, reliable and easily quantified. Limitations: low response rates, imposed answer categories, risk of lying, and no ability to clarify meaning', topic: 'Research Methods' },
  { front: 'What are official statistics and what problem do interpretivists identify?', back: 'Quantitative data collected by government, such as crime or exam statistics. Interpretivists argue they are socially constructed, reflecting the decisions of those who record them rather than objective reality', topic: 'Research Methods' },
  { front: 'What is triangulation?', back: 'Using two or more methods together so the strengths of one compensate for the weaknesses of the other, for example combining a survey with follow-up interviews', topic: 'Research Methods' },

  // Theory
  { front: 'Summarise the functionalist view of society', back: 'Society is a system of interdependent parts, like an organism, held together by value consensus. Institutions perform functions that maintain order and meet society’s functional prerequisites', topic: 'Sociological Theory' },
  { front: 'Summarise the Marxist view of society', back: 'Society is divided into the bourgeoisie who own the means of production and the proletariat who sell their labour. The economic base shapes the superstructure, and false class consciousness maintains exploitation', topic: 'Sociological Theory' },
  { front: 'Distinguish liberal, Marxist and radical feminism', back: 'Liberal feminists seek gradual reform through law and policy. Marxist feminists see women’s oppression as serving capitalism. Radical feminists see patriarchy as the fundamental division and men as the oppressors', topic: 'Sociological Theory' },
  { front: 'What is social action theory?', back: 'A micro approach focusing on how individuals give meaning to situations. Weber argued we need both structural causes and an understanding of actors’ meanings (verstehen)', topic: 'Sociological Theory' },
  { front: 'What is postmodernism?', back: 'The view that society has fragmented, metanarratives have lost credibility, identity is chosen and fluid, and knowledge is relative. Criticised for making objective sociology impossible', topic: 'Sociological Theory' },
  { front: 'Can sociology be value free?', back: 'Positivists say yes, through objective scientific method. Weber said values are needed in choosing a topic but not in collecting data. Gouldner argued value freedom is impossible and sociologists should take sides', topic: 'Sociological Theory' },

  // Family
  { front: 'What is the functionalist view of the family?', back: 'Murdock identified four functions: sexual, reproductive, economic and educational. Parsons argued the nuclear family performs two irreducible functions: primary socialisation and the stabilisation of adult personalities', topic: 'Family Structures and Roles' },
  { front: 'What is the Marxist view of the family?', back: 'The family serves capitalism: it is a unit of consumption, inheritance of private property maintains class inequality, and it socialises children into accepting hierarchy. Zaretsky called it a "haven" that cushions exploitation', topic: 'Family Structures and Roles' },
  { front: 'What are conjugal roles and the symmetrical family?', back: 'Segregated roles are separate and distinct; joint roles are shared. Young and Willmott argued the family has become symmetrical, with roles more equal, as part of the march of progress', topic: 'Family Structures and Roles' },
  { front: 'What is the dual burden and the triple shift?', back: 'The dual burden is women doing both paid work and the bulk of domestic labour. Duncombe and Marsden added emotion work, giving a triple shift', topic: 'Family Structures and Roles' },
  { front: 'Give four reasons for the increase in divorce', back: 'Changes in law making divorce cheaper and easier, declining stigma and secularisation, rising expectations of marriage, and women’s increased financial independence', topic: 'Family Structures and Roles' },
  { front: 'What is the personal life perspective on families?', back: 'It rejects a fixed definition of family, arguing we should study the meanings people give to relationships, including chosen families, fictive kin, pets and even relationships with the dead', topic: 'Family Structures and Roles' },

  // Childhood
  { front: 'What is the social construction of childhood?', back: 'Childhood is not natural or universal but shaped by culture and time. Aries argued that in medieval Europe childhood as a separate status did not exist, and children were "little adults"', topic: 'Childhood and Demography' },
  { front: 'Give arguments for the march of progress view of childhood', back: 'Children today are better fed, healthier, better educated and legally protected. Higher living standards, smaller families and child protection laws mean childhood is far better than in the past', topic: 'Childhood and Demography' },
  { front: 'What is the conflict view of childhood?', back: 'Inequalities remain between children by class, gender and ethnicity, and adults exercise control over children’s space, time, bodies and resources. Firestone called protection a form of oppression', topic: 'Childhood and Demography' },
  { front: 'Give reasons for the decline in the birth rate', back: 'Changes in women’s position, a fall in the infant mortality rate, children becoming an economic liability, and child-centredness leading to quality over quantity', topic: 'Childhood and Demography' },
  { front: 'What are the consequences of an ageing population?', back: 'More pressure on public services and pensions, a rising dependency ratio, more one-person pensioner households, and the emergence of ageism as an issue', topic: 'Childhood and Demography' },

  // Religion
  { front: 'What is the functionalist view of religion?', back: 'Durkheim argued religion reinforces collective conscience through worship of the sacred, which is really society itself. Malinowski said it helps at times of uncertainty; Parsons said it provides meaning and values', topic: 'Religion and Social Change' },
  { front: 'What is the Marxist view of religion?', back: 'Religion is the "opium of the people": it legitimates suffering, promises an afterlife, and produces false class consciousness that prevents revolution. It is an ideological weapon of the ruling class', topic: 'Religion and Social Change' },
  { front: 'What is Weber’s argument in The Protestant Ethic?', back: 'Calvinist beliefs in predestination and the calling created an ascetic lifestyle where wealth was reinvested rather than spent. This provided the spirit of modern capitalism, so religion can cause social change', topic: 'Religion and Social Change' },
  { front: 'What is liberation theology?', back: 'A movement in 1960s Latin America where Catholic priests supported the poor against oppressive regimes, showing religion can be a force for radical social change rather than conservatism', topic: 'Religion and Social Change' },
  { front: 'Distinguish churches, sects, denominations and cults', back: 'Troeltsch: churches are large, universal and linked to the state; sects are small, exclusive and hostile to society. Niebuhr added denominations (accepting of society) and cults (individualistic and world-affirming)', topic: 'Religion and Social Change' },

  // Secularisation
  { front: 'What is secularisation?', back: 'Wilson defined it as the process whereby religious beliefs, practices and institutions lose social significance. Evidence includes declining attendance, fewer religious marriages, and fewer clergy', topic: 'Secularisation' },
  { front: 'What is Weber’s disenchantment argument?', back: 'Rational, scientific ways of thinking replace religious explanations of the world, undermining the religious worldview and removing the sense of mystery and magic', topic: 'Secularisation' },
  { front: 'What is Berger’s sacred canopy and religious diversity argument?', back: 'A single shared religion once acted as a sacred canopy giving one plausible worldview. Religious diversity creates a crisis of credibility, since competing versions of the truth undermine each other', topic: 'Secularisation' },
  { front: 'Give three criticisms of the secularisation thesis', back: 'Religion has changed rather than declined (believing without belonging, Davie); it has grown globally, especially fundamentalism; and statistics on attendance are unreliable measures of belief', topic: 'Secularisation' },
  { front: 'What is the religious market theory?', back: 'Stark and Bainbridge argue religion never declines, it only changes form. Where there is competition and choice, religious participation rises, as in the USA', topic: 'Secularisation' },

  // Crime theories
  { front: 'What is Durkheim’s functionalist view of crime?', back: 'Crime is inevitable and universal, and performs positive functions: boundary maintenance, adaptation and change, and a safety valve. Too much crime, however, threatens social order', topic: 'Theories of Crime' },
  { front: 'Explain Merton’s strain theory', back: 'When society sets goals (the American Dream) but blocks legitimate means for some, strain results. Five adaptations: conformity, innovation, ritualism, retreatism and rebellion', topic: 'Theories of Crime' },
  { front: 'What is status frustration?', back: 'Cohen argued working-class boys who fail in the middle-class school system suffer status frustration and form delinquent subcultures that invert mainstream values to gain status', topic: 'Theories of Crime' },
  { front: 'Name Cloward and Ohlin’s three subcultures', back: 'Criminal (organised, with an illegitimate opportunity structure), conflict (loosely organised, gang violence for status), and retreatist (drug use, double failure in both legitimate and illegitimate structures)', topic: 'Theories of Crime' },
  { front: 'Explain labelling theory of crime', back: 'No act is inherently deviant; deviance is created by societal reaction. Becker’s moral entrepreneurs create rules, and being labelled leads to a master status, self-fulfilling prophecy and secondary deviance', topic: 'Theories of Crime' },
  { front: 'What is a deviance amplification spiral?', back: 'Media exaggeration creates moral panic and a folk devil, prompting a crackdown, which increases visible deviance and appears to confirm the original panic. Cohen’s Mods and Rockers study demonstrated this', topic: 'Theories of Crime' },
  { front: 'What is right realism and its main policy?', back: 'Crime is a rational choice by individuals, linked to poor socialisation and low self-control. Wilson and Kelling’s broken windows theory advocates zero tolerance policing and target hardening', topic: 'Theories of Crime' },
  { front: 'What is left realism and its main policy?', back: 'Lea and Young argue crime is caused by relative deprivation, subculture and marginalisation. Policies should tackle inequality and use democratic, community-based policing', topic: 'Theories of Crime' },

  // Class, ethnicity, gender in crime
  { front: 'Why might official crime statistics under-represent white-collar crime?', back: 'It is often invisible, complex and hard to detect, victims may be unaware, and organisations may handle it internally rather than reporting it to avoid reputational damage', topic: 'Class, Ethnicity and Gender in Crime' },
  { front: 'What is the difference between occupational and corporate crime?', back: 'Occupational crime is committed by employees for personal gain against the organisation. Corporate crime is committed by or for the organisation itself in pursuit of its goals', topic: 'Class, Ethnicity and Gender in Crime' },
  { front: 'Give explanations for ethnic differences in the crime statistics', back: 'Either real differences from racism, marginalisation and relative deprivation, or the product of policing: disproportionate stop and search, canteen culture, and institutional racism in the criminal justice system', topic: 'Class, Ethnicity and Gender in Crime' },
  { front: 'What is the chivalry thesis and the evidence against it?', back: 'The claim that the justice system treats women more leniently. Against it: Heidensohn found double standards, and women are punished more harshly for deviating from gender norms', topic: 'Class, Ethnicity and Gender in Crime' },
  { front: 'Explain Heidensohn’s control theory of female crime', back: 'Women commit less crime because patriarchal society controls them more effectively: control at home through domestic roles, in public through fear of violence, and at work through male supervision', topic: 'Class, Ethnicity and Gender in Crime' },
  { front: 'What is the "liberation thesis"?', back: 'Adler argued that as women became more liberated from patriarchal control, their crime would become more frequent and more serious, mirroring male patterns. Criticised as female crime rose before liberation', topic: 'Class, Ethnicity and Gender in Crime' },

  // Control and punishment
  { front: 'Explain Foucault’s idea of disciplinary power', back: 'Punishment shifted from sovereign power over the body to disciplinary power over the mind. The panopticon means prisoners self-survey because they never know when they are watched, so surveillance becomes self-discipline', topic: 'Control, Punishment and Victims' },
  { front: 'What are the two main justifications for punishment?', back: 'Reduction (deterrence, rehabilitation and incapacitation, aiming to prevent future crime) and retribution (punishing because the offender deserves it, expressing society’s outrage)', topic: 'Control, Punishment and Victims' },
  { front: 'What is situational crime prevention?', back: 'Reducing opportunities for crime through target hardening and design, based on rational choice theory. Criticised for displacement, moving crime elsewhere rather than reducing it', topic: 'Control, Punishment and Victims' },
  { front: 'Distinguish positivist and critical victimology', back: 'Positivist victimology looks for patterns and victim proneness, risking victim blaming. Critical victimology focuses on structural powerlessness and the state’s power to deny victim status', topic: 'Control, Punishment and Victims' },
  { front: 'What are the two types of surveillance beyond the panopticon?', back: 'Synoptic surveillance, where the many watch the few (media and citizen recording), and actuarial justice, where risk profiling predicts and screens rather than punishing after the fact', topic: 'Control, Punishment and Victims' },
]

export const SOCIOLOGY_MCQ = [
  { question: 'Which sociologist argued education creates social solidarity?', options: ['Parsons', 'Durkheim', 'Althusser', 'Bourdieu'], answer: 1, explanation: 'Durkheim saw education as transmitting shared culture and creating social solidarity.', topic: 'Role of Education' },
  { question: 'The correspondence principle was proposed by', options: ['Willis', 'Bowles and Gintis', 'Bernstein', 'Becker'], answer: 1, explanation: 'Bowles and Gintis argued the hidden curriculum mirrors the workplace.', topic: 'Role of Education' },
  { question: 'Althusser described education as an', options: ['Ideological State Apparatus', 'organic analogy', 'illegitimate opportunity structure', 'agent of value consensus'], answer: 0, explanation: 'Education is an ISA reproducing and legitimating class inequality.', topic: 'Role of Education' },
  { question: 'Willis found the "lads" formed a', options: ['pro-school subculture', 'counter-school culture', 'meritocracy', 'sacred canopy'], answer: 1, explanation: 'They rejected school values, which ironically prepared them for manual work.', topic: 'Role of Education' },
  { question: 'Cultural capital is associated with', options: ['Bourdieu', 'Merton', 'Durkheim', 'Cohen'], answer: 0, explanation: 'Bourdieu argued middle-class culture is rewarded by schools.', topic: 'Class Differences in Achievement' },
  { question: 'Bernstein’s restricted code is characterised by', options: ['wide vocabulary and context-free meanings', 'limited vocabulary and context-bound meanings', 'formal grammar', 'written language only'], answer: 1, explanation: 'The restricted code is context-bound with a narrower vocabulary.', topic: 'Class Differences in Achievement' },
  { question: 'A pupil internalising a teacher label and living up to it is a', options: ['moral panic', 'self-fulfilling prophecy', 'status frustration', 'deviance amplification'], answer: 1, explanation: 'The label becomes true through the pupil acting on it.', topic: 'Class Differences in Achievement' },
  { question: 'The ethnocentric curriculum is an example of', options: ['material deprivation', 'institutional racism', 'marketisation', 'meritocracy'], answer: 1, explanation: 'It privileges one culture within the routine workings of the institution.', topic: 'Ethnicity and Gender in Education' },
  { question: 'Sharpe’s research showed girls’ priorities shifted towards', options: ['marriage and family', 'careers and independence', 'part-time work', 'domestic roles'], answer: 1, explanation: 'Her 1970s and 1990s comparison found a shift towards careers and self-sufficiency.', topic: 'Ethnicity and Gender in Education' },
  { question: 'Which act introduced marketisation of education?', options: ['1944 Education Act', '1988 Education Reform Act', '1965 Circular 10/65', '2010 Academies Act'], answer: 1, explanation: 'The 1988 ERA brought league tables, formula funding and open enrolment.', topic: 'Education Policy' },
  { question: 'The "A to C economy" was identified by', options: ['Ball', 'Gillborn and Youdell', 'Bourdieu', 'Willis'], answer: 1, explanation: 'They described educational triage driven by league tables.', topic: 'Education Policy' },
  { question: 'Which method would an interpretivist most likely favour?', options: ['Structured questionnaire', 'Official statistics', 'Unstructured interview', 'Laboratory experiment'], answer: 2, explanation: 'Interpretivists want rich qualitative data and verstehen.', topic: 'Research Methods' },
  { question: 'A key strength of questionnaires is', options: ['high validity', 'reliability and large samples', 'verstehen', 'flexibility'], answer: 1, explanation: 'They are standardised, so reliable, and can reach large representative samples cheaply.', topic: 'Research Methods' },
  { question: 'Going native is a risk in', options: ['questionnaires', 'participant observation', 'official statistics', 'structured interviews'], answer: 1, explanation: 'The researcher becomes over-involved and loses objectivity.', topic: 'Research Methods' },
  { question: 'Which theory sees society as based on value consensus?', options: ['Marxism', 'Functionalism', 'Feminism', 'Postmodernism'], answer: 1, explanation: 'Functionalism sees shared norms and values holding society together.', topic: 'Sociological Theory' },
  { question: 'Radical feminists identify the fundamental division in society as', options: ['class', 'patriarchy', 'ethnicity', 'age'], answer: 1, explanation: 'Radical feminism sees patriarchy as the primary and universal form of oppression.', topic: 'Sociological Theory' },
  { question: 'Weber’s concept of verstehen means', options: ['objectivity', 'empathetic understanding', 'value freedom', 'social facts'], answer: 1, explanation: 'Verstehen is understanding the meanings actors give to their actions.', topic: 'Sociological Theory' },
  { question: 'Parsons argued the nuclear family has how many irreducible functions?', options: ['One', 'Two', 'Four', 'Six'], answer: 1, explanation: 'Primary socialisation and stabilisation of adult personalities.', topic: 'Family Structures and Roles' },
  { question: 'The triple shift adds which element to the dual burden?', options: ['Childcare', 'Emotion work', 'Paid work', 'Housework'], answer: 1, explanation: 'Duncombe and Marsden identified emotion work as a third shift.', topic: 'Family Structures and Roles' },
  { question: 'Young and Willmott described the modern family as', options: ['patriarchal', 'symmetrical', 'segregated', 'extended'], answer: 1, explanation: 'They argued for a march of progress towards symmetry in conjugal roles.', topic: 'Family Structures and Roles' },
  { question: 'Aries argued that in medieval society', options: ['childhood was highly protected', 'childhood as a separate status did not exist', 'children had legal rights', 'children were educated separately'], answer: 1, explanation: 'He argued children were treated as "little adults" with no distinct status.', topic: 'Childhood and Demography' },
  { question: 'An ageing population increases', options: ['the birth rate', 'the dependency ratio', 'infant mortality', 'net migration'], answer: 1, explanation: 'More non-working older people raises the dependency ratio.', topic: 'Childhood and Demography' },
  { question: 'Marx described religion as', options: ['the sacred canopy', 'the opium of the people', 'the Protestant ethic', 'a civil religion'], answer: 1, explanation: 'Religion dulls the pain of exploitation and prevents revolution.', topic: 'Religion and Social Change' },
  { question: 'Weber linked the rise of capitalism to which religious group?', options: ['Catholics', 'Calvinists', 'Anglicans', 'Methodists'], answer: 1, explanation: 'Calvinist asceticism and the calling produced the spirit of capitalism.', topic: 'Religion and Social Change' },
  { question: 'Which is small, exclusive and hostile to wider society?', options: ['Church', 'Denomination', 'Sect', 'Cult'], answer: 2, explanation: 'Troeltsch defined sects as small and in tension with society.', topic: 'Religion and Social Change' },
  { question: 'Davie’s phrase for religion changing rather than declining is', options: ['disenchantment', 'believing without belonging', 'the sacred canopy', 'religious pluralism'], answer: 1, explanation: 'People retain belief while attending less often.', topic: 'Secularisation' },
  { question: 'Durkheim argued crime is', options: ['always harmful', 'inevitable and functional', 'caused by biology', 'a media creation'], answer: 1, explanation: 'Crime performs boundary maintenance, adaptation and acts as a safety valve.', topic: 'Theories of Crime' },
  { question: 'In Merton’s strain theory, using illegitimate means to achieve goals is', options: ['conformity', 'innovation', 'ritualism', 'retreatism'], answer: 1, explanation: 'Innovators accept the goals but reject the legitimate means.', topic: 'Theories of Crime' },
  { question: 'Status frustration was proposed by', options: ['Merton', 'Cohen', 'Becker', 'Young'], answer: 1, explanation: 'Cohen argued working-class boys form delinquent subcultures after failing at school.', topic: 'Theories of Crime' },
  { question: 'A label becoming the dominant identity of an individual is a', options: ['moral panic', 'master status', 'folk devil', 'primary deviance'], answer: 1, explanation: 'Becker argued the deviant label can override all other identities.', topic: 'Theories of Crime' },
  { question: 'Broken windows theory is associated with', options: ['left realism', 'right realism', 'Marxism', 'labelling theory'], answer: 1, explanation: 'Wilson and Kelling’s right realist argument for zero tolerance policing.', topic: 'Theories of Crime' },
  { question: 'Left realists explain crime through relative deprivation, marginalisation and', options: ['biology', 'subculture', 'genetics', 'rational choice'], answer: 1, explanation: 'Lea and Young identify these three causes.', topic: 'Theories of Crime' },
  { question: 'Corporate crime is committed', options: ['by employees against the organisation', 'by or for the organisation', 'by individuals for personal use', 'only by governments'], answer: 1, explanation: 'Corporate crime serves the organisation’s own goals.', topic: 'Class, Ethnicity and Gender in Crime' },
  { question: 'Heidensohn explained low female crime rates through', options: ['the chivalry thesis', 'patriarchal control', 'the liberation thesis', 'biology'], answer: 1, explanation: 'Control at home, in public and at work restricts women’s opportunities to offend.', topic: 'Class, Ethnicity and Gender in Crime' },
  { question: 'Foucault’s panopticon illustrates', options: ['retribution', 'self-surveillance and disciplinary power', 'incapacitation', 'restorative justice'], answer: 1, explanation: 'Not knowing when you are watched produces self-discipline.', topic: 'Control, Punishment and Victims' },
  { question: 'A criticism of situational crime prevention is', options: ['it is too expensive', 'displacement of crime', 'it ignores rational choice', 'it targets only white-collar crime'], answer: 1, explanation: 'Crime may simply move in time, place, target or method.', topic: 'Control, Punishment and Victims' },
]

export const SOCIOLOGY_EXAM = [
  { question: 'Outline two functions that the education system performs according to functionalists.', marks: 4, markScheme: ['Creating social solidarity: Durkheim argued school transmits shared culture and history so individuals see themselves as part of a wider community', 'Teaching specialist skills for a complex division of labour, so the economy can function', 'Role allocation: Davis and Moore argued education sifts and sorts individuals into roles matching their ability', 'Acting as a bridge between family and society, moving from particularistic to universalistic standards (Parsons)', 'Final answer: any two functions, each identified and developed'], topic: 'Role of Education' },
  { question: 'Outline three ways in which cultural factors may explain social class differences in educational achievement.', marks: 6, markScheme: ['Cultural deprivation: working-class families may lack the values, attitudes and intellectual stimulation the school rewards', 'Bernstein’s speech codes: schools use the elaborated code, giving middle-class pupils an advantage as it is their everyday language', 'Cultural capital: Bourdieu argued middle-class tastes and knowledge are valued by schools, which converts into educational capital', 'Attitudes to deferred gratification, with working-class subcultures said to favour immediate gratification (Sugarman)', 'Final answer: any three factors, each identified and explained'], topic: 'Class Differences in Achievement' },
  { question: 'Applying material from the item, analyse two ways in which marketisation policies may have increased inequality in education.', marks: 10, markScheme: ['League tables and the A to C economy: schools focus resources on C/D borderline pupils and practise educational triage, disadvantaging working-class and black pupils (Gillborn and Youdell)', 'Cream-skimming and silt-shifting: good schools select higher achieving, mostly middle-class pupils and offload less able ones, reproducing inequality', 'The myth of parentocracy: Ball argues middle-class parents have the cultural and economic capital to be skilled choosers, so choice is unequal', 'Funding formula: popular schools get more funding and can afford better teachers and facilities, widening the gap', 'Evaluation: some policies such as EMA and pupil premium have compensated, and marketisation may raise standards overall', 'Final answer: two developed ways, applied to the item, with evaluation'], topic: 'Education Policy' },
  { question: 'Evaluate the usefulness of participant observation for studying pupil subcultures.', marks: 20, markScheme: ['Practical: gaining access to pupil groups is difficult for an adult researcher, and the study is time consuming; covert observation risks discovery', 'Ethical: covert research means no informed consent and involves deception; the researcher may witness illegal or harmful behaviour', 'Theoretical strength: high validity and verstehen, as the researcher sees actual behaviour in its natural setting rather than what pupils claim they do', 'Theoretical strength: it can uncover subcultures and meanings that questionnaires would miss entirely, favoured by interpretivists', 'Theoretical limitation: low reliability, as the study cannot be replicated and depends on the individual researcher', 'Theoretical limitation: small samples mean findings are not representative or generalisable, which positivists reject', 'Theoretical limitation: the Hawthorne effect in overt observation, and going native in covert observation, both threaten validity', 'Application: Willis used participant observation with the lads; his rich data revealed the counter-school culture but has been criticised as unrepresentative of just 12 boys', 'Final answer: a balanced evaluation using PET factors, applied to pupil subcultures, reaching a supported conclusion'], topic: 'Research Methods' },
  { question: 'Outline two criticisms of the functionalist view of the family.', marks: 4, markScheme: ['It ignores the dark side of family life, such as domestic violence and child abuse, presenting an idealised picture', 'It is out of date: it assumes a nuclear family with segregated roles, ignoring family diversity such as lone-parent, reconstituted and same-sex families', 'Marxists argue it ignores how the family serves capitalism rather than society as a whole', 'Feminists argue it ignores the exploitation of women through unpaid domestic labour', 'Final answer: any two criticisms, each identified and explained'], topic: 'Family Structures and Roles' },
  { question: 'Outline three reasons for the increase in the divorce rate since the 1960s.', marks: 6, markScheme: ['Changes in the law: the 1969 Divorce Reform Act allowed irretrievable breakdown, and legal aid made divorce affordable', 'Declining stigma and secularisation: divorce is no longer shameful and the churches’ influence over marriage has weakened', 'Rising expectations of marriage: Fletcher argued higher expectations of romantic love make people less willing to tolerate an unhappy marriage', 'Women’s increased financial independence through paid employment means they are less dependent on a husband; most petitions are filed by women', 'Final answer: any three reasons, each identified and explained'], topic: 'Family Structures and Roles' },
  { question: 'Outline and explain two ways in which religion may act as a conservative force.', marks: 10, markScheme: ['Functionalist view: religion reinforces value consensus and collective conscience, so it maintains existing norms and social order (Durkheim)', 'Marxist view: religion legitimates inequality by presenting it as divinely ordained and offers an illusory afterlife, producing false class consciousness', 'Feminist view: religion transmits patriarchal ideology, for example through male-dominated hierarchies and sacred texts that subordinate women', 'Evaluation: Weber shows religion can also cause change (Calvinism), and liberation theology shows it can challenge oppression', 'Final answer: two developed ways with an evaluative counterpoint'], topic: 'Religion and Social Change' },
  { question: 'Outline two criticisms of the secularisation thesis.', marks: 4, markScheme: ['Religion has changed rather than declined: Davie argues people practise believing without belonging, so attendance figures underestimate belief', 'Religion has grown globally, particularly fundamentalism and Pentecostalism, so secularisation is at best a Western phenomenon', 'Statistics are unreliable: historical attendance figures may have been inflated for social respectability rather than genuine belief', 'Religious market theory argues participation rises where there is genuine choice and competition, as in the USA', 'Final answer: any two criticisms, each explained'], topic: 'Secularisation' },
  { question: 'Outline Merton’s strain theory of crime and deviance.', marks: 6, markScheme: ['Society sets culturally approved goals, such as material success in the American Dream', 'It also sets legitimate means of achieving them, such as education and hard work', 'Some groups, particularly the working class, are blocked from the legitimate means by inequality of opportunity', 'The resulting strain to anomie produces deviant adaptations', 'The five adaptations are conformity, innovation (crime), ritualism, retreatism and rebellion', 'Innovation explains utilitarian crime, as the goal is accepted but the means rejected', 'Final answer: goals, means, blocked opportunity, strain, and the five adaptations'], topic: 'Theories of Crime' },
  { question: 'Applying material from the item, analyse two ways in which labelling theory helps explain patterns of crime.', marks: 10, markScheme: ['Selective law enforcement: police use typifications and stereotypes, so certain groups are more likely to be stopped, arrested and charged, producing biased statistics', 'The self-fulfilling prophecy: once labelled, an individual takes on a deviant master status, is rejected by mainstream society and turns to a deviant subculture, producing secondary deviance', 'Deviance amplification: media exaggeration creates moral panics and folk devils, prompting crackdowns that increase recorded deviance (Cohen’s Mods and Rockers)', 'Evaluation: it is deterministic in implying a label inevitably leads to deviance, and it fails to explain the original primary deviance', 'Final answer: two developed ways applied to the item, with evaluation'], topic: 'Theories of Crime' },
  { question: 'Outline two reasons why official crime statistics may not give a valid picture of the extent of crime.', marks: 4, markScheme: ['The dark figure of crime: many offences are never reported by victims, for example because they are seen as too trivial, too personal, or the victim fears reprisal', 'Police discretion and recording practices: officers use typifications and may not record all reported offences, so statistics reflect police activity as much as criminal activity', 'White-collar and corporate crime is under-represented because it is hard to detect and often dealt with internally', 'Final answer: any two reasons, each identified and explained'], topic: 'Class, Ethnicity and Gender in Crime' },
  { question: 'Outline two explanations for gender differences in recorded crime rates.', marks: 4, markScheme: ['The chivalry thesis: the criminal justice system treats women more leniently because it is male dominated and socialised to be protective, so female crime is under-recorded', 'Heidensohn’s control theory: patriarchal society controls women at home through domestic roles, in public through fear of male violence, and at work through male supervision, reducing opportunity to offend', 'Sex role theory: girls are socialised differently, with less risk-taking and closer supervision than boys', 'Final answer: any two explanations, each identified and explained'], topic: 'Class, Ethnicity and Gender in Crime' },
  { question: 'Explain Foucault’s distinction between sovereign power and disciplinary power.', marks: 6, markScheme: ['Sovereign power operated before the nineteenth century, exercised by the monarch over the physical body of the subject', 'Punishment was public, spectacular and inflicted directly on the body, such as branding or execution', 'Disciplinary power governs the mind as well as the body, through surveillance rather than force', 'The panopticon is the model: prisoners can be seen at any time but never know when they are watched', 'This uncertainty causes prisoners to monitor and discipline themselves, so surveillance becomes internalised', 'Foucault argues this form of control has spread throughout society, into schools, workplaces and hospitals', 'Final answer: contrast bodily public punishment with internalised self-surveillance via the panopticon'], topic: 'Control, Punishment and Victims' },
]

export const SOCIOLOGY_NOTES = {
  'Role of Education': '<h3>Consensus views</h3><p>Durkheim: social solidarity and specialist skills. Parsons: bridge from particularistic to universalistic standards, meritocracy. Davis and Moore: role allocation.</p><h3>Conflict views</h3><p>Althusser: Ideological State Apparatus. Bowles and Gintis: correspondence principle and the myth of meritocracy. Willis: counter-school culture.</p>',
  'Class Differences in Achievement': '<h3>External factors</h3><p>Cultural deprivation (Bernstein speech codes, Douglas parental interest, Sugarman deferred gratification), material deprivation, cultural capital (Bourdieu).</p><h3>Internal factors</h3><p>Labelling, self-fulfilling prophecy (Rosenthal and Jacobson), streaming and polarisation (Ball, Lacey), pupil subcultures.</p>',
  'Ethnicity and Gender in Education': '<h3>Ethnicity</h3><p>External: cultural and material deprivation, racism in society. Internal: labelling, ethnocentric curriculum, institutional racism, pupil responses.</p><h3>Gender</h3><p>Girls’ improvement: feminism, family change, employment change, equal opportunities policies, coursework. Boys: identity crisis, literacy, laddish subcultures.</p>',
  'Education Policy': '<h3>Timeline</h3><p>1944 tripartite system, 1965 comprehensives, 1988 ERA (marketisation), New Labour compensatory policies, Coalition academies and free schools.</p><p class="exam-tip">Exam tip: for any policy question, ask whether it increased equality, choice, or standards, and who benefited.</p>',
  'Research Methods': '<h3>PET</h3><p>Practical, Ethical and Theoretical factors decide method choice.</p><h3>Positivism vs interpretivism</h3><p>Positivists: quantitative, reliable, representative, seeking laws. Interpretivists: qualitative, valid, verstehen.</p><p>Methods: questionnaires, interviews, observation, experiments, official statistics, documents. Triangulation combines them.</p>',
  'Sociological Theory': '<h3>Structural</h3><p>Functionalism (consensus, organic analogy), Marxism (base and superstructure, class conflict), Feminism (liberal, Marxist, radical, difference).</p><h3>Action and beyond</h3><p>Social action theory (Weber, verstehen), interactionism, postmodernism, late modernity. Debates: science, value freedom, sociology and social policy.</p>',
  'Family Structures and Roles': '<h3>Perspectives</h3><p>Functionalist (Murdock four functions, Parsons two irreducible functions), Marxist (inheritance, unit of consumption), Feminist (patriarchy, dual burden, triple shift), personal life perspective.</p><h3>Change</h3><p>Divorce, cohabitation, lone-parent and reconstituted families, same-sex couples, and increasing diversity.</p>',
  'Childhood and Demography': '<h3>Childhood</h3><p>Socially constructed (Aries). March of progress vs conflict view. Debate over the disappearance of childhood (Postman).</p><h3>Demography</h3><p>Falling birth and death rates, ageing population, rising dependency ratio, migration and globalisation.</p>',
  'Religion and Social Change': '<h3>Conservative force</h3><p>Functionalism (collective conscience), Marxism (opium of the people), Feminism (patriarchal ideology).</p><h3>Force for change</h3><p>Weber (Calvinism and capitalism), liberation theology, the American civil rights movement.</p><h3>Organisations</h3><p>Church, denomination, sect, cult; New Religious Movements and New Age.</p>',
  Secularisation: '<h3>Evidence for</h3><p>Falling attendance, fewer religious marriages, fewer clergy. Explanations: rationalisation and disenchantment (Weber), religious diversity and the sacred canopy (Berger), social and cultural diversity.</p><h3>Evidence against</h3><p>Believing without belonging (Davie), vicarious religion, religious market theory, global growth of fundamentalism.</p>',
  'Theories of Crime': '<h3>Structural</h3><p>Functionalism (Durkheim), strain theory (Merton), subcultural (Cohen status frustration; Cloward and Ohlin three subcultures), Marxism, neo-Marxism.</p><h3>Interactionist</h3><p>Labelling (Becker), master status, secondary deviance, moral panics and deviance amplification (Cohen).</p><h3>Realism</h3><p>Right realism (rational choice, broken windows, zero tolerance) vs left realism (relative deprivation, subculture, marginalisation).</p>',
  'Class, Ethnicity and Gender in Crime': '<h3>Class</h3><p>White-collar, occupational and corporate crime are under-represented in statistics because they are invisible and hard to detect.</p><h3>Ethnicity</h3><p>Real differences vs the product of policing: stop and search, canteen culture, institutional racism.</p><h3>Gender</h3><p>Chivalry thesis, Heidensohn control theory, Carlen class and gender deals, Adler liberation thesis, masculinity (Messerschmidt).</p>',
  'Control, Punishment and Victims': '<h3>Punishment</h3><p>Reduction (deterrence, rehabilitation, incapacitation) vs retribution. Durkheim on functions of punishment; Marxists on punishment as class control; Foucault on disciplinary power and the panopticon.</p><h3>Prevention</h3><p>Situational, environmental and social and community crime prevention.</p><h3>Victims</h3><p>Positivist victimology (victim proneness, risks victim blaming) vs critical victimology (structural powerlessness).</p>',
}
