/*
  A third batch of OCR H446 Computer Science content.

  CS was already the best-covered subject, so this tops up the chapters that
  sat lowest rather than spreading evenly: Web Technologies, Elements of
  Computational Thinking and Computational Methods were on 7-8 exam
  questions where Databases and Data Structures had 14. It also adds MCQs
  across every chapter so a second session doesn't just repeat the first.

  Mark schemes follow the pack convention: marking points, then a "Final
  answer:" line to self-mark a whole response against.
*/

export const CS_EXAM_3 = [
  {
    question: 'Explain the difference between client-side and server-side processing, giving one example of each and one advantage of each.',
    marks: 6,
    markScheme: [
      'Client-side processing runs in the user’s browser, typically JavaScript',
      'Example: validating that an email field is non-empty before the form is submitted',
      'Advantage: instant response with no round trip, and it reduces load on the server',
      'Server-side processing runs on the web server, e.g. PHP or Python',
      'Example: checking login credentials against a database, or processing a payment',
      'Advantage: the code and data are hidden from the user, so it cannot be tampered with',
      'Final answer: Client-side code runs in the browser (e.g. JavaScript form validation), giving instant feedback and reducing server load; server-side code runs on the server (e.g. checking credentials against a database), keeping logic and data secure from the user. Security-critical checks must always be repeated server-side.',
    ],
    topic: 'Web Technologies',
  },
  {
    question: 'Describe how a search engine uses web crawlers and indexing to return results, and explain the purpose of the PageRank algorithm.',
    marks: 8,
    markScheme: [
      'Web crawlers (spiders) follow hyperlinks between pages automatically',
      'They collect page content and metadata, respecting robots.txt exclusions',
      'An index is built mapping keywords to the pages containing them, for fast lookup',
      'Without an index, every query would require scanning the whole web',
      'PageRank orders results by importance rather than just keyword relevance',
      'A page’s rank depends on the number of inbound links and the rank of the pages linking to it',
      'A link from a high-ranked page counts for more than one from a low-ranked page',
      'Final answer: Crawlers follow links to gather pages, which are stored in a keyword index so queries can be answered without rescanning the web. PageRank then orders those results by importance, judged by how many pages link to a page and how highly ranked those linking pages themselves are.',
    ],
    topic: 'Web Technologies',
  },
  {
    question: 'Explain the difference between HTML, CSS and JavaScript in the construction of a web page.',
    marks: 6,
    markScheme: [
      'HTML defines the structure and content - headings, paragraphs, forms, images',
      'CSS defines the presentation - colour, layout, typography, spacing',
      'Separating them means the same content can be restyled without editing the content',
      'JavaScript defines behaviour - it responds to events and can change the page dynamically',
      'Final answer: HTML provides structure and content, CSS controls presentation, and JavaScript adds interactive behaviour. Separating the three means a site can be restyled or made interactive without rewriting its content.',
    ],
    topic: 'Web Technologies',
  },
  {
    question: 'Explain what is meant by abstraction and give two examples of abstraction in computing.',
    marks: 6,
    markScheme: [
      'Abstraction is removing unnecessary detail to focus on what matters for the problem',
      'It reduces complexity and makes a problem tractable',
      'Example: the London Underground map removes real geography, keeping only connections and order of stops',
      'Example: a high-level programming language abstracts away registers and memory addresses',
      'Example: a class interface hides its implementation from code that uses it',
      'Final answer: Abstraction removes detail irrelevant to the problem so it can be reasoned about. The Tube map keeps station order and connections while discarding real distances; a high-level language hides registers and memory management from the programmer.',
    ],
    topic: 'Elements of Computational Thinking',
  },
  {
    question: 'Explain the difference between decomposition and abstraction, and why both are needed when designing a large program.',
    marks: 6,
    markScheme: [
      'Decomposition breaks a problem into smaller sub-problems that can be solved separately',
      'Each sub-problem becomes a module or function, which can be tested and reused independently',
      'Abstraction removes detail within each part, hiding implementation behind an interface',
      'Together: decomposition manages size, abstraction manages complexity',
      'Allows a team to work in parallel, since each only needs the interface of the others’ modules',
      'Final answer: Decomposition splits a large problem into independently solvable parts, while abstraction hides the detail inside each part behind an interface. Decomposition controls the size of the problem and abstraction controls its complexity - together they let a team work on separate modules in parallel.',
    ],
    topic: 'Elements of Computational Thinking',
  },
  {
    question: 'Explain what is meant by "thinking concurrently" and give one advantage and one disadvantage of concurrent processing.',
    marks: 6,
    markScheme: [
      'Thinking concurrently means identifying parts of a problem that can be carried out at the same time',
      'Requires spotting which steps are independent and which depend on earlier results',
      'Advantage: reduced overall execution time, and better use of multi-core processors',
      'Disadvantage: much harder to design and debug - race conditions and deadlock become possible',
      'Disadvantage: overhead of coordination may outweigh the gain for small tasks',
      'Not all problems parallelise - a strictly sequential dependency chain cannot be split',
      'Final answer: Thinking concurrently means identifying independent parts of a problem that can run simultaneously, cutting execution time on multi-core hardware. The cost is much greater design complexity, with race conditions and deadlock to guard against, and coordination overhead that can outweigh the benefit for small tasks.',
    ],
    topic: 'Elements of Computational Thinking',
  },
  {
    question: 'Explain what is meant by a heuristic, and why heuristics are used in problems such as route finding.',
    marks: 6,
    markScheme: [
      'A heuristic is a rule of thumb that produces a good-enough solution quickly',
      'It does not guarantee the optimal solution',
      'Used when an exhaustive search is computationally intractable - the search space is too large',
      'Example: in route finding, prefer expanding nodes that are geographically nearer the destination (A* search)',
      'Trade-off: accuracy is sacrificed for a solution in acceptable time',
      'Final answer: A heuristic is a rule of thumb giving a good-enough answer quickly without guaranteeing optimality. It is used where exhaustive search is intractable - a route finder cannot test every possible path, so it prioritises routes heading towards the destination.',
    ],
    topic: 'Computational Methods',
  },
  {
    question: 'Explain what is meant by problem recognition and problem decomposition when deciding whether a problem is solvable by computational methods.',
    marks: 6,
    markScheme: [
      'Problem recognition: identifying precisely what the problem is and what a solution would look like',
      'Requires determining the inputs, the required outputs and the constraints',
      'Some problems are not computable at all, or not within acceptable time',
      'Decomposition: breaking the recognised problem into sub-problems small enough to solve',
      'A problem is amenable to computational methods if it can be decomposed into well-defined, computable steps with clear inputs and outputs',
      'Final answer: Problem recognition establishes exactly what must be solved, including inputs, outputs and constraints; decomposition then breaks it into sub-problems. A problem suits computational methods when it can be reduced to well-defined, computable steps that run in acceptable time.',
    ],
    topic: 'Computational Methods',
  },
  {
    question: 'Explain what backtracking is and give an example of a problem where it would be used.',
    marks: 6,
    markScheme: [
      'Backtracking explores a solution path and abandons it as soon as it cannot lead to a valid solution',
      'It then returns to the last decision point and tries a different branch',
      'More efficient than brute force because whole subtrees are pruned without being explored',
      'Example: solving a Sudoku - place a digit, and if a later cell has no valid options, undo and try the next digit',
      'Example: maze solving, or the n-queens problem',
      'Final answer: Backtracking builds a solution incrementally and abandons a partial solution the moment it cannot succeed, returning to the previous decision point. Pruning those branches makes it far faster than brute force - it is how a Sudoku solver undoes a digit once a later cell has no valid options.',
    ],
    topic: 'Computational Methods',
  },
  {
    question: 'Explain the difference between the waterfall model and agile development, and give one situation where each is preferable.',
    marks: 8,
    markScheme: [
      'Waterfall: sequential phases (analysis, design, implementation, testing, maintenance), each completed before the next begins',
      'Documentation-heavy; changing requirements late is expensive',
      'Agile: iterative, delivering working software in short cycles with continuous customer feedback',
      'Requirements can evolve; less formal documentation',
      'Waterfall preferable where requirements are fixed and well understood, and where safety or legal certification demands full documentation - e.g. avionics software',
      'Agile preferable where requirements are unclear or expected to change - e.g. a consumer web product',
      'Final answer: Waterfall completes each phase before the next and suits projects with fixed, well-understood requirements needing full documentation, such as safety-critical avionics. Agile delivers working software iteratively with continuous feedback, suiting products whose requirements will change - though it produces less documentation.',
    ],
    topic: 'Software Development Methodologies',
  },
  {
    question: 'Explain the purpose of black box testing and white box testing, and why both are used.',
    marks: 6,
    markScheme: [
      'Black box testing: tests inputs against expected outputs without knowledge of the internal code',
      'Checks the program meets its specification; testers need not be programmers',
      'White box testing: designed with knowledge of the code, aiming to execute every path and branch',
      'Checks the internal logic, finding paths black box testing would miss',
      'Both are needed: black box can miss untested internal paths; white box can miss missing requirements entirely',
      'Final answer: Black box testing checks inputs against expected outputs to confirm the specification is met, while white box testing uses knowledge of the code to exercise every branch. Both are needed because black box testing misses untested internal paths and white box testing cannot reveal a requirement that was never implemented.',
    ],
    topic: 'Software Development Methodologies',
  },
  {
    question: 'Explain the difference between a compiler and an interpreter, and state one advantage of each.',
    marks: 6,
    markScheme: [
      'A compiler translates the entire source program into object code before execution',
      'An interpreter translates and executes one statement at a time, each time the program runs',
      'Compiler advantage: the compiled program runs faster, as translation happens once, and the source need not be distributed',
      'Interpreter advantage: easier debugging as errors are reported at the statement that caused them, and the same source runs on any machine with the interpreter',
      'A compiler reports all errors at the end of compilation; an interpreter stops at the first',
      'Final answer: A compiler translates the whole program in advance, producing faster-running object code without shipping the source; an interpreter translates line by line at run time, which is slower but makes debugging easier and lets the same source run anywhere the interpreter exists.',
    ],
    topic: 'Applications Generation (Translators)',
  },
  {
    question: 'Describe the role of the linker and the loader in producing an executable program.',
    marks: 6,
    markScheme: [
      'A large program is compiled as separate modules producing separate object files',
      'The linker combines these object files into a single executable',
      'It also incorporates code from library files that the program calls',
      'It resolves addresses so that calls between modules point to the correct locations',
      'The loader copies the executable from secondary storage into main memory ready to run',
      'The loader relocates addresses to match where the program is actually placed in memory',
      'Final answer: The linker combines separately compiled object files and library code into one executable, resolving cross-module addresses. The loader then copies that executable into main memory and adjusts addresses to reflect where it was actually loaded.',
    ],
    topic: 'Applications Generation (Translators)',
  },
  {
    question: 'Explain how paging and virtual memory allow a computer to run a program larger than its physical RAM.',
    marks: 8,
    markScheme: [
      'Memory is divided into fixed-size blocks called pages; physical memory into frames of the same size',
      'Only the pages currently needed are held in RAM; the rest reside on secondary storage',
      'A page table maps logical page numbers to physical frame addresses',
      'When a program accesses a page not in RAM, a page fault occurs',
      'The OS loads the required page from disk, evicting another page if memory is full',
      'This creates the illusion of more memory than physically exists (virtual memory)',
      'Excessive paging causes disk thrashing, where the CPU spends more time swapping than executing',
      'Final answer: Memory is split into fixed-size pages, only some of which are held in RAM while the rest sit on disk. A page table maps logical to physical addresses, and a page fault triggers loading the required page - giving the illusion of more memory than exists, at the cost of thrashing if paging becomes excessive.',
    ],
    topic: 'Systems Software',
  },
  {
    question: 'Explain the difference between round robin and shortest job first scheduling, and state one drawback of each.',
    marks: 6,
    markScheme: [
      'Round robin gives each process a fixed time slice in turn, pre-empting it when the slice expires',
      'Drawback: high context-switching overhead, and long jobs take much longer to complete',
      'Shortest job first runs the process with the shortest estimated burst time next',
      'Drawback: long processes may be starved indefinitely if short jobs keep arriving; also requires knowing burst times in advance',
      'Final answer: Round robin gives each process an equal time slice in rotation, which is fair but incurs heavy context-switching overhead; shortest job first minimises average waiting time but can starve long processes indefinitely and needs burst times known in advance.',
    ],
    topic: 'Systems Software',
  },
  {
    question: 'Explain the difference between symmetric and asymmetric encryption, and describe one situation where they are used together.',
    marks: 8,
    markScheme: [
      'Symmetric encryption uses the same key to encrypt and decrypt',
      'Fast and efficient for large volumes of data, but the key must be shared securely - the key distribution problem',
      'Asymmetric encryption uses a public key to encrypt and a mathematically related private key to decrypt',
      'Solves key distribution since the public key can be published, but it is computationally far slower',
      'Used together in HTTPS/TLS: asymmetric encryption securely exchanges a symmetric session key',
      'The rest of the session then uses fast symmetric encryption with that key',
      'Final answer: Symmetric encryption uses one shared key and is fast but requires secure key distribution; asymmetric uses a public/private key pair, solving distribution but far more slowly. HTTPS combines them - asymmetric encryption exchanges a symmetric session key, then the bulk of the traffic is encrypted symmetrically.',
    ],
    topic: 'Compression, Encryption and Hashing',
  },
  {
    question: 'Explain why a hashing algorithm is used to store passwords rather than storing them in plain text, and what a salt adds.',
    marks: 8,
    markScheme: [
      'A hash function is one-way: it is computationally infeasible to reverse the digest to recover the password',
      'The system stores the hash; on login it hashes the entered password and compares digests',
      'If the database is stolen, the attacker does not directly obtain the passwords',
      'Weakness: identical passwords produce identical hashes, and rainbow tables allow precomputed lookup',
      'A salt is a random value appended to the password before hashing, stored alongside the hash',
      'Salts make identical passwords hash differently and render precomputed rainbow tables useless',
      'The attacker must then brute force each password individually',
      'Final answer: Hashing is one-way, so a stolen database does not directly reveal passwords - the system compares digests instead. Adding a unique random salt before hashing means identical passwords produce different hashes, defeating rainbow tables and forcing an attacker to crack each account separately.',
    ],
    topic: 'Compression, Encryption and Hashing',
  },
  {
    question: 'Explain what normalisation is and why a database would be normalised to third normal form.',
    marks: 8,
    markScheme: [
      '1NF: no repeating groups; each field holds a single atomic value',
      '2NF: in 1NF and no partial dependencies - every non-key attribute depends on the whole primary key',
      '3NF: in 2NF and no transitive dependencies - no non-key attribute depends on another non-key attribute',
      'Benefit: removes data redundancy, so each fact is stored once',
      'Benefit: removes update, insertion and deletion anomalies',
      'Benefit: saves storage and keeps data consistent',
      'Drawback: more tables means more joins, which can slow complex queries',
      'Final answer: Normalisation restructures tables to remove repeating groups, partial dependencies and transitive dependencies. Reaching 3NF means each fact is stored exactly once, eliminating redundancy and update anomalies and keeping data consistent - at the cost of needing more joins when querying.',
    ],
    topic: 'Databases',
  },
  {
    question: 'Explain what is meant by the ACID properties of a database transaction.',
    marks: 8,
    markScheme: [
      'Atomicity: a transaction either completes fully or has no effect at all - partial updates are rolled back',
      'Consistency: a transaction takes the database from one valid state to another, preserving all rules and constraints',
      'Isolation: concurrent transactions do not interfere; the result is as if they ran sequentially',
      'Durability: once committed, changes survive a subsequent system failure, usually via a transaction log',
      'Example: a bank transfer must debit and credit together, or neither (atomicity)',
      'Final answer: Atomicity means all-or-nothing execution, consistency means constraints are preserved, isolation means concurrent transactions do not interfere, and durability means committed changes survive a crash. A bank transfer illustrates all four - the debit and credit must both happen or neither can.',
    ],
    topic: 'Databases',
  },
  {
    question: 'Explain the difference between the TCP/IP stack layers and describe the role of two of them.',
    marks: 8,
    markScheme: [
      'Four layers: Application, Transport, Internet (Network), Link (Data Link/Network Interface)',
      'Application layer: provides protocols the user’s software uses directly - HTTP, FTP, SMTP',
      'Transport layer: splits data into packets and establishes an end-to-end connection; TCP adds reliability with sequence numbers and acknowledgements',
      'Internet layer: adds source and destination IP addresses and handles routing between networks',
      'Link layer: handles physical transmission on the local network, adding MAC addresses',
      'Each layer adds a header as data passes down and strips it on the way up - encapsulation',
      'Layering means a change to one layer does not require changing the others',
      'Final answer: The stack has Application, Transport, Internet and Link layers. The Transport layer splits data into packets and, using TCP, guarantees reliable ordered delivery via sequence numbers and acknowledgements; the Internet layer adds IP addressing and routes packets between networks. Layering means each can change independently.',
    ],
    topic: 'Networks',
  },
  {
    question: 'Explain the purpose of DNS and describe what happens when a browser requests a domain name not held in its cache.',
    marks: 6,
    markScheme: [
      'DNS translates human-readable domain names into IP addresses',
      'Needed because routing uses IP addresses, but names are far easier for people to remember',
      'The browser checks its own cache, then the OS cache, then queries the local DNS resolver',
      'If the resolver does not know it, it queries a root nameserver, which directs it to the TLD server (e.g. .uk)',
      'The TLD server directs it to the authoritative nameserver for that domain, which returns the IP',
      'The result is cached at each level for a period set by its TTL',
      'Final answer: DNS maps domain names to the IP addresses routing actually uses. On a cache miss the resolver queries a root server, is directed to the relevant TLD server, and then to the domain’s authoritative nameserver, which returns the IP address - which is then cached for its TTL.',
    ],
    topic: 'Networks',
  },
  {
    question: 'Explain the difference between a stack and a queue, and give one use of each in a computer system.',
    marks: 6,
    markScheme: [
      'A stack is Last In First Out (LIFO): push and pop both act on the top',
      'A queue is First In First Out (FIFO): enqueue at the rear, dequeue from the front',
      'Stack use: the call stack storing return addresses and local variables during subroutine calls; also undo functionality and expression evaluation',
      'Queue use: a print spooler, keyboard buffer, or process scheduling ready queue',
      'Final answer: A stack is LIFO with all operations at the top, used for the call stack that stores return addresses during subroutine calls; a queue is FIFO with insertion at the rear and removal from the front, used for print spoolers and scheduling queues.',
    ],
    topic: 'Data Structures',
  },
  {
    question: 'Explain the advantages and disadvantages of a linked list compared with an array.',
    marks: 8,
    markScheme: [
      'A linked list stores nodes containing data plus a pointer to the next node; nodes need not be contiguous',
      'Advantage: dynamic size - it grows and shrinks at run time without reallocating',
      'Advantage: insertion and deletion are O(1) once the position is found, needing only pointer changes',
      'Disadvantage: no random access - finding the nth element requires traversal from the head, O(n)',
      'Disadvantage: extra memory for the pointers',
      'Array advantage: direct indexed access in O(1), and better cache performance from contiguous storage',
      'Final answer: A linked list grows dynamically and allows insertion or deletion by changing pointers rather than shifting elements, but it has no random access, so reaching the nth item takes O(n), and each node costs extra memory for its pointer. An array gives O(1) indexed access but a fixed size and costly insertions.',
    ],
    topic: 'Data Structures',
  },
  {
    question: 'Compare the time complexity of a linear search and a binary search, and state the precondition binary search requires.',
    marks: 6,
    markScheme: [
      'Linear search checks each element in turn: O(n) in the worst case',
      'Binary search repeatedly halves the search space: O(log n) in the worst case',
      'Binary search requires the data to be sorted beforehand',
      'For small or unsorted lists, linear search may be preferable since sorting costs at least O(n log n)',
      'Final answer: Linear search is O(n) and works on any list; binary search is O(log n) but requires the data to be sorted first. For a small or frequently changing unsorted list, linear search can be faster overall because sorting costs O(n log n).',
    ],
    topic: 'Algorithms: Searching, Sorting & Graph Traversal',
  },
  {
    question: 'Explain how Dijkstra’s algorithm finds the shortest path, and state one limitation.',
    marks: 8,
    markScheme: [
      'Assign a tentative distance of 0 to the start node and infinity to all others',
      'Visit the unvisited node with the smallest tentative distance',
      'For each neighbour, calculate the distance via the current node and update it if smaller',
      'Mark the current node visited; it will not be revisited',
      'Repeat until the destination is visited or all reachable nodes are done',
      'Limitation: it cannot handle negative edge weights, since a visited node is never reconsidered',
      'Limitation: it explores in all directions, so A* with a heuristic is faster for a known destination',
      'Final answer: Dijkstra’s repeatedly visits the nearest unvisited node, updating its neighbours’ tentative distances, until the destination is reached. It fails with negative edge weights because visited nodes are never revisited, and it searches in all directions - so A* with a distance heuristic is faster when the destination is known.',
    ],
    topic: 'Algorithms: Searching, Sorting & Graph Traversal',
  },
  {
    question: 'Explain the difference between procedural and object-oriented programming paradigms.',
    marks: 8,
    markScheme: [
      'Procedural: the program is a sequence of instructions organised into procedures/functions operating on separate data',
      'Data and the code acting on it are kept apart, so any procedure may modify any accessible data',
      'Object-oriented: data and the methods that operate on it are bundled together into objects, defined by classes',
      'Encapsulation hides internal state behind methods, so it can only be changed in controlled ways',
      'Inheritance allows a subclass to reuse and extend a superclass; polymorphism allows one interface to many implementations',
      'OOP scales better for large systems and promotes reuse; procedural is simpler for small, linear tasks',
      'Final answer: Procedural programming separates data from the procedures that act on it, while object-oriented programming bundles them into objects defined by classes. Encapsulation, inheritance and polymorphism make OOP better suited to large reusable systems, whereas procedural code is simpler for small linear tasks.',
    ],
    topic: 'Programming Paradigms',
  },
  {
    question: 'Explain what is meant by encapsulation and polymorphism, using an example of each.',
    marks: 6,
    markScheme: [
      'Encapsulation: bundling attributes and methods together and restricting direct access to the attributes',
      'Attributes are declared private and accessed through public getters and setters, so validation can be enforced',
      'Example: a BankAccount whose balance can only change through deposit() and withdraw()',
      'Polymorphism: the same method call behaving differently depending on the object’s actual class',
      'Example: a Shape superclass with area() overridden differently by Circle and Rectangle',
      'Final answer: Encapsulation hides an object’s attributes behind methods so they can only change in validated ways - a BankAccount balance changing only via deposit() and withdraw(). Polymorphism lets one method call behave differently per class, as when Circle and Rectangle each override area().',
    ],
    topic: 'Programming Paradigms',
  },
  {
    question: 'Explain the difference between an interrupt and a subroutine call, and describe how the processor handles an interrupt.',
    marks: 8,
    markScheme: [
      'A subroutine call is initiated by the program itself at a predetermined point',
      'An interrupt is triggered by hardware or software externally, at an unpredictable time',
      'On receiving an interrupt, the processor completes the current instruction (not the whole cycle mid-instruction)',
      'It checks the interrupt priority against the current task; lower-priority interrupts are queued',
      'It saves the contents of registers and the program counter onto the stack',
      'It loads the address of the appropriate interrupt service routine into the PC and executes it',
      'Afterwards it restores the saved register contents from the stack and resumes',
      'Final answer: A subroutine call is made by the program at a known point, whereas an interrupt arrives unpredictably from hardware or software. The processor finishes the current instruction, checks priority, pushes the registers and program counter onto the stack, runs the interrupt service routine, then restores state and resumes.',
    ],
    topic: 'Structure and Function of the Processor',
  },
  {
    question: 'Explain how pipelining improves processor performance and state one situation where it can stall.',
    marks: 6,
    markScheme: [
      'Pipelining overlaps the fetch, decode and execute stages of successive instructions',
      'While one instruction is executing, the next is decoded and a third is fetched',
      'This increases instruction throughput without increasing clock speed',
      'It stalls on a conditional branch: the instructions already fetched may be the wrong ones and must be flushed',
      'Also stalls on a data dependency, where an instruction needs the result of one still executing',
      'Branch prediction is used to reduce the cost of branching',
      'Final answer: Pipelining overlaps the fetch, decode and execute stages of consecutive instructions, raising throughput without a faster clock. It stalls on conditional branches, where prefetched instructions must be discarded, and on data dependencies - which is why processors use branch prediction.',
    ],
    topic: 'Structure and Function of the Processor',
  },
  {
    question: 'Explain two ways in which computing technology raises ethical concerns, referring to relevant legislation.',
    marks: 8,
    markScheme: [
      'Privacy and data collection: organisations gather large volumes of personal data, often without meaningful consent',
      'The Data Protection Act 2018 / UK GDPR requires data to be processed lawfully, kept accurate, held only as long as necessary and kept secure',
      'Automated decision making: algorithms may reproduce bias present in training data, e.g. in recruitment or lending',
      'Raises accountability questions - who is responsible when an automated system causes harm',
      'Computer Misuse Act 1990 covers unauthorised access, unauthorised access with intent, and unauthorised modification',
      'Other valid: environmental cost of hardware and data centres, automation and employment, digital divide',
      'Final answer: Mass collection of personal data raises privacy concerns, regulated by the Data Protection Act 2018 which requires lawful, secure and time-limited processing. Automated decision making raises fairness and accountability concerns because algorithms can reproduce bias in their training data - and unauthorised access to systems is separately criminalised by the Computer Misuse Act 1990.',
    ],
    topic: 'Legal, Moral, Cultural and Ethical Issues',
  },
]

export const CS_MCQ_3 = [
  {
    question: 'Which register holds the address of the next instruction to be executed?',
    options: ['Program Counter', 'Accumulator', 'Memory Data Register', 'Current Instruction Register'],
    answer: 0,
    explanation: 'The PC holds the address of the next instruction; the CIR holds the instruction currently being decoded.',
    topic: 'Structure and Function of the Processor',
  },
  {
    question: 'What is the effect of increasing the width of the address bus by one bit?',
    options: [
      'The addressable memory doubles',
      'The addressable memory increases by one byte',
      'Data transfer speed doubles',
      'The word size doubles',
    ],
    answer: 0,
    explanation: 'n address lines address 2ⁿ locations, so each extra line doubles the addressable memory.',
    topic: 'Structure and Function of the Processor',
  },
  {
    question: 'In Von Neumann architecture, what is shared that is separate in Harvard architecture?',
    options: [
      'Memory holding both instructions and data',
      'The control unit',
      'The ALU',
      'The program counter',
    ],
    answer: 0,
    explanation: 'Von Neumann stores instructions and data in the same memory; Harvard uses physically separate memories and buses.',
    topic: 'Structure and Function of the Processor',
  },
  {
    question: 'Which type of processor architecture has a small set of simple, fixed-length instructions?',
    options: ['RISC', 'CISC', 'Von Neumann', 'Harvard'],
    answer: 0,
    explanation: 'RISC uses few simple instructions that mostly execute in one cycle, making pipelining easier; CISC has many complex variable-length instructions.',
    topic: 'Types of Processor',
  },
  {
    question: 'What is the main advantage of a GPU over a CPU for tasks like image processing?',
    options: [
      'Many cores performing the same operation on lots of data in parallel',
      'A much higher clock speed',
      'Larger cache memory',
      'It uses less power per core',
    ],
    answer: 0,
    explanation: 'GPUs have thousands of simple cores suited to SIMD workloads, where the same operation is applied across large data sets.',
    topic: 'Types of Processor',
  },
  {
    question: 'Which storage type has no moving parts and uses NAND flash memory?',
    options: ['Solid state drive', 'Hard disk drive', 'Optical disc', 'Magnetic tape'],
    answer: 0,
    explanation: 'SSDs use NAND flash, giving faster access, silent operation and better shock resistance, but a finite number of write cycles.',
    topic: 'Input, Output and Storage',
  },
  {
    question: 'What does RAM being described as "volatile" mean?',
    options: [
      'Its contents are lost when power is removed',
      'Its contents change unpredictably',
      'It can only be read, not written',
      'It is slower than secondary storage',
    ],
    answer: 0,
    explanation: 'Volatile means it needs a constant power supply to retain data - which is why programs must be loaded from non-volatile secondary storage.',
    topic: 'Input, Output and Storage',
  },
  {
    question: 'What is the purpose of the operating system kernel?',
    options: [
      'To manage memory, processes and hardware access',
      'To provide the graphical user interface',
      'To compile source code',
      'To defragment the hard disk',
    ],
    answer: 0,
    explanation: 'The kernel is the core of the OS, handling memory management, scheduling and hardware access via device drivers.',
    topic: 'Systems Software',
  },
  {
    question: 'What is disk thrashing?',
    options: [
      'Excessive paging leaving little time for actual execution',
      'Physical damage to the disk platters',
      'Fragmentation of files across the disk',
      'A failed disk read requiring a retry',
    ],
    answer: 0,
    explanation: 'When too little RAM is available the OS spends most of its time swapping pages in and out rather than executing instructions.',
    topic: 'Systems Software',
  },
  {
    question: 'A lexical analyser in a compiler is responsible for:',
    options: [
      'Converting source code into tokens and building the symbol table',
      'Checking that statements follow the grammar rules',
      'Producing the final machine code',
      'Removing redundant instructions',
    ],
    answer: 0,
    explanation: 'Lexical analysis strips whitespace and comments, converts keywords and identifiers into tokens, and begins the symbol table. Grammar checking is syntax analysis.',
    topic: 'Applications Generation (Translators)',
  },
  {
    question: 'Which stage of compilation reports a missing closing bracket?',
    options: ['Syntax analysis', 'Lexical analysis', 'Code generation', 'Optimisation'],
    answer: 0,
    explanation: 'Syntax analysis checks tokens against the language grammar, so structural errors like unmatched brackets are found there.',
    topic: 'Applications Generation (Translators)',
  },
  {
    question: 'In the waterfall model, what is the main disadvantage?',
    options: [
      'Changing requirements late in the project is very expensive',
      'It produces too little documentation',
      'The customer is involved too often',
      'It cannot be used for large projects',
    ],
    answer: 0,
    explanation: 'Because each phase completes before the next begins, a requirement discovered during testing means revisiting earlier phases at high cost.',
    topic: 'Software Development Methodologies',
  },
  {
    question: 'What is the purpose of α and β testing?',
    options: [
      'Alpha is in-house testing; β is by real users outside the organisation',
      'Alpha tests the code; β tests the documentation',
      'Alpha is automated; β is manual',
      'Alpha is before coding; β is after release',
    ],
    answer: 0,
    explanation: 'Alpha testing happens internally by the development organisation; β releases the software to real users who report bugs in real conditions.',
    topic: 'Software Development Methodologies',
  },
  {
    question: 'Which compression method discards data that cannot be recovered?',
    options: ['Lossy', 'Lossless', 'Run length encoding', 'Dictionary encoding'],
    answer: 0,
    explanation: 'Lossy compression permanently removes data (e.g. JPEG, MP3); RLE and dictionary encoding are both lossless.',
    topic: 'Compression, Encryption and Hashing',
  },
  {
    question: 'A good hashing algorithm for a hash table should:',
    options: [
      'Distribute keys evenly to minimise collisions',
      'Always produce the same output length as the input',
      'Be reversible',
      'Produce the same hash for similar keys',
    ],
    answer: 0,
    explanation: 'Even distribution minimises collisions and keeps lookup close to O(1). Reversibility would defeat the purpose in security contexts.',
    topic: 'Compression, Encryption and Hashing',
  },
  {
    question: 'A table is in 2NF but has a non-key attribute that depends on another non-key attribute. This is:',
    options: [
      'A transitive dependency, breaking 3NF',
      'A partial dependency, breaking 2NF',
      'A repeating group, breaking 1NF',
      'Perfectly normalised',
    ],
    answer: 0,
    explanation: 'A non-key attribute depending on another non-key attribute is a transitive dependency, which 3NF removes.',
    topic: 'Databases',
  },
  {
    question: 'What does referential integrity ensure?',
    options: [
      'A foreign key always refers to an existing primary key',
      'No two records have the same primary key',
      'All fields contain data of the correct type',
      'Transactions complete fully or not at all',
    ],
    answer: 0,
    explanation: 'Referential integrity prevents orphaned records by ensuring every foreign key value matches an existing primary key.',
    topic: 'Databases',
  },
  {
    question: 'Which protocol guarantees reliable, ordered delivery of packets?',
    options: ['TCP', 'UDP', 'IP', 'HTTP'],
    answer: 0,
    explanation: 'TCP uses sequence numbers and acknowledgements to guarantee ordered delivery; UDP is faster but offers no such guarantee.',
    topic: 'Networks',
  },
  {
    question: 'What is the main advantage of packet switching over circuit switching?',
    options: [
      'The network is used efficiently and can route around failures',
      'Packets always arrive in order',
      'It guarantees a constant transfer rate',
      'It requires no addressing',
    ],
    answer: 0,
    explanation: 'Packets share the network and can take different routes, so bandwidth is used efficiently and a failed link can be bypassed.',
    topic: 'Networks',
  },
  {
    question: 'What is the purpose of a firewall using packet filtering?',
    options: [
      'To inspect packet headers and block those failing the rules',
      'To encrypt all outgoing traffic',
      'To translate domain names into IP addresses',
      'To compress data before transmission',
    ],
    answer: 0,
    explanation: 'Packet filtering examines source and destination addresses and port numbers against a rule set, dropping packets that do not comply.',
    topic: 'Networks',
  },
  {
    question: 'Why is client-side validation alone insufficient for security?',
    options: [
      'The user can disable or bypass it, so it must be repeated server-side',
      'It is too slow to run in the browser',
      'It cannot check the format of an email address',
      'It only works on modern browsers',
    ],
    answer: 0,
    explanation: 'Anything running in the user’s browser is under the user’s control and can be bypassed, so security-critical checks must be repeated on the server.',
    topic: 'Web Technologies',
  },
  {
    question: 'In CSS, which selector has the highest specificity?',
    options: ['An id selector (#header)', 'A class selector (.nav)', 'An element selector (p)', 'The universal selector (*)'],
    answer: 0,
    explanation: 'Specificity increases from universal, to element, to class, to id - so an id selector overrides the others.',
    topic: 'Web Technologies',
  },
  {
    question: 'What is the denary value of the two’s complement 8-bit number 11110000?',
    options: ['-16', '240', '-112', '-15'],
    answer: 0,
    explanation: 'The leading 1 means negative. Invert to 00001111 and add 1 to get 00010000 = 16, so the value is -16.',
    topic: 'Data Types and Number Representation',
  },
  {
    question: 'Which is a benefit of floating point over fixed point representation?',
    options: [
      'A much wider range of values for the same number of bits',
      'Greater precision for every value',
      'Faster arithmetic operations',
      'No rounding errors',
    ],
    answer: 0,
    explanation: 'Floating point trades precision for range - the exponent allows very large and very small magnitudes, but fixed point is more precise within its narrower range.',
    topic: 'Data Types and Number Representation',
  },
  {
    question: 'Which traversal of a binary search tree outputs the values in ascending order?',
    options: ['In-order', 'Pre-order', 'Post-order', 'Breadth-first'],
    answer: 0,
    explanation: 'In-order (left, root, right) visits a BST in sorted order. Post-order is used to delete a tree; pre-order to copy one.',
    topic: 'Data Structures',
  },
  {
    question: 'In a circular queue, what problem does wrapping the rear pointer solve?',
    options: [
      'Wasted space left at the front after items are dequeued',
      'Items being dequeued in the wrong order',
      'The queue growing beyond memory',
      'Two items having the same priority',
    ],
    answer: 0,
    explanation: 'In a linear queue the space vacated at the front cannot be reused; a circular queue wraps the pointers around to reclaim it.',
    topic: 'Data Structures',
  },
  {
    question: 'Simplify A.(A + B) using Boolean algebra.',
    options: ['A', 'A + B', 'A.B', 'B'],
    answer: 0,
    explanation: 'This is the absorption law: A.(A + B) = A. If A is false the whole expression is false; if A is true it is true.',
    topic: 'Boolean Algebra',
  },
  {
    question: 'According to De Morgan’s laws, NOT(A AND B) is equivalent to:',
    options: ['NOT A OR NOT B', 'NOT A AND NOT B', 'A OR B', 'NOT(A OR B)'],
    answer: 0,
    explanation: 'Break the bar and change the sign: the negation of a conjunction is the disjunction of the negations.',
    topic: 'Boolean Algebra',
  },
  {
    question: 'Which logic gate outputs 1 only when its two inputs differ?',
    options: ['XOR', 'AND', 'OR', 'NAND'],
    answer: 0,
    explanation: 'XOR (exclusive OR) outputs 1 for inputs 01 and 10, and 0 for 00 and 11 - which is why it is used in half adders.',
    topic: 'Boolean Algebra',
  },
  {
    question: 'What is the worst-case time complexity of bubble sort?',
    options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'],
    answer: 0,
    explanation: 'Bubble sort makes n passes each comparing up to n elements, giving O(n²) - which is why it is only used for teaching or tiny data sets.',
    topic: 'Algorithms: Searching, Sorting & Graph Traversal',
  },
  {
    question: 'Merge sort is an example of which algorithmic strategy?',
    options: ['Divide and conquer', 'Greedy', 'Backtracking', 'Dynamic programming'],
    answer: 0,
    explanation: 'Merge sort recursively splits the list until single elements remain, then merges the sorted halves - the classic divide-and-conquer pattern.',
    topic: 'Algorithms: Searching, Sorting & Graph Traversal',
  },
  {
    question: 'Which data structure does a breadth-first traversal use?',
    options: ['A queue', 'A stack', 'A binary tree', 'A hash table'],
    answer: 0,
    explanation: 'BFS uses a queue to visit nodes level by level. Depth-first uses a stack (or recursion, which uses the call stack).',
    topic: 'Algorithms: Searching, Sorting & Graph Traversal',
  },
  {
    question: 'Which is the best example of abstraction?',
    options: [
      'A Tube map showing connections but not real distances',
      'Splitting a program into functions',
      'Testing each module separately',
      'Running two tasks at the same time',
    ],
    answer: 0,
    explanation: 'The Tube map removes detail (geography, scale) irrelevant to the task of finding a route - the definition of abstraction. Splitting into functions is decomposition.',
    topic: 'Elements of Computational Thinking',
  },
  {
    question: 'A problem where the same subproblem is solved repeatedly is best addressed by:',
    options: [
      'Caching results (memoisation)',
      'Brute force search',
      'Adding more comments',
      'Increasing the recursion depth',
    ],
    answer: 0,
    explanation: 'Storing the result of each subproblem the first time avoids recomputing it - the basis of dynamic programming.',
    topic: 'Computational Methods',
  },
  {
    question: 'What does "performance modelling" mean in the context of computational methods?',
    options: [
      'Using mathematical models to predict system behaviour instead of testing it directly',
      'Measuring how fast a program runs',
      'Optimising code to run faster',
      'Comparing two sorting algorithms',
    ],
    answer: 0,
    explanation: 'Performance modelling simulates a system mathematically where real testing would be too expensive, dangerous or slow.',
    topic: 'Computational Methods',
  },
  {
    question: 'What does it mean for a subroutine to be recursive?',
    options: [
      'It calls itself, with a base case to stop',
      'It calls another subroutine',
      'It runs in a loop',
      'It returns more than one value',
    ],
    answer: 0,
    explanation: 'A recursive subroutine calls itself on a smaller input, and must have a base case or it will exhaust the call stack.',
    topic: 'Programming Techniques',
  },
  {
    question: 'What is the difference between passing a parameter by value and by reference?',
    options: [
      'By value passes a copy; by reference passes the memory address',
      'By value is faster for large objects',
      'By reference creates a new variable',
      'There is no difference',
    ],
    answer: 0,
    explanation: 'By value copies the data so the original is unchanged; by reference passes the address, so changes inside the subroutine affect the original.',
    topic: 'Programming Techniques',
  },
  {
    question: 'Which best describes the scope of a local variable?',
    options: [
      'It exists only within the subroutine that declares it',
      'It exists throughout the whole program',
      'It exists until the program is recompiled',
      'It can be accessed by any subroutine that knows its name',
    ],
    answer: 0,
    explanation: 'A local variable is created when the subroutine is called and destroyed when it returns, which prevents unintended interference between subroutines.',
    topic: 'Programming Techniques',
  },
  {
    question: 'In OOP, what does inheritance allow?',
    options: [
      'A subclass to reuse and extend the attributes and methods of a superclass',
      'Two objects to share the same memory',
      'A method to have several different implementations',
      'Attributes to be hidden from outside the class',
    ],
    answer: 0,
    explanation: 'Inheritance lets a subclass reuse a superclass and add to it. Hiding attributes is encapsulation; several implementations is polymorphism.',
    topic: 'Programming Paradigms',
  },
  {
    question: 'Which UK law makes unauthorised access to computer material a criminal offence?',
    options: [
      'Computer Misuse Act 1990',
      'Data Protection Act 2018',
      'Copyright, Designs and Patents Act 1988',
      'Regulation of Investigatory Powers Act 2000',
    ],
    answer: 0,
    explanation: 'The Computer Misuse Act 1990 covers unauthorised access, access with intent to commit further offences, and unauthorised modification.',
    topic: 'Legal, Moral, Cultural and Ethical Issues',
  },
  {
    question: 'Under the Data Protection Act 2018, personal data must be:',
    options: [
      'Kept no longer than necessary for its stated purpose',
      'Kept indefinitely for auditing',
      'Shared with any organisation that requests it',
      'Stored only on paper',
    ],
    answer: 0,
    explanation: 'Storage limitation is one of the core principles: data must be kept only as long as needed for the purpose it was collected for.',
    topic: 'Legal, Moral, Cultural and Ethical Issues',
  },
]
