/*
  Extra Edexcel A-level Economics A exam questions - Themes 1 and 2.

  The pack shipped with about 2.4 exam questions per chapter, the thinnest
  content of the three subjects, and Economics is the one assessed almost
  entirely through written answers. Two more per chapter roughly doubles it.

  Mark schemes follow the existing convention: the marking points first,
  then a "Final answer:" line so a student self-marking has something to
  compare their whole answer against rather than only a list of fragments.

  Mark tariffs use the real command words - 4 marks for explain, 8-12 for
  the analyse/evaluate questions that carry the paper.
*/
export const ECON_EXAM_2 = [
  // ================================================== THEME 1 · 1.1-1.2
  {
    question: 'Explain the difference between positive and normative economic statements, using an example of each.',
    marks: 4,
    markScheme: [
      'A positive statement is objective and can be tested against evidence as true or false',
      'e.g. "a rise in the minimum wage increases unemployment among 18-24 year olds"',
      'A normative statement is subjective, contains a value judgement, and cannot be tested',
      'e.g. "the government ought to raise the minimum wage"',
      'Final answer: Positive statements are factual claims that evidence can settle (e.g. raising the minimum wage raises youth unemployment); normative statements contain value judgements about what should happen (e.g. the minimum wage ought to rise) and so cannot be proved or disproved.',
    ],
    topic: 'Economic Methodology and the Economic Problem',
  },
  {
    question: 'Explain why the concept of opportunity cost is relevant to governments as well as to individual consumers.',
    marks: 4,
    markScheme: [
      'Opportunity cost is the value of the next best alternative forgone',
      'Government budgets are finite, so spending on one area means forgoing another',
      'e.g. money spent on a new hospital cannot also be spent on schools or defence',
      'Applies to consumers identically: limited income forces a choice between goods',
      'Final answer: Because resources are scarce for every economic agent. A government choosing to spend £1bn on healthcare gives up the next best use of that £1bn, such as education - exactly as a consumer choosing one good gives up the next best alternative.',
    ],
    topic: 'Economic Methodology and the Economic Problem',
  },
  {
    question: 'Analyse, using a PPF diagram, the effect of a significant improvement in a country’s education system on its production possibility frontier.',
    marks: 8,
    markScheme: [
      'Diagram: PPF shifting outwards (to the right) from the origin',
      'Better education raises the quality of human capital, so labour becomes more productive',
      'This raises the productive potential of the economy - more of both goods can be produced',
      'This is economic growth in the long run (an increase in productive capacity), not just a movement to a point closer to the frontier',
      'The shift may be non-parallel if education benefits one sector more, e.g. capital goods requiring skilled labour',
      'Time lag: the effect appears only when educated cohorts enter the workforce',
      'Final answer: Improved education raises human capital and therefore productivity, shifting the PPF outwards and increasing the economy’s productive potential. The shift may be uneven between sectors and occurs with a significant time lag.',
    ],
    topic: 'Production Possibility Frontiers',
  },
  {
    question: 'Explain the difference between a movement along a PPF and a shift of the PPF.',
    marks: 4,
    markScheme: [
      'A movement along the PPF is a reallocation of existing resources between two goods',
      'It involves an opportunity cost: more of one good means less of the other',
      'A shift of the PPF is a change in the economy’s total productive capacity',
      'Caused by more or better resources: investment, net immigration, technology, education',
      'Final answer: Moving along the PPF reallocates the same resources, so gaining one good costs another; shifting the PPF changes how much the economy can produce in total, caused by a change in the quantity or quality of factors of production.',
    ],
    topic: 'Production Possibility Frontiers',
  },
  {
    question: 'Evaluate the view that a mixed economy allocates resources more effectively than a free market economy.',
    marks: 12,
    markScheme: [
      'Free markets use the price mechanism: signalling, incentives and rationing allocate resources without central direction',
      'Advantages: efficiency incentives, consumer sovereignty, innovation driven by the profit motive',
      'However free markets fail: public goods are not provided, externalities are ignored, merit goods under-consumed, monopoly power emerges, inequality can be extreme',
      'A mixed economy retains market incentives while government corrects these failures through taxation, regulation and direct provision',
      'Evaluation: government intervention itself can fail - information gaps, administrative cost, unintended consequences, regulatory capture',
      'Evaluation: depends on the quality of institutions and the degree of intervention; the optimal mix differs by market',
      'Final answer: A mixed economy is generally more effective because it keeps the efficiency incentives of the market while correcting market failure, but this depends on the government intervening competently - poorly designed intervention can produce government failure that leaves welfare lower than the free market outcome.',
    ],
    topic: 'Economic Systems',
  },
  {
    question: 'Explain two limitations of a command economy as a way of allocating resources.',
    marks: 4,
    markScheme: [
      'Information problem: central planners cannot gather and process the information the price mechanism conveys automatically',
      'This leads to persistent surpluses and shortages as plans do not match actual preferences',
      'Weak incentives: without profit or competition there is little reason to cut costs or innovate',
      'Result is productive and dynamic inefficiency, and limited consumer choice',
      'Final answer: Planners lack the information the price mechanism generates, causing shortages and surpluses; and the absence of the profit motive removes the incentive to cut costs or innovate, causing productive and dynamic inefficiency.',
    ],
    topic: 'Economic Systems',
  },
  {
    question: 'Explain, using an example, how the assumption of rational decision making may not hold in reality.',
    marks: 4,
    markScheme: [
      'Traditional theory assumes consumers maximise utility and firms maximise profit using full information',
      'In reality: habitual behaviour, e.g. buying the same brand without comparing prices',
      'Bounded rationality: limited time and information means people satisfice rather than optimise',
      'Influence of social norms and immediate gratification, e.g. undersaving for a pension',
      'Final answer: Consumers are often not fully rational - for example someone repeatedly buys the same brand out of habit rather than comparing prices, because limited time and information mean they satisfice rather than maximise utility.',
    ],
    topic: 'Rational Decision Making',
  },
  {
    question: 'Analyse how behavioural economics can be used by governments to influence consumer choice.',
    marks: 8,
    markScheme: [
      'Behavioural economics recognises consumers are not fully rational: they use heuristics and are influenced by framing',
      'Choice architecture: changing how options are presented without removing any option',
      'Default options exploit inertia, e.g. auto-enrolment into workplace pensions raised participation sharply',
      'Framing and salience: displaying calorie counts or traffic-light labelling on food',
      'Social norms: telling taxpayers that most people in their area have already paid raises compliance',
      'Advantage over taxation or bans: cheap, preserves freedom of choice ("nudge" not "shove")',
      'Evaluation: effects can be small or fade over time, and there are ethical concerns about manipulation',
      'Final answer: Governments use choice architecture - defaults, framing and social norms - to steer decisions without removing options, as with pension auto-enrolment. It is cheap and preserves freedom of choice, but the effects can be modest and raise ethical questions about manipulating decisions.',
    ],
    topic: 'Rational Decision Making',
  },
  {
    question: 'Analyse two factors, other than price, that would cause the demand curve for a good to shift to the right.',
    marks: 8,
    markScheme: [
      'Rise in real incomes: for a normal good, higher purchasing power raises demand at every price',
      'Diagram: demand curve shifts right, raising equilibrium price and quantity',
      'Rise in the price of a substitute: consumers switch to this good, raising its demand',
      'e.g. a rise in the price of coffee raises demand for tea',
      'Other valid factors: successful advertising, population growth, favourable tastes, expectations of future price rises',
      'Chain of reasoning must run from cause to a shift, not a movement along',
      'Final answer: A rise in real income raises demand for a normal good at every price level, and a rise in the price of a substitute causes consumers to switch into this good - both shifting demand right and raising equilibrium price and quantity.',
    ],
    topic: 'Demand',
  },
  {
    question: 'Explain the difference between a shift in demand and a movement along the demand curve.',
    marks: 4,
    markScheme: [
      'A movement along the curve (extension or contraction) is caused only by a change in the price of the good itself',
      'A shift of the whole curve is caused by any other determinant of demand',
      'Conditions of demand: income, prices of substitutes and complements, tastes, population, expectations',
      'Confusing the two is the most common error in this topic',
      'Final answer: Only a change in the good’s own price moves you along the demand curve; a change in any other determinant - income, related goods’ prices, tastes, population - shifts the entire curve.',
    ],
    topic: 'Demand',
  },
  {
    question: 'A firm cuts its price by 10% and total revenue falls by 4%. Calculate the price elasticity of demand and explain what this means for the firm’s pricing strategy.',
    marks: 6,
    markScheme: [
      'Revenue falling when price falls means demand is price inelastic',
      'Quantity demanded must have risen by roughly 6.7% (since revenue change ≈ %ΔP + %ΔQ)',
      'PED = %ΔQd / %ΔP = +6.7 / -10 = -0.67 (inelastic, |PED| < 1)',
      'For an inelastic good, cutting price reduces total revenue - the firm should raise price instead',
      'Raising price would increase revenue because quantity falls proportionately less than price rises',
      'Final answer: PED ≈ -0.67, so demand is price inelastic. Cutting price was the wrong strategy - the firm should raise price, since quantity demanded falls proportionately less than the price rise, increasing total revenue.',
    ],
    topic: 'Price, Income and Cross Elasticities of Demand',
  },
  {
    question: 'Explain what the sign and size of cross elasticity of demand (XED) tell you about the relationship between two goods.',
    marks: 4,
    markScheme: [
      'XED = %ΔQd of good A / %ΔP of good B',
      'Positive XED means the goods are substitutes: a rise in B’s price raises demand for A',
      'Negative XED means the goods are complements: a rise in B’s price lowers demand for A',
      'The larger the absolute value, the stronger the relationship; XED near zero means unrelated goods',
      'Final answer: The sign shows the type of relationship - positive for substitutes, negative for complements - and the magnitude shows its strength, with values near zero indicating the goods are unrelated.',
    ],
    topic: 'Price, Income and Cross Elasticities of Demand',
  },
  {
    question: 'Analyse the factors that determine the price elasticity of supply of a good.',
    marks: 8,
    markScheme: [
      'Time period: supply is more elastic in the long run when all factors are variable',
      'In the very short run supply may be perfectly inelastic (fixed stock)',
      'Availability of spare capacity: firms with idle plant can expand output quickly, raising PES',
      'Ease of storing stock: storable goods allow a quick supply response',
      'Factor mobility: if labour and capital can be switched into this industry easily, PES is higher',
      'Barriers to entry: low barriers allow new firms to respond to price rises',
      'Final answer: PES rises with the time available, spare capacity, the ability to hold stocks, and the mobility of factors of production; agricultural goods with long growing seasons are highly inelastic in the short run, while manufactured goods with idle capacity are elastic.',
    ],
    topic: 'Supply and Elasticity of Supply',
  },
  {
    question: 'Explain two factors that would cause the supply curve for wheat to shift to the left.',
    marks: 4,
    markScheme: [
      'A rise in costs of production, e.g. higher fertiliser or fuel prices, makes supply less profitable at every price',
      'Adverse weather or crop disease reduces yields, cutting the quantity supplied at every price',
      'Other valid: removal of a subsidy, an indirect tax, firms leaving the industry',
      'Both shift the supply curve left, raising equilibrium price and lowering equilibrium quantity',
      'Final answer: Higher input costs such as fertiliser, and a poor harvest caused by adverse weather, both reduce the quantity supplied at every price - shifting supply left, raising price and reducing quantity traded.',
    ],
    topic: 'Supply and Elasticity of Supply',
  },
  {
    question: 'Explain the three functions of the price mechanism in a market economy.',
    marks: 6,
    markScheme: [
      'Signalling: prices convey information about relative scarcity to buyers and sellers',
      'A rising price signals shortage; a falling price signals surplus',
      'Incentive: a higher price rewards producers for supplying more, and encourages consumers to economise',
      'Rationing: when supply is scarce, a rising price allocates the good to those willing and able to pay most',
      'Together these coordinate millions of decisions without central direction',
      'Final answer: Prices signal relative scarcity, incentivise producers to supply more and consumers to use less, and ration scarce goods to those willing to pay - coordinating resource allocation without any central planner.',
    ],
    topic: 'Price Determination and the Price Mechanism',
  },
  {
    question: 'Analyse, using a diagram, the effect on the market for new-build housing of a fall in mortgage interest rates.',
    marks: 8,
    markScheme: [
      'Lower interest rates reduce the cost of borrowing, so mortgages become more affordable',
      'This raises effective demand for housing: the demand curve shifts right',
      'Diagram: D1 to D2, equilibrium price rises P1 to P2 and quantity rises Q1 to Q2',
      'Supply of new housing is price inelastic in the short run (planning delays, build time)',
      'Therefore most of the adjustment falls on price rather than quantity',
      'Final answer: Cheaper borrowing shifts housing demand right; because the supply of new housing is highly price inelastic in the short run, the increase shows up mainly as a rise in price rather than in the number of houses built.',
    ],
    topic: 'Price Determination and the Price Mechanism',
  },
  {
    question: 'Explain, using examples, the difference between complete market failure and partial market failure.',
    marks: 4,
    markScheme: [
      'Complete market failure: a missing market - the free market provides none of the good',
      'e.g. pure public goods such as national defence or street lighting, due to the free rider problem',
      'Partial market failure: the market exists but provides the wrong quantity',
      'e.g. healthcare or education are provided, but under-consumed relative to the social optimum',
      'Final answer: Complete failure means the market does not exist at all, as with public goods like national defence; partial failure means the market operates but at the wrong quantity, as with the under-consumption of merit goods like education.',
    ],
    topic: 'Types of Market Failure',
  },
  {
    question: 'Analyse how the immobility of labour can cause market failure.',
    marks: 8,
    markScheme: [
      'Geographical immobility: workers cannot move to where jobs are, due to housing costs, family ties, or regional house price differences',
      'Occupational immobility: workers lack the skills to move between industries, e.g. former miners cannot become software engineers',
      'Result: structural unemployment persists alongside unfilled vacancies elsewhere',
      'This is a misallocation of resources - labour is not being used at its most productive',
      'Society operates inside its PPF, so output is below potential',
      'Justifies intervention: retraining subsidies, housing policy, improved information',
      'Final answer: When labour cannot move geographically or occupationally, unemployment coexists with unfilled vacancies. Labour is not allocated to its most productive use, so the economy produces inside its PPF - a misallocation of resources that justifies government retraining and housing policy.',
    ],
    topic: 'Types of Market Failure',
  },
  {
    question: 'Analyse, using a diagram, the welfare loss arising from a negative externality of production.',
    marks: 8,
    markScheme: [
      'Diagram: MPC below MSC, with MSB = MPB; free market equilibrium at MPC = MPB',
      'Marginal external cost is the vertical gap between MPC and MSC',
      'Free market output Q1 exceeds the social optimum Q*, where MSC = MSB',
      'Between Q* and Q1 the social cost of each unit exceeds the social benefit',
      'The welfare loss (deadweight loss) is the triangle between MSC and MSB over that range',
      'Example: a factory emitting pollution imposes health costs on third parties it does not pay',
      'Final answer: Because firms consider only private costs, output settles where MPC = MPB, above the social optimum where MSC = MSB. Every unit beyond the optimum costs society more than it benefits it, and the resulting welfare loss is the triangle between the MSC and MSB curves.',
    ],
    topic: 'Externalities',
  },
  {
    question: 'Explain why a positive consumption externality leads to under-consumption in a free market.',
    marks: 4,
    markScheme: [
      'A positive consumption externality means MSB > MPB - third parties gain from the consumption',
      'Consumers base their decision only on their own private benefit',
      'So the market settles where MPB = MPC, at a quantity below the social optimum where MSB = MSC',
      'e.g. vaccination: the individual considers only their own protection, not the reduced transmission to others',
      'Final answer: Consumers weigh only their private benefit, so the market equilibrium occurs where MPB = MPC. Because the social benefit exceeds this, the socially optimal quantity is higher, and the good is under-consumed - as with vaccination, where the individual ignores the protection they give others.',
    ],
    topic: 'Externalities',
  },
  {
    question: 'Explain the two characteristics of a pure public good and why they cause the free rider problem.',
    marks: 4,
    markScheme: [
      'Non-excludable: it is impossible to prevent someone who has not paid from consuming it',
      'Non-rival: one person’s consumption does not reduce the amount available to others',
      'Non-excludability means consumers can wait for others to pay and then consume for free',
      'If everyone free rides there is no revenue, so no private firm will supply it - a missing market',
      'Final answer: Public goods are non-excludable and non-rival. Because non-payers cannot be excluded, everyone has an incentive to free ride; with no way to charge, no private firm can profit from supplying it, so the market fails completely.',
    ],
    topic: 'Public Goods and Information Gaps',
  },
  {
    question: 'Analyse how asymmetric information can cause market failure in the second-hand car market.',
    marks: 8,
    markScheme: [
      'Asymmetric information: the seller knows the car’s true condition, the buyer does not',
      'Buyers cannot distinguish good cars from "lemons", so they offer only an average price',
      'Owners of good cars refuse to sell at the average price and withdraw from the market',
      'The average quality remaining falls, so buyers lower their offers further - adverse selection',
      'In the extreme the market unravels and only poor-quality cars trade',
      'Resource misallocation: mutually beneficial trades in good cars do not happen',
      'Final answer: Because sellers know more than buyers, buyers only offer an average price; owners of good cars withdraw, average quality falls, and offers fall further. This adverse selection drives good cars out of the market, so mutually beneficial trades fail to occur.',
    ],
    topic: 'Public Goods and Information Gaps',
  },
  {
    question: 'Evaluate the use of indirect taxation as a method of correcting the market failure caused by carbon emissions.',
    marks: 12,
    markScheme: [
      'A carbon tax internalises the externality: it shifts MPC up towards MSC',
      'Diagram: supply shifts left, output falls towards the social optimum, welfare loss is reduced',
      'Advantages: uses the price mechanism, raises revenue that can be hypothecated to green investment, incentivises firms to innovate to reduce emissions',
      'Evaluation: demand for energy is price inelastic, so a large tax is needed to change behaviour much',
      'Evaluation: regressive - it takes a larger share of income from poorer households',
      'Evaluation: setting the tax requires valuing the external cost, which is very difficult',
      'Evaluation: risk of production relocating to countries without a carbon tax (carbon leakage), so global emissions may not fall',
      'Alternatives: tradable permits give certainty over quantity; regulation is simpler but blunter',
      'Final answer: A carbon tax works in principle by internalising the external cost and creating an ongoing incentive to innovate, but its effectiveness is limited by inelastic demand, it is regressive, the correct rate is very hard to calculate, and it risks carbon leakage. It is most effective combined with regulation and international agreement.',
    ],
    topic: 'Government Intervention in Markets',
  },
  {
    question: 'Explain, using a diagram, the effect of a minimum price set above equilibrium in the market for alcohol.',
    marks: 6,
    markScheme: [
      'Diagram: horizontal minimum price line above the equilibrium price',
      'At the minimum price, quantity supplied exceeds quantity demanded - an excess supply',
      'Consumption falls from Q1 to Qd, which is the policy objective given alcohol’s negative externalities',
      'Producers gain higher revenue per unit; the surplus is not bought by government (unlike a buffer stock)',
      'Effectiveness limited by inelastic demand for alcohol among heavy drinkers',
      'Final answer: A minimum price above equilibrium creates excess supply and reduces consumption from Q1 to Qd, reducing the external costs of drinking - though demand from the heaviest drinkers is price inelastic, limiting the fall.',
    ],
    topic: 'Government Intervention in Markets',
  },
  {
    question: 'Analyse two causes of government failure.',
    marks: 8,
    markScheme: [
      'Information gaps: government lacks the information to value externalities or set a tax at the right level',
      'Result: over- or under-correction, potentially leaving welfare lower than before',
      'Unintended consequences: policy changes incentives in unforeseen ways',
      'e.g. a landfill tax raising fly-tipping; rent controls reducing the supply of rented housing',
      'Other valid: administrative costs, regulatory capture, political short-termism ahead of elections',
      'Final answer: Governments often lack the information needed to set intervention at the right level, causing over- or under-correction; and intervention creates unintended consequences, such as a landfill tax increasing fly-tipping - in both cases welfare can end up lower than with no intervention at all.',
    ],
    topic: 'Government Failure',
  },
  {
    question: 'Explain what is meant by regulatory capture and why it leads to government failure.',
    marks: 4,
    markScheme: [
      'Regulatory capture is where a regulator comes to act in the interests of the firms it regulates',
      'Occurs because the industry holds the technical information and lobbies intensively',
      'Movement of staff between the regulator and the industry reinforces it',
      'Consequence: regulation is too lax, so the original market failure persists while regulatory costs are still incurred',
      'Final answer: Regulatory capture is when a regulator ends up serving the industry it oversees, because that industry holds the expertise and lobbies hardest. Regulation then becomes too weak to correct the market failure while still imposing costs - so welfare falls.',
    ],
    topic: 'Government Failure',
  },

  // =========================================================== THEME 2
  {
    question: 'Explain two limitations of using real GDP per capita to compare living standards between countries.',
    marks: 4,
    markScheme: [
      'It is a mean, so says nothing about distribution - high inequality means the typical person may be far poorer',
      'It excludes the informal economy and unpaid work, which is a larger share of output in developing countries',
      'It ignores negative externalities such as pollution generated in producing that output',
      'It ignores non-material determinants of welfare: health, education, leisure, political freedom',
      'Final answer: Real GDP per capita is an average that hides inequality, and it omits the informal economy, unpaid work, environmental damage and non-material factors like health and leisure - so two countries with equal GDP per capita can have very different living standards.',
    ],
    topic: 'Economic Growth',
  },
  {
    question: 'Explain the difference between nominal and real GDP, and why real GDP is used to measure economic growth.',
    marks: 4,
    markScheme: [
      'Nominal GDP measures output at current prices, so it rises when prices rise as well as when output rises',
      'Real GDP is adjusted for inflation, valuing output at constant base-year prices',
      'Using nominal GDP would record growth in a year where output was flat but prices rose 5%',
      'Only real GDP isolates the change in the actual volume of goods and services produced',
      'Final answer: Nominal GDP is measured at current prices and so rises with inflation as well as output, whereas real GDP holds prices constant. Economic growth uses real GDP because only that isolates a genuine increase in the quantity of output rather than a rise in prices.',
    ],
    topic: 'Economic Growth',
  },
  {
    question: 'Analyse, using an AD/AS diagram, how a large rise in world oil prices affects the UK price level and output.',
    marks: 8,
    markScheme: [
      'Oil is an input into almost all production, so costs of production rise across the economy',
      'Diagram: SRAS shifts left, from SRAS1 to SRAS2',
      'Price level rises P1 to P2 and real output falls Y1 to Y2',
      'This is cost-push inflation combined with falling output - stagflation',
      'Policy dilemma: raising interest rates to control inflation worsens the fall in output',
      'Magnitude depends on the economy’s oil intensity and the availability of substitutes',
      'Final answer: Higher oil prices raise costs across the economy, shifting SRAS left so that the price level rises while real output falls. This stagflation creates a policy dilemma, since tackling the inflation with tighter policy deepens the fall in output.',
    ],
    topic: 'Inflation',
  },
  {
    question: 'Explain the difference between demand-pull and cost-push inflation.',
    marks: 4,
    markScheme: [
      'Demand-pull: caused by AD rising faster than the economy’s capacity to supply',
      'Shown as AD shifting right along an upward-sloping or vertical AS curve; output tends to rise too',
      'Cost-push: caused by a rise in the costs of production',
      'Shown as SRAS shifting left; output falls as the price level rises',
      'Final answer: Demand-pull inflation comes from excess demand (AD shifting right), and tends to raise output as well as prices; cost-push inflation comes from rising production costs (SRAS shifting left), and raises prices while reducing output.',
    ],
    topic: 'Inflation',
  },
  {
    question: 'Analyse two economic costs of high and persistent unemployment.',
    marks: 8,
    markScheme: [
      'Lost output: the economy operates inside its PPF, so real GDP is below potential permanently forgone',
      'Fiscal cost: higher welfare spending combined with lower income tax and VAT receipts widens the budget deficit',
      'Hysteresis: the long-term unemployed lose skills and work habits, lowering potential output even after recovery',
      'Social costs: poorer physical and mental health, higher crime, wider inequality',
      'Final answer: Unemployment permanently forgoes output the economy could have produced, and worsens the public finances through higher benefit spending and lower tax revenue. Persistent unemployment also causes hysteresis, as skills erode and potential output itself falls.',
    ],
    topic: 'Employment and Unemployment',
  },
  {
    question: 'Explain the difference between structural, frictional and cyclical unemployment.',
    marks: 6,
    markScheme: [
      'Structural: a mismatch between workers’ skills or location and available jobs, caused by long-term change in the pattern of demand',
      'e.g. decline of coal mining leaving workers without transferable skills',
      'Frictional: short-term unemployment while people move between jobs; largely voluntary and unavoidable',
      'Cyclical (demand-deficient): caused by a fall in AD during a recession, affecting all sectors',
      'Final answer: Structural unemployment is a lasting mismatch of skills or location, frictional is short-term job search between roles, and cyclical is caused by deficient aggregate demand in a downturn.',
    ],
    topic: 'Employment and Unemployment',
  },
  {
    question: 'Explain what is meant by a current account deficit and identify two of its possible causes.',
    marks: 4,
    markScheme: [
      'A current account deficit means the value of imports of goods, services, income and transfers exceeds exports',
      'Cause: poor international competitiveness - high relative unit labour costs or low productivity',
      'Cause: a strong exchange rate making exports expensive and imports cheap',
      'Cause: strong domestic growth relative to trading partners, sucking in imports',
      'Final answer: A current account deficit is where outflows on trade, income and transfers exceed inflows. It may be caused by weak competitiveness (high unit labour costs), a strong exchange rate, or domestic growth outpacing that of trading partners.',
    ],
    topic: 'Balance of Payments',
  },
  {
    question: 'Explain why a current account deficit is not necessarily a problem for an economy.',
    marks: 4,
    markScheme: [
      'A deficit may reflect strong economic growth and high consumer confidence, which are desirable',
      'It may be financed by a financial account surplus - inward FDI that raises future productive capacity',
      'Imports of capital goods raise future potential output',
      'It becomes a problem if it is large, persistent, and financed by short-term "hot money" that can leave suddenly',
      'Final answer: A deficit can reflect healthy growth and be financed by inward investment that raises future capacity, especially if imports are capital goods. It becomes a problem only when large, persistent, and financed by volatile short-term capital flows.',
    ],
    topic: 'Balance of Payments',
  },
  {
    question: 'Explain the four components of aggregate demand and state which is normally the largest in the UK.',
    marks: 4,
    markScheme: [
      'AD = C + I + G + (X - M)',
      'C is household consumption; I is gross investment by firms; G is government spending',
      '(X - M) is net trade: exports minus imports',
      'Consumption is the largest, at roughly 60-65% of UK AD',
      'Final answer: AD = C + I + G + (X - M) - consumption, investment, government spending and net trade. Consumption is much the largest, at around 60-65% of UK aggregate demand.',
    ],
    topic: 'Components of Aggregate Demand',
  },
  {
    question: 'Analyse how a fall in interest rates affects each component of aggregate demand.',
    marks: 8,
    markScheme: [
      'Consumption rises: cheaper borrowing, lower mortgage repayments raise disposable income, saving less attractive',
      'Investment rises: more projects become profitable as the cost of borrowing falls',
      'Net trade: lower rates reduce the attractiveness of the currency, causing depreciation',
      'Depreciation makes exports cheaper and imports dearer, so (X - M) improves',
      'G is largely unaffected directly, though debt interest costs fall',
      'Overall AD shifts right; magnitude depends on confidence and the size of existing debt',
      'Final answer: Lower interest rates raise consumption through cheaper borrowing and lower saving returns, raise investment as more projects become viable, and improve net trade via currency depreciation - shifting AD right, though the size of the effect depends heavily on business and consumer confidence.',
    ],
    topic: 'Components of Aggregate Demand',
  },
  {
    question: 'Explain the difference between the average propensity to consume and the marginal propensity to consume.',
    marks: 4,
    markScheme: [
      'APC = total consumption / total disposable income - the proportion of all income spent',
      'MPC = change in consumption / change in disposable income - the proportion of extra income spent',
      'MPC is the one that determines the size of the multiplier',
      'MPC is typically higher for lower-income households, who must spend a larger share of any extra income',
      'Final answer: APC is the share of total income that is consumed; MPC is the share of any additional income that is consumed. It is MPC that determines the multiplier, and it is generally higher for poorer households.',
    ],
    topic: 'Consumption, Savings and Investment',
  },
  {
    question: 'Analyse the factors that influence business investment.',
    marks: 8,
    markScheme: [
      'Interest rates: the cost of borrowing and the opportunity cost of using retained profit',
      'Business confidence and "animal spirits": expectations of future demand may matter more than rates',
      'Level of retained profit: the main source of investment finance for most firms',
      'Corporation tax and investment allowances alter the post-tax return',
      'Technological change creating new profitable opportunities',
      'Spare capacity: firms with idle plant have little reason to invest',
      'Final answer: Investment depends on interest rates, retained profit and tax treatment, but business confidence about future demand is often decisive - firms with spare capacity will not invest however cheap borrowing becomes.',
    ],
    topic: 'Consumption, Savings and Investment',
  },
  {
    question: 'Explain why the short-run aggregate supply curve slopes upwards while the long-run curve (Classical view) is vertical.',
    marks: 6,
    markScheme: [
      'SRAS: in the short run some costs, especially nominal wages, are fixed by contract',
      'A higher price level therefore raises profit margins, so firms expand output - upward slope',
      'LRAS (Classical): in the long run all prices and wages are flexible and adjust fully',
      'Output is then determined solely by the quantity and quality of factors of production, not the price level',
      'So LRAS is vertical at the full employment level of output',
      'Final answer: In the short run wages are sticky, so a higher price level widens margins and firms produce more, giving an upward-sloping SRAS. In the long run wages adjust fully, so output depends only on the economy’s productive capacity and LRAS is vertical.',
    ],
    topic: 'Aggregate Supply',
  },
  {
    question: 'Explain two factors that would shift the long-run aggregate supply curve to the right.',
    marks: 4,
    markScheme: [
      'Investment in new capital raises the capital stock and productive capacity',
      'Improved education and training raises human capital and labour productivity',
      'Other valid: net inward migration raising the labour force, technological advance, deregulation, discovery of raw materials',
      'These raise potential output, so LRAS shifts right - potential economic growth',
      'Final answer: Anything raising the quantity or quality of factors of production - for example investment raising the capital stock, or improved education raising labour productivity - shifts LRAS right and increases the economy’s potential output.',
    ],
    topic: 'Aggregate Supply',
  },
  {
    question: 'The marginal propensity to consume is 0.6, with an MPT of 0.2 and an MPM of 0.1. Calculate the multiplier and explain what it means for a £10bn increase in government spending.',
    marks: 6,
    markScheme: [
      'MPS = 1 - MPC = 1 - 0.6 = 0.1',
      'Total withdrawals: MPS + MPT + MPM = 0.1 + 0.2 + 0.1 = 0.4',
      'Multiplier = 1 / 0.4 = 2.5',
      'A £10bn injection therefore raises national income by £10bn × 2.5 = £25bn',
      'Because the initial spending becomes someone’s income, part of which is re-spent, and so on',
      'Final answer: The multiplier is 1 / 0.4 = 2.5, so £10bn of extra government spending eventually raises national income by £25bn as the initial injection is re-spent round the circular flow.',
    ],
    topic: 'The Circular Flow of Income and the Multiplier',
  },
  {
    question: 'Explain why the size of the multiplier is smaller in an open economy with high taxation.',
    marks: 4,
    markScheme: [
      'The multiplier = 1 / (MPS + MPT + MPM)',
      'High taxation raises MPT, so more of each round of income is withdrawn',
      'An open economy has a high MPM, so more spending leaks abroad as imports',
      'Larger withdrawals mean each successive round of re-spending is smaller, so the multiplier is smaller',
      'Final answer: Because taxation and imports are withdrawals from the circular flow. A high MPT and MPM mean less of each round of extra income is re-spent domestically, so the multiplier 1/(MPS+MPT+MPM) is smaller.',
    ],
    topic: 'The Circular Flow of Income and the Multiplier',
  },
  {
    question: 'Evaluate the view that economic growth always improves living standards.',
    marks: 12,
    markScheme: [
      'Benefits: higher real incomes, more consumption, lower unemployment, higher tax revenue funding public services',
      'Growth can reduce absolute poverty and fund healthcare and education',
      'Evaluation: depends on distribution - if gains accrue to the top, median living standards may stagnate',
      'Evaluation: negative externalities - pollution, congestion, resource depletion reduce quality of life',
      'Evaluation: growth may be unsustainable, borrowing welfare from future generations',
      'Evaluation: costs of growth include longer working hours and reduced leisure',
      'Evaluation: depends on the type of growth - export-led vs consumption-fuelled and debt-financed',
      'Final answer: Growth usually raises living standards by raising incomes, cutting unemployment and funding public services, but not always - if the gains are captured by a small share of the population, or offset by pollution, congestion and resource depletion, average measured income can rise while welfare does not.',
    ],
    topic: 'Causes and Effects of Economic Growth',
  },
  {
    question: 'Explain what is meant by an output gap and how a negative output gap would be identified.',
    marks: 4,
    markScheme: [
      'An output gap is the difference between actual real GDP and potential (trend) output',
      'A negative output gap means actual output is below potential - spare capacity exists',
      'Indicators: unemployment above the natural rate, falling inflation, low capacity utilisation',
      'Shown on an AD/AS diagram as AD intersecting SRAS to the left of LRAS',
      'Final answer: An output gap is the difference between actual and potential output. A negative gap means the economy is producing below capacity, indicated by high unemployment, low capacity utilisation and falling inflationary pressure.',
    ],
    topic: 'Causes and Effects of Economic Growth',
  },
  {
    question: 'Explain two possible conflicts between macroeconomic objectives.',
    marks: 6,
    markScheme: [
      'Growth vs inflation: rising AD to boost growth can generate demand-pull inflation as the economy nears capacity',
      'Growth vs the current account: faster growth raises import demand, worsening the current account deficit',
      'Unemployment vs inflation: the short-run Phillips curve trade-off',
      'Growth vs the environment: higher output raises emissions and resource depletion',
      'Final answer: Pursuing growth by raising AD tends to generate demand-pull inflation as spare capacity disappears, and also worsens the current account as higher incomes suck in imports - so growth conflicts with both price stability and external balance.',
    ],
    topic: 'Macroeconomic Objectives',
  },
  {
    question: 'Explain why price stability is defined as low positive inflation rather than zero inflation.',
    marks: 4,
    markScheme: [
      'The UK target is 2% CPI, not 0%',
      'Deflation is damaging: consumers delay purchases expecting lower prices, so AD falls further',
      'Deflation raises the real value of debt, worsening balance sheets',
      'A small positive rate gives room to cut real interest rates below zero in a downturn',
      'It also allows relative wages to adjust without nominal wage cuts, which workers resist',
      'Final answer: A small positive target avoids the risk of deflation, which depresses spending and raises real debt burdens, and it leaves room for real interest rates to fall in a recession and for relative wages to adjust without nominal pay cuts.',
    ],
    topic: 'Macroeconomic Objectives',
  },
  {
    question: 'Evaluate the effectiveness of expansionary fiscal policy in closing a large negative output gap.',
    marks: 12,
    markScheme: [
      'Higher G or lower T raises AD directly; G has the larger immediate effect as it is spending, not partly saved',
      'Diagram: AD shifts right, closing the output gap, raising real output and reducing cyclical unemployment',
      'Multiplier effect magnifies the initial injection; large when spare capacity exists',
      'Evaluation: time lags - identifying the gap, legislating, and implementing infrastructure takes years',
      'Evaluation: crowding out - government borrowing may raise interest rates and displace private investment, though this is weak with spare capacity',
      'Evaluation: worsens the budget deficit and national debt, potentially raising debt-servicing costs',
      'Evaluation: leakage into imports reduces the multiplier in an open economy',
      'Evaluation: effectiveness depends on confidence - Ricardian equivalence suggests households may save a tax cut expecting future tax rises',
      'Final answer: Expansionary fiscal policy directly raises AD and is most effective in a deep recession, where spare capacity makes crowding out unlikely and the multiplier large. Its weaknesses are long implementation lags, a worsening deficit, and leakage into imports - so it works best targeted at capital spending with a high domestic multiplier.',
    ],
    topic: 'Fiscal Policy',
  },
  {
    question: 'Explain the difference between a structural and a cyclical budget deficit.',
    marks: 4,
    markScheme: [
      'A cyclical deficit is the part caused by the economic cycle',
      'In a recession, tax receipts fall and benefit spending rises automatically - it disappears as the economy recovers',
      'A structural deficit is the part that remains even at full employment',
      'It reflects a permanent mismatch between spending commitments and the tax base, so requires policy change to remove',
      'Final answer: A cyclical deficit is caused by the downturn and corrects itself as the economy recovers through automatic stabilisers; a structural deficit persists even at full capacity and can only be removed by raising taxes or cutting spending.',
    ],
    topic: 'Fiscal Policy',
  },
  {
    question: 'Analyse the transmission mechanism by which a rise in the Bank Rate reduces inflation.',
    marks: 8,
    markScheme: [
      'Higher Bank Rate raises commercial bank lending and saving rates',
      'Consumption falls: borrowing is dearer, mortgage repayments rise reducing disposable income, saving becomes more attractive',
      'Investment falls: fewer projects clear the higher cost of capital',
      'Exchange rate appreciates as hot money inflows rise, making imports cheaper and exports dearer',
      'So AD falls: C, I and (X - M) all decline; AD shifts left',
      'Lower AD reduces demand-pull inflationary pressure; the stronger pound also reduces imported inflation',
      'Time lag of up to two years for the full effect',
      'Final answer: A higher Bank Rate raises borrowing costs, reducing consumption and investment, and appreciates the exchange rate, worsening net trade but lowering import prices. AD shifts left, easing demand-pull inflation - though the full effect takes up to two years.',
    ],
    topic: 'Monetary Policy',
  },
  {
    question: 'Explain what quantitative easing is and why a central bank would use it.',
    marks: 4,
    markScheme: [
      'QE is the central bank creating money electronically to buy financial assets, mainly government bonds',
      'This raises bond prices and lowers their yields, reducing long-term interest rates across the economy',
      'It increases commercial banks’ reserves, encouraging lending, and raises asset prices creating a wealth effect',
      'Used when Bank Rate is already near zero and conventional policy has no room left',
      'Final answer: QE is asset purchases funded by newly created money, used when interest rates are already near zero. By raising bond prices it lowers long-term yields, encourages bank lending and raises asset prices - stimulating AD when conventional monetary policy is exhausted.',
    ],
    topic: 'Monetary Policy',
  },
  {
    question: 'Evaluate the view that supply-side policies are more effective than demand-side policies in raising long-run economic growth.',
    marks: 12,
    markScheme: [
      'Supply-side policies raise productive capacity, shifting LRAS right - this is the only source of sustainable long-run growth',
      'Market-based: tax cuts, deregulation, trade union reform, privatisation - improve incentives and efficiency',
      'Interventionist: education and training, infrastructure, R&D subsidies - address market failure in human and physical capital',
      'Non-inflationary: unlike demand-side stimulus, raising LRAS lowers the price level as output rises',
      'Evaluation: very long time lags - education reforms take a generation to affect the workforce',
      'Evaluation: high fiscal cost, and outcomes are uncertain; market-based policies can widen inequality',
      'Evaluation: supply-side policy is ineffective in a deep recession where the constraint is deficient demand, not capacity',
      'Evaluation: the two are complements - demand-side policy stabilises the cycle, supply-side raises the trend',
      'Final answer: Supply-side policies are the only route to sustainable long-run growth because they raise capacity without inflation, but they act slowly, cost a great deal and are uncertain. They are not a substitute for demand-side policy in a recession, where the binding constraint is deficient demand - the two are complements rather than alternatives.',
    ],
    topic: 'Supply-Side Policy',
  },
  {
    question: 'Explain the difference between market-based and interventionist supply-side policies, with one example of each.',
    marks: 4,
    markScheme: [
      'Market-based policies remove barriers to the free operation of markets and improve incentives',
      'e.g. cutting income tax to increase the incentive to work, or deregulating an industry',
      'Interventionist policies involve the government directly correcting a market failure',
      'e.g. state funding of apprenticeships and training, or building infrastructure',
      'Final answer: Market-based policies free up markets and sharpen incentives, such as cutting income tax to encourage work; interventionist policies have government act directly to fix a market failure, such as funding training or building infrastructure.',
    ],
    topic: 'Supply-Side Policy',
  },
]
