/*
  Extra Edexcel A-level Economics A multiple-choice questions.

  After the exam-question batches, 20 chapters were still on only 3 MCQs
  while the rest had 6. These add 3 to each of those 20 so no chapter is
  short, and every chapter can support more than one MCQ session without
  simply repeating.

  Distractors are the definitions students actually confuse - movement
  along versus shift, deficit versus debt, equity versus equality, absolute
  versus comparative advantage - so a wrong answer identifies the specific
  misconception.
*/
export const ECON_MCQ_2 = [
  {
    question: 'Which of these is a normative statement?',
    options: [
      'The government should reduce income inequality',
      'Inflation was 4.2% last year',
      'Unemployment rose by 30,000 in the quarter',
      'A rise in price led to a fall in quantity demanded',
    ],
    answer: 0,
    explanation: '"Should" signals a value judgement, which cannot be tested against evidence. The others are all factual claims that data could confirm or refute.',
    topic: 'Economic Methodology and the Economic Problem',
  },
  {
    question: 'Which best describes the "economic problem"?',
    options: [
      'Scarce resources but unlimited wants, forcing choices',
      'Governments spending more than they collect in tax',
      'Prices rising faster than incomes',
      'Unemployment existing alongside vacancies',
    ],
    answer: 0,
    explanation: 'The economic problem is scarcity relative to unlimited wants. The other options are specific issues that follow from it, not the problem itself.',
    topic: 'Economic Methodology and the Economic Problem',
  },
  {
    question: 'A student gives up a £20,000 salary to study, paying £9,000 in fees. What is the opportunity cost of one year of study?',
    options: ['£29,000', '£20,000', '£9,000', '£11,000'],
    answer: 0,
    explanation: 'Opportunity cost includes both the explicit cost (£9,000 fees) and the implicit cost of the forgone salary (£20,000), giving £29,000.',
    topic: 'Economic Methodology and the Economic Problem',
  },
  {
    question: 'A point inside the production possibility frontier indicates:',
    options: [
      'Unemployed or inefficiently used resources',
      'An unattainable combination of output',
      'Maximum productive efficiency',
      'That the economy is growing',
    ],
    answer: 0,
    explanation: 'Inside the PPF the economy is producing less than it could with existing resources, so factors are unemployed or misallocated.',
    topic: 'Production Possibility Frontiers',
  },
  {
    question: 'Why is a PPF usually drawn concave to the origin?',
    options: [
      'Resources are not equally suited to producing both goods, so opportunity cost increases',
      'Resources are perfectly substitutable between the two goods',
      'The economy is experiencing economic growth',
      'Because of diminishing returns to capital',
    ],
    answer: 0,
    explanation: 'As production shifts, increasingly unsuitable resources must be transferred, so each extra unit costs more of the other good - increasing opportunity cost.',
    topic: 'Production Possibility Frontiers',
  },
  {
    question: 'A country experiences net emigration of skilled workers. On its PPF diagram this is shown as:',
    options: [
      'An inward shift of the PPF',
      'A movement along the PPF',
      'An outward shift of the PPF',
      'A movement to a point inside the PPF',
    ],
    answer: 0,
    explanation: 'Losing factors of production reduces productive capacity, so the whole frontier shifts inwards - a fall in potential output.',
    topic: 'Production Possibility Frontiers',
  },
  {
    question: 'In a free market economy, the fundamental questions of what to produce are answered by:',
    options: [
      'The price mechanism and consumer spending',
      'Central government planners',
      'Producer cooperatives',
      'International trade agreements',
    ],
    answer: 0,
    explanation: 'Prices signal, incentivise and ration, so consumer spending decisions determine what is produced without any central direction.',
    topic: 'Economic Systems',
  },
  {
    question: 'Which is a disadvantage of a command economy?',
    options: [
      'Planners lack the information the price mechanism generates automatically',
      'Income inequality is extremely high',
      'Public goods are under-provided',
      'Firms have excessive monopoly power',
    ],
    answer: 0,
    explanation: 'The information problem is the classic weakness of central planning. The other three are characteristic failures of free markets, not command economies.',
    topic: 'Economic Systems',
  },
  {
    question: 'Adam Smith’s "invisible hand" refers to the idea that:',
    options: [
      'Individuals pursuing self-interest can produce a socially beneficial outcome',
      'Governments must guide markets to efficient outcomes',
      'Markets always fail without regulation',
      'Prices are set by producers rather than markets',
    ],
    answer: 0,
    explanation: 'Smith argued that self-interested decisions, coordinated through prices, can allocate resources efficiently without anyone intending that result.',
    topic: 'Economic Systems',
  },
  {
    question: 'Which is an example of the government using a "nudge" rather than regulation?',
    options: [
      'Automatically enrolling employees into a pension they can opt out of',
      'Banning smoking in enclosed public places',
      'Imposing a tax on sugary drinks',
      'Setting a legal minimum wage',
    ],
    answer: 0,
    explanation: 'A nudge changes how choices are presented without removing any option. Bans, taxes and legal minimums all change the choice set or its price directly.',
    topic: 'Rational Decision Making',
  },
  {
    question: 'What does "bounded rationality" mean?',
    options: [
      'Consumers satisfice because information and time are limited',
      'Consumers always maximise utility perfectly',
      'Consumers have unlimited wants',
      'Firms are constrained by law in what they can charge',
    ],
    answer: 0,
    explanation: 'With limited information and computing time, people settle for a good-enough choice rather than the optimal one.',
    topic: 'Rational Decision Making',
  },
  {
    question: 'A consumer buys the same brand of coffee every week without checking rival prices. This best illustrates:',
    options: [
      'The influence of habitual behaviour',
      'Perfect information',
      'Rational utility maximisation',
      'The substitution effect',
    ],
    answer: 0,
    explanation: 'Habit removes the active comparison that rational choice theory assumes, which is why the behavioural critique matters for real markets.',
    topic: 'Rational Decision Making',
  },
  {
    question: 'A landfill tax leads to a large rise in fly-tipping. This is an example of:',
    options: [
      'Government failure through unintended consequences',
      'A successful correction of a negative externality',
      'Regulatory capture',
      'Complete market failure',
    ],
    answer: 0,
    explanation: 'The policy changed incentives in an unforeseen way, creating a new external cost that can leave welfare lower than before.',
    topic: 'Government Failure',
  },
  {
    question: 'Which best describes regulatory capture?',
    options: [
      'A regulator acting in the interests of the firms it regulates',
      'A government taking a firm into public ownership',
      'A firm being fined for breaking competition law',
      'A regulator setting a price cap below cost',
    ],
    answer: 0,
    explanation: 'Because the industry holds the technical expertise and lobbies hardest, regulation can become too lax - imposing cost while failing to correct the market failure.',
    topic: 'Government Failure',
  },
  {
    question: 'Rent controls set below the market rent are most likely to cause:',
    options: [
      'A shortage of rental housing as landlords withdraw supply',
      'An increase in the quality of rental housing',
      'A surplus of available rental properties',
      'A rise in the market equilibrium rent',
    ],
    answer: 0,
    explanation: 'A maximum price below equilibrium leaves quantity demanded above quantity supplied. Landlords exit the market, so the policy intended to help tenants reduces the housing available - a classic case of government failure.',
    topic: 'Government Failure',
  },
  {
    question: 'Which item appears on the current account of the balance of payments?',
    options: [
      'Profits earned abroad by a UK-owned firm',
      'A UK firm buying a factory in Poland',
      'Purchase of foreign government bonds by a UK bank',
      'An increase in official foreign exchange reserves',
    ],
    answer: 0,
    explanation: 'Investment income is primary income, part of the current account. The other three are all financial account transactions.',
    topic: 'Balance of Payments',
  },
  {
    question: 'A current account deficit must be matched by:',
    options: [
      'A surplus on the combined capital and financial accounts',
      'A government budget deficit',
      'A fall in the exchange rate',
      'A rise in unemployment',
    ],
    answer: 0,
    explanation: 'The balance of payments must balance overall, so a current account deficit is financed by net inflows on the financial account.',
    topic: 'Balance of Payments',
  },
  {
    question: 'Which would most likely worsen a country’s current account?',
    options: [
      'A sustained appreciation of its currency',
      'A rise in the productivity of its exporters',
      'A recession among its trading partners… reducing its imports',
      'A fall in domestic wage costs relative to competitors',
    ],
    answer: 0,
    explanation: 'Appreciation makes exports dearer abroad and imports cheaper at home, worsening the trade balance. The others improve competitiveness or reduce imports.',
    topic: 'Balance of Payments',
  },
  {
    question: 'If disposable income rises by £200 and consumption rises by £150, the marginal propensity to consume is:',
    options: ['0.75', '1.33', '0.5', '50'],
    answer: 0,
    explanation: 'MPC = ΔC/ΔY = 150/200 = 0.75. Inverting the fraction gives 1.33 - a common slip.',
    topic: 'Consumption, Savings and Investment',
  },
  {
    question: 'Which would most likely increase business investment?',
    options: [
      'A rise in business confidence about future demand',
      'A rise in corporation tax',
      'A rise in interest rates',
      'An increase in spare capacity',
    ],
    answer: 0,
    explanation: 'Expected future demand is usually the dominant influence. Higher tax and interest rates reduce returns, and spare capacity removes the need to invest.',
    topic: 'Consumption, Savings and Investment',
  },
  {
    question: 'The wealth effect describes how:',
    options: [
      'A rise in asset values increases consumption',
      'Higher incomes increase saving',
      'Richer countries grow faster',
      'Inequality reduces the multiplier',
    ],
    answer: 0,
    explanation: 'When house or share prices rise, households feel wealthier and more secure, so they consume more even without a rise in current income.',
    topic: 'Consumption, Savings and Investment',
  },
  {
    question: 'The Classical long-run aggregate supply curve is vertical because:',
    options: [
      'In the long run output depends only on factors of production, not the price level',
      'Wages are fixed by long-term contracts',
      'Firms always operate at full capacity',
      'Aggregate demand is perfectly inelastic',
    ],
    answer: 0,
    explanation: 'With fully flexible wages and prices, output settles at the full-employment level determined by the quantity and quality of factors, whatever the price level.',
    topic: 'Aggregate Supply',
  },
  {
    question: 'Which would shift the short-run aggregate supply curve to the left?',
    options: [
      'A sharp rise in world commodity prices',
      'An increase in the size of the labour force',
      'A fall in the rate of corporation tax',
      'Investment in new technology',
    ],
    answer: 0,
    explanation: 'Higher input costs reduce the quantity firms will supply at each price level. The other three raise capacity or lower costs, shifting supply right.',
    topic: 'Aggregate Supply',
  },
  {
    question: 'On the Keynesian AS curve, an increase in AD at very low output levels causes:',
    options: [
      'A large rise in output with little change in the price level',
      'A large rise in the price level with no change in output',
      'A fall in output',
      'No change in either output or prices',
    ],
    answer: 0,
    explanation: 'With substantial spare capacity the Keynesian AS curve is nearly horizontal, so extra demand is met by raising output rather than prices.',
    topic: 'Aggregate Supply',
  },
  {
    question: 'A negative output gap is most likely to be associated with:',
    options: [
      'Unemployment above the natural rate and falling inflation',
      'Rising inflationary pressure',
      'Output above the long-run trend',
      'Full capacity utilisation',
    ],
    answer: 0,
    explanation: 'A negative gap means the economy is operating below capacity, so there is spare labour and capital and downward pressure on prices.',
    topic: 'Causes and Effects of Economic Growth',
  },
  {
    question: 'Which is most likely to raise a country’s long-run trend rate of growth?',
    options: [
      'Sustained investment in education and infrastructure',
      'A temporary cut in interest rates',
      'A one-off increase in government spending',
      'A depreciation of the exchange rate',
    ],
    answer: 0,
    explanation: 'Only policies raising productive capacity shift LRAS and change the trend rate. The others affect aggregate demand and so actual, not potential, growth.',
    topic: 'Causes and Effects of Economic Growth',
  },
  {
    question: 'Which is a cost of rapid economic growth?',
    options: [
      'Increased negative externalities such as pollution and congestion',
      'Lower unemployment',
      'Higher tax revenues',
      'Rising average incomes',
    ],
    answer: 0,
    explanation: 'Higher output generally means more emissions, congestion and resource depletion. The other three are benefits of growth.',
    topic: 'Causes and Effects of Economic Growth',
  },
  {
    question: 'Which is a market-based supply-side policy?',
    options: [
      'Reducing the rate of income tax to strengthen work incentives',
      'Government funding of apprenticeship schemes',
      'State investment in road and rail infrastructure',
      'Direct government provision of childcare',
    ],
    answer: 0,
    explanation: 'Market-based policies work by improving incentives and freeing markets; the other three involve government acting directly, so they are interventionist.',
    topic: 'Supply-Side Policy',
  },
  {
    question: 'A successful supply-side policy shown on an AD/AS diagram results in:',
    options: [
      'Higher output and a lower price level',
      'Higher output and a higher price level',
      'Lower output and a lower price level',
      'No change in output and a higher price level',
    ],
    answer: 0,
    explanation: 'Shifting LRAS right raises output while easing price pressure - which is why supply-side growth is described as non-inflationary.',
    topic: 'Supply-Side Policy',
  },
  {
    question: 'What is the main drawback of supply-side policies?',
    options: [
      'They involve very long time lags before taking effect',
      'They always cause inflation',
      'They reduce the economy’s productive capacity',
      'They cannot be used alongside monetary policy',
    ],
    answer: 0,
    explanation: 'Education and infrastructure take years or decades to raise capacity, so supply-side policy cannot address a recession happening now.',
    topic: 'Supply-Side Policy',
  },
  {
    question: 'A firm sells off one of its divisions as a separate company. This is:',
    options: ['A demerger', 'A horizontal merger', 'A vertical integration', 'A conglomerate merger'],
    answer: 0,
    explanation: 'Splitting a business into separate entities is a demerger - the reverse of the integration described in the other options.',
    topic: 'Demergers',
  },
  {
    question: 'Which is a likely motive for a demerger?',
    options: [
      'To escape diseconomies of scale and refocus on core activities',
      'To increase monopoly power in the market',
      'To secure supplies of a raw material',
      'To achieve purchasing economies of scale',
    ],
    answer: 0,
    explanation: 'Demergers reduce size and complexity. The other three are motives for integration, which increases size.',
    topic: 'Demergers',
  },
  {
    question: 'A likely negative impact of a demerger on workers is:',
    options: [
      'Redundancies where head-office functions were duplicated',
      'A guaranteed increase in wages',
      'Reduced competition for their jobs',
      'A larger internal labour market',
    ],
    answer: 0,
    explanation: 'Separating the businesses means functions no longer shared must be duplicated or cut, and support roles are the usual casualty.',
    topic: 'Demergers',
  },
  {
    question: 'What is the minimum efficient scale?',
    options: [
      'The lowest output at which long-run average cost is minimised',
      'The smallest output at which a firm breaks even',
      'The output where marginal cost equals marginal revenue',
      'The maximum output a firm can produce',
    ],
    answer: 0,
    explanation: 'MES is where the LRAC curve first reaches its minimum, and its size relative to market demand shapes market structure.',
    topic: 'Economies and Diseconomies of Scale',
  },
  {
    question: 'A large firm can borrow at lower interest rates than a small one. This is an example of:',
    options: [
      'Financial economies of scale',
      'Technical economies of scale',
      'Purchasing economies of scale',
      'External economies of scale',
    ],
    answer: 0,
    explanation: 'Financial economies arise because large firms are lower risk and have more collateral, so lenders charge them less.',
    topic: 'Economies and Diseconomies of Scale',
  },
  {
    question: 'Which is an external economy of scale?',
    options: [
      'A local university producing graduates skilled in the industry',
      'A firm buying raw materials in bulk',
      'A firm employing specialist managers',
      'A firm investing in automated production lines',
    ],
    answer: 0,
    explanation: 'External economies arise from growth of the whole industry or region and benefit every firm in it; the others are internal to a single firm.',
    topic: 'Economies and Diseconomies of Scale',
  },
  {
    question: 'Why does a firm in monopolistic competition face a downward-sloping demand curve, unlike one in perfect competition?',
    options: [
      'Its product is differentiated, giving it some price-setting power',
      'It is the only firm in the market',
      'There are high barriers to entry',
      'It faces no close substitutes',
    ],
    answer: 0,
    explanation: 'Differentiation means some customers stay even if it raises price, so demand slopes downwards - though it is highly elastic because close substitutes exist.',
    topic: 'Monopolistic Competition',
  },
  {
    question: 'In long-run equilibrium, a firm in monopolistic competition earns:',
    options: ['Normal profit only', 'Supernormal profit', 'A loss', 'Zero total revenue'],
    answer: 0,
    explanation: 'Low barriers to entry mean new firms enter until AR is tangential to AC, competing away any supernormal profit.',
    topic: 'Monopolistic Competition',
  },
  {
    question: 'Why is a monopolistically competitive firm productively inefficient in the long run?',
    options: [
      'It produces where AR is tangent to AC, on the downward-sloping part of AC',
      'It produces where MC is above MR',
      'It always makes a loss',
      'It faces a perfectly elastic demand curve',
    ],
    answer: 0,
    explanation: 'The tangency occurs before the minimum of AC, so the firm operates with excess capacity and never reaches the lowest point on its cost curve.',
    topic: 'Monopolistic Competition',
  },
  {
    question: 'A market is contestable if:',
    options: [
      'Barriers to entry and exit, including sunk costs, are low',
      'There are many firms already operating in it',
      'The largest firm has less than 25% market share',
      'Firms produce identical products',
    ],
    answer: 0,
    explanation: 'Contestability depends on the threat of entry, not the current number of firms - which is why even a monopoly can be contestable.',
    topic: 'Contestability',
  },
  {
    question: 'An incumbent firm sets price just low enough to deter new entrants. This is called:',
    options: ['Limit pricing', 'Price discrimination', 'Predatory pricing', 'Cost-plus pricing'],
    answer: 0,
    explanation: 'Limit pricing sacrifices some short-run profit to keep rivals out. Predatory pricing goes further, pricing below cost to drive existing rivals out.',
    topic: 'Contestability',
  },
  {
    question: 'Why do high sunk costs reduce the contestability of a market?',
    options: [
      'They make exit costly, so hit-and-run entry is not viable',
      'They raise the price consumers pay',
      'They increase the number of firms in the market',
      'They reduce economies of scale',
    ],
    answer: 0,
    explanation: 'Sunk costs cannot be recovered on exit, so entering becomes a risky one-way bet and the threat of hit-and-run competition disappears.',
    topic: 'Contestability',
  },
  {
    question: 'Which best describes vertical equity?',
    options: [
      'Those with a greater ability to pay contribute proportionately more',
      'Everyone receives an identical income',
      'People in identical circumstances are treated identically',
      'All taxes are set at the same percentage rate',
    ],
    answer: 0,
    explanation: 'Vertical equity means treating unequal cases differently according to ability to pay - the principle behind progressive taxation.',
    topic: 'Government Intervention and Equity',
  },
  {
    question: 'A poverty trap occurs when:',
    options: [
      'Earning more leads to benefit withdrawal and tax, leaving little net gain',
      'The minimum wage is set below the equilibrium wage',
      'Inflation erodes the value of benefits',
      'Unemployment benefits are abolished',
    ],
    answer: 0,
    explanation: 'When benefit withdrawal combines with income tax, the effective marginal rate on extra earnings can approach or exceed 100%, removing the incentive to work more.',
    topic: 'Government Intervention and Equity',
  },
  {
    question: 'Which policy is most likely to reduce inequality of opportunity in the long run?',
    options: [
      'Free access to high-quality education for all children',
      'A one-off cash transfer to low-income households',
      'A cut in the rate of VAT',
      'An increase in the state pension',
    ],
    answer: 0,
    explanation: 'Education raises human capital and social mobility, addressing the cause of inequality; the others raise current incomes without changing future earning potential.',
    topic: 'Government Intervention and Equity',
  },
  {
    question: 'Which correctly describes a customs union?',
    options: [
      'Free trade between members plus a common external tariff',
      'Free trade between members with independent external tariffs',
      'Free movement of labour and capital between members',
      'A shared currency and central bank',
    ],
    answer: 0,
    explanation: 'A common external tariff is what distinguishes a customs union from a free trade area. Free movement of factors defines a single market.',
    topic: 'Trading Blocs and the WTO',
  },
  {
    question: 'Trade diversion occurs when joining a customs union causes:',
    options: [
      'Cheaper non-member imports to be replaced by dearer member imports',
      'High-cost domestic production to be replaced by cheaper member imports',
      'Total trade between members to increase',
      'A country to leave the WTO',
    ],
    answer: 0,
    explanation: 'The common external tariff can make a genuinely lower-cost non-member supplier more expensive than a member, reducing welfare.',
    topic: 'Trading Blocs and the WTO',
  },
  {
    question: 'A principal role of the WTO is to:',
    options: [
      'Resolve trade disputes and promote reductions in trade barriers',
      'Set exchange rates between member currencies',
      'Lend to countries facing balance of payments crises',
      'Provide development aid to low-income countries',
    ],
    answer: 0,
    explanation: 'The WTO administers trade rules and adjudicates disputes. Balance of payments lending is the IMF, and development finance the World Bank.',
    topic: 'Trading Blocs and the WTO',
  },
  {
    question: 'Which is a limitation of using the Human Development Index?',
    options: [
      'It is a national average that hides inequality within a country',
      'It only measures income',
      'It cannot be compared between countries',
      'It ignores life expectancy',
    ],
    answer: 0,
    explanation: 'HDI does combine health, education and income, but as a single average it conceals internal inequality and omits political freedom and environmental quality.',
    topic: 'Measures and Strategies for Development',
  },
  {
    question: 'The Harrod-Domar model suggests development is constrained primarily by:',
    options: [
      'A low level of domestic saving limiting investment',
      'A shortage of natural resources',
      'Excessive government spending',
      'An overvalued exchange rate',
    ],
    answer: 0,
    explanation: 'The model identifies the savings gap: low incomes mean low saving, so investment and hence growth are constrained - a case for FDI or aid.',
    topic: 'Measures and Strategies for Development',
  },
  {
    question: 'The "primary product dependency" problem refers to developing economies:',
    options: [
      'Relying on commodity exports whose prices are volatile',
      'Importing too many manufactured goods',
      'Having too large a service sector',
      'Depending on foreign aid for government revenue',
    ],
    answer: 0,
    explanation: 'Commodity prices are volatile because supply and demand are both price inelastic, making export earnings and government revenue unpredictable.',
    topic: 'Measures and Strategies for Development',
  },
  {
    question: 'Which is NOT a function of financial markets?',
    options: [
      'Setting the rate of income tax',
      'Facilitating saving',
      'Allocating capital between competing uses',
      'Providing forward markets so firms can hedge risk',
    ],
    answer: 0,
    explanation: 'Taxation is a function of government, not of financial markets. The other three are core roles of the financial system.',
    topic: 'The Role of Financial Markets',
  },
  {
    question: 'Moral hazard in banking refers to:',
    options: [
      'Banks taking greater risks because they expect to be bailed out',
      'Borrowers concealing their true creditworthiness before a loan',
      'Banks refusing to lend to risky borrowers',
      'Customers withdrawing deposits during a panic',
    ],
    answer: 0,
    explanation: 'Moral hazard arises after the agreement, when the party protected from consequences takes more risk. Concealment beforehand is adverse selection.',
    topic: 'The Role of Financial Markets',
  },
  {
    question: 'A speculative bubble in an asset market occurs when:',
    options: [
      'Prices rise far above fundamental value because buyers expect further rises',
      'Prices fall below the cost of production',
      'A central bank cuts interest rates',
      'The government imposes a transactions tax',
    ],
    answer: 0,
    explanation: 'Self-reinforcing expectations drive prices away from underlying value, until the expectation reverses and the bubble bursts.',
    topic: 'The Role of Financial Markets',
  },
  {
    question: 'A central bank acting as "lender of last resort" means it:',
    options: [
      'Provides liquidity to solvent banks facing a run',
      'Lends to any bank regardless of solvency',
      'Provides mortgages directly to households',
      'Guarantees the profits of commercial banks',
    ],
    answer: 0,
    explanation: 'Because banks borrow short and lend long, even a solvent bank can fail a run - so the central bank supplies liquidity to prevent contagion.',
    topic: 'Central Banks and Financial Regulation',
  },
  {
    question: 'Requiring banks to hold a minimum ratio of capital to risk-weighted assets is an example of:',
    options: [
      'Macroprudential regulation',
      'Monetary policy',
      'Fiscal policy',
      'Supply-side policy',
    ],
    answer: 0,
    explanation: 'Capital requirements are prudential rules designed to make individual banks and the system as a whole resilient to losses.',
    topic: 'Central Banks and Financial Regulation',
  },
  {
    question: 'The primary objective of the Bank of England’s Monetary Policy Committee is to:',
    options: [
      'Meet the government’s inflation target of 2% CPI',
      'Maximise economic growth',
      'Minimise the budget deficit',
      'Maintain a fixed exchange rate',
    ],
    answer: 0,
    explanation: 'The MPC has a primary inflation target of 2% CPI; supporting growth and employment is a secondary objective, subject to meeting that target.',
    topic: 'Central Banks and Financial Regulation',
  },
  {
    question: 'The national debt differs from the budget deficit because the debt is:',
    options: [
      'A stock accumulated over time, while the deficit is an annual flow',
      'An annual flow, while the deficit is a stock',
      'Always smaller than the deficit',
      'Owed only to foreign creditors',
    ],
    answer: 0,
    explanation: 'Each year of deficit adds to the accumulated stock of debt, which is why the debt can still rise while the deficit is falling.',
    topic: 'The National Debt',
  },
  {
    question: 'The debt-to-GDP ratio can fall without any repayment of debt if:',
    options: [
      'Nominal GDP grows faster than the debt',
      'Interest rates rise sharply',
      'The government runs a larger deficit',
      'Inflation falls to zero',
    ],
    answer: 0,
    explanation: 'The ratio is debt divided by GDP, so faster growth in the denominator reduces it even when the stock of debt is unchanged.',
    topic: 'The National Debt',
  },
  {
    question: 'Which is the strongest argument that a high national debt need not be damaging?',
    options: [
      'If borrowing funds capital investment, it raises future capacity to repay',
      'Debt interest is always paid to foreign creditors',
      'Governments can never default on debt',
      'Debt automatically disappears with inflation',
    ],
    answer: 0,
    explanation: 'Borrowing to invest raises future output and tax revenue, so it can pay for itself - unlike borrowing to fund current consumption.',
    topic: 'The National Debt',
  },
]
