/*
  Extra Edexcel A-level Economics A exam questions - Themes 3 and 4.
  Companion to econ-exam-2.js; same conventions (marking points, then a
  "Final answer:" line to self-mark a whole answer against).
*/
export const ECON_EXAM_3 = [
  // =========================================================== THEME 3
  {
    question: 'Explain the difference between organic and inorganic growth, and give one advantage of each.',
    marks: 6,
    markScheme: [
      'Organic (internal) growth: expanding by increasing output, opening new outlets, or entering new markets using the firm’s own resources',
      'Advantage: lower risk, financed from retained profit, keeps the existing management culture intact',
      'Inorganic (external) growth: expanding through merger or takeover',
      'Advantage: much faster, immediately acquires market share, brands, and expertise',
      'Final answer: Organic growth expands the firm using its own resources, which is slower but lower risk and preserves company culture; inorganic growth via merger or takeover is far faster and buys market share and expertise immediately.',
    ],
    topic: 'Business Growth',
  },
  {
    question: 'Analyse the reasons why some firms choose to remain small.',
    marks: 8,
    markScheme: [
      'Size of the market: a niche market cannot support a large firm',
      'Diseconomies of scale: coordination and communication problems can raise unit costs beyond a point',
      'Personal or lifestyle objectives of the owner rather than profit maximisation',
      'Ability to offer a personalised, flexible service that large firms cannot replicate',
      'Barriers to growth: lack of access to finance, particularly for young firms without collateral',
      'Regulatory thresholds and monopoly regulation that apply above a certain size',
      'Final answer: Firms stay small when the market itself is small or niche, when growth would bring diseconomies of scale, when owners have non-profit objectives, or simply because they cannot raise the finance to expand.',
    ],
    topic: 'Business Growth',
  },
  {
    question: 'Explain two reasons why a firm might choose to demerge.',
    marks: 4,
    markScheme: [
      'To escape diseconomies of scale - a smaller, more focused firm is easier to coordinate and control',
      'To focus on core competencies and sell divisions that distract management',
      'To raise cash by selling off a division, or to satisfy a competition authority ruling',
      'Because the parts may be worth more separately than combined (removing a conglomerate discount)',
      'Final answer: Firms demerge to escape diseconomies of scale and refocus on core activities, and because separate businesses are often valued more highly by the market than a sprawling conglomerate - as well as to comply with competition rulings.',
    ],
    topic: 'Demergers',
  },
  {
    question: 'Analyse the impact of a demerger on the workers and consumers of the businesses involved.',
    marks: 8,
    markScheme: [
      'Workers: risk of redundancy as duplicated head-office functions are removed',
      'Workers: potentially better morale and clearer promotion paths in a smaller, focused firm',
      'Consumers: more competition between the separated firms may lower prices and raise choice',
      'Consumers: loss of economies of scale may raise unit costs and therefore prices',
      'Depends on whether the separated firms compete with each other or serve distinct markets',
      'Final answer: Workers may face redundancy where functions are duplicated but can benefit from clearer focus and progression; consumers gain if the split increases competition, but lose if the loss of scale economies pushes unit costs and prices up.',
    ],
    topic: 'Demergers',
  },
  {
    question: 'Explain, using a diagram, the difference between profit maximisation and revenue maximisation for a firm.',
    marks: 6,
    markScheme: [
      'Profit maximisation occurs where MC = MR',
      'Revenue maximisation occurs where MR = 0, which is further along the demand curve',
      'Diagram: MC, MR and AR curves, with the two output levels marked',
      'Revenue maximisation therefore gives a higher output and a lower price than profit maximisation',
      'Firms may revenue maximise to gain market share, or because managers’ pay is linked to sales',
      'Final answer: Profit is maximised where MC = MR; revenue is maximised where MR = 0, which lies at a higher output and lower price. A firm pursuing market share or whose managers are rewarded on sales will produce at the revenue-maximising point.',
    ],
    topic: 'Business Objectives',
  },
  {
    question: 'Explain what is meant by the principal-agent problem and how it affects a firm’s objectives.',
    marks: 4,
    markScheme: [
      'The principals (shareholders) own the firm; the agents (managers) run it day to day',
      'Their objectives diverge: shareholders want profit maximisation, managers may want growth, prestige or an easy life',
      'Asymmetric information means shareholders cannot fully monitor managers',
      'Result: divorce of ownership from control, so the firm may satisfice or sales maximise rather than profit maximise',
      'Final answer: Shareholders own the firm but managers control it, and because shareholders cannot fully monitor managers, managers can pursue their own goals - growth, prestige or a quiet life - so the firm may satisfice rather than maximise profit.',
    ],
    topic: 'Business Objectives',
  },
  {
    question: 'Explain the difference between normal profit and supernormal profit, and state the significance of each.',
    marks: 4,
    markScheme: [
      'Normal profit is the minimum return needed to keep the firm in the industry - it is an economic cost',
      'It occurs where AR = AC (total revenue equals total cost including opportunity cost)',
      'Supernormal profit is any return above normal profit, where AR > AC',
      'Supernormal profit attracts new entrants in the long run unless barriers to entry exist',
      'Final answer: Normal profit is the minimum needed to keep resources in their current use and counts as a cost; supernormal profit is anything above that, and it acts as the signal that draws new firms into the industry unless barriers to entry prevent it.',
    ],
    topic: 'Revenue, Costs and Profit',
  },
  {
    question: 'Explain, using the law of diminishing marginal returns, why the marginal cost curve is U-shaped in the short run.',
    marks: 6,
    markScheme: [
      'In the short run at least one factor (usually capital) is fixed',
      'Initially, adding variable factors to fixed capital raises marginal product - specialisation improves',
      'Rising marginal product means each extra unit costs less to make, so MC falls',
      'Beyond a point, the fixed factor becomes a constraint and marginal product falls - diminishing returns',
      'Falling marginal product means each extra unit costs more, so MC rises',
      'Final answer: MC is the mirror image of marginal product. While marginal product rises through specialisation MC falls; once the fixed factor becomes a constraint, diminishing marginal returns set in, marginal product falls and MC rises - giving the U shape.',
    ],
    topic: 'Revenue, Costs and Profit',
  },
  {
    question: 'Analyse three internal economies of scale a large supermarket chain might experience.',
    marks: 8,
    markScheme: [
      'Purchasing (bulk-buying) economies: buying in huge volume secures large discounts from suppliers',
      'Technical economies: investment in automated distribution centres is only viable at high volume, lowering unit cost',
      'Managerial economies: employing specialists in logistics, marketing and law spreads their cost over more output',
      'Financial economies: large firms borrow at lower interest rates because they are lower risk and have collateral',
      'Risk-bearing economies: a wide product range and many locations diversifies risk',
      'All reduce long-run average cost as output rises',
      'Final answer: A supermarket chain gains purchasing economies through bulk discounts, technical economies from automated distribution only viable at scale, and managerial economies from specialist staff whose cost is spread over far more output - all lowering long-run average cost.',
    ],
    topic: 'Economies and Diseconomies of Scale',
  },
  {
    question: 'Explain what is meant by the minimum efficient scale and why it matters for market structure.',
    marks: 4,
    markScheme: [
      'MES is the lowest level of output at which long-run average cost is minimised',
      'If MES is large relative to market demand, only a few firms can operate efficiently',
      'This produces a concentrated market - oligopoly or natural monopoly',
      'If MES is small relative to the market, many firms can compete efficiently, favouring competitive structures',
      'Final answer: MES is the smallest output at which LRAC is minimised. When MES is large relative to total market demand only a few firms can be efficient, so the market naturally becomes concentrated; when MES is small, many firms can compete on equal cost terms.',
    ],
    topic: 'Economies and Diseconomies of Scale',
  },
  {
    question: 'Explain, using a diagram, why a firm in perfect competition earns only normal profit in the long run.',
    marks: 6,
    markScheme: [
      'Diagram: short run with AR above AC at the profit-maximising output, showing supernormal profit',
      'Supernormal profit attracts new entrants because there are no barriers to entry',
      'Industry supply shifts right, so market price falls',
      'The firm’s horizontal AR = MR curve shifts down until it is tangential to AC',
      'At this point AR = AC, so only normal profit is earned and entry stops',
      'Final answer: Supernormal profits attract entry because barriers are absent; entry raises industry supply and lowers price until the firm’s AR curve is tangent to its AC curve. At that point only normal profit remains, so entry ceases and the long-run equilibrium is stable.',
    ],
    topic: 'Perfect Competition',
  },
  {
    question: 'Explain why perfect competition is allocatively and productively efficient in the long run.',
    marks: 4,
    markScheme: [
      'Productive efficiency: the firm produces at the minimum point of the AC curve, where AC is lowest',
      'This follows from the long-run tangency of AR and AC',
      'Allocative efficiency: price equals marginal cost (P = MC), because AR = MR = MC in equilibrium',
      'P = MC means the value consumers place on the last unit equals its cost of production',
      'Final answer: In long-run equilibrium the firm produces at the minimum of AC, achieving productive efficiency, and because AR = MR = MC the price equals marginal cost, achieving allocative efficiency - so resources are allocated exactly as consumers value them.',
    ],
    topic: 'Perfect Competition',
  },
  {
    question: 'Explain three characteristics of monopolistic competition and give an example of such a market.',
    marks: 6,
    markScheme: [
      'A large number of relatively small firms, each with a small market share',
      'Product differentiation - goods are similar but not identical, giving each firm some price-setting power',
      'Low barriers to entry and exit, so supernormal profit is competed away in the long run',
      'Downward-sloping but highly elastic demand curve for each firm',
      'Example: hairdressers, restaurants, plumbers, coffee shops',
      'Final answer: Monopolistic competition has many small firms, differentiated products giving each limited price-setting power, and low barriers to entry so only normal profit is earned in the long run - restaurants and hairdressers are typical examples.',
    ],
    topic: 'Monopolistic Competition',
  },
  {
    question: 'Explain why a firm in monopolistic competition is not productively efficient in the long run.',
    marks: 4,
    markScheme: [
      'The firm faces a downward-sloping demand curve because its product is differentiated',
      'In long-run equilibrium AR is tangential to AC, but tangency occurs on the falling part of the AC curve',
      'It therefore produces below the minimum of AC - excess capacity',
      'Productive efficiency requires production at the lowest point of AC, which is never reached',
      'Final answer: Because the firm’s demand curve slopes downwards, the long-run tangency of AR and AC occurs on the downward-sloping part of AC, not its minimum. The firm therefore operates with excess capacity and is productively inefficient.',
    ],
    topic: 'Monopolistic Competition',
  },
  {
    question: 'Analyse, using the kinked demand curve model, why prices tend to be stable in an oligopoly.',
    marks: 8,
    markScheme: [
      'Assumption: rivals match a price cut but do not follow a price rise',
      'Above the current price, demand is elastic - raising price loses many customers to rivals who hold price',
      'Below the current price, demand is inelastic - rivals match, so little market share is gained',
      'The demand curve is therefore kinked at the current price',
      'This produces a discontinuity (vertical section) in the MR curve',
      'MC can change anywhere within that discontinuity without altering the profit-maximising price - so price is sticky',
      'Final answer: Because rivals match price cuts but not price rises, each firm’s demand curve is kinked at the ruling price, creating a gap in the MR curve. Marginal cost can shift within that gap without changing the profit-maximising output, so prices remain stable even when costs move.',
    ],
    topic: 'Oligopoly',
  },
  {
    question: 'Evaluate the view that collusion in an oligopolistic market is always against the consumer interest.',
    marks: 12,
    markScheme: [
      'Overt collusion (a cartel) restricts output and raises price towards the monopoly level',
      'Consumer surplus falls and is transferred to producers; deadweight welfare loss arises',
      'Reduced incentive for dynamic efficiency and innovation when profits are secure',
      'Evaluation: tacit collusion may produce price stability, which helps consumers and firms plan',
      'Evaluation: supernormal profits may fund R&D, giving dynamic efficiency gains passed on later',
      'Evaluation: collusion is inherently unstable - each firm has an incentive to cheat and undercut (game theory / prisoner’s dilemma)',
      'Evaluation: contestable markets and competition authorities limit the damage',
      'Final answer: Collusion generally harms consumers by restricting output, raising price and transferring surplus to producers. But the harm is not automatic - price stability has value, retained profits can fund innovation, and cartels are unstable because each member gains by cheating, so the outcome depends heavily on the strength of competition policy.',
    ],
    topic: 'Oligopoly',
  },
  {
    question: 'Explain, using a diagram, why a monopoly is allocatively inefficient.',
    marks: 6,
    markScheme: [
      'Diagram: downward-sloping AR with MR below it, MC cutting MR at the profit-maximising output',
      'The monopolist produces where MC = MR, at output Qm',
      'Price is read off the AR curve at Pm, which is above MC',
      'Allocative efficiency requires P = MC; here P > MC',
      'The value consumers place on extra units exceeds the cost of producing them, so output is too low',
      'Deadweight welfare loss triangle between the competitive and monopoly output',
      'Final answer: A monopolist sets output where MC = MR but charges the higher price shown on the AR curve, so P > MC. Consumers value additional units more than they cost to produce, but those units are not made - creating a deadweight welfare loss.',
    ],
    topic: 'Monopoly',
  },
  {
    question: 'Explain two conditions necessary for successful price discrimination.',
    marks: 4,
    markScheme: [
      'The firm must have price-setting power (not a price taker)',
      'It must be able to identify and separate groups with different price elasticities of demand',
      'It must be able to prevent resale (market seepage) between the groups',
      'The cost of separating the markets must be less than the extra revenue gained',
      'Final answer: The firm needs price-setting power and must be able to separate consumers into groups with different price elasticities - charging the inelastic group more - while preventing resale between those groups.',
    ],
    topic: 'Monopoly',
  },
  {
    question: 'Explain what is meant by a contestable market and why the threat of entry affects incumbent behaviour.',
    marks: 6,
    markScheme: [
      'A contestable market has low barriers to entry and exit, and low sunk costs',
      'Firms can "hit and run": enter to capture supernormal profit, then leave without loss',
      'Incumbents therefore cannot sustain high prices even if concentration is high',
      'They may set limit prices - just below the level that would attract entry - accepting lower profit to deter rivals',
      'So the number of firms matters less than the ease of entry',
      'Final answer: In a contestable market low sunk costs allow hit-and-run entry, so incumbents cannot exploit their market share. They set prices near the entry-deterring level, meaning market performance is determined by the threat of competition rather than the actual number of firms.',
    ],
    topic: 'Contestability',
  },
  {
    question: 'Explain the significance of sunk costs for the contestability of a market.',
    marks: 4,
    markScheme: [
      'Sunk costs are costs that cannot be recovered on exit, e.g. bespoke machinery or advertising spend',
      'High sunk costs make exit expensive, so entry is risky and hit-and-run entry is impossible',
      'This reduces contestability and allows incumbents to sustain supernormal profit',
      'Low sunk costs (e.g. leased aircraft) make a market highly contestable',
      'Final answer: Sunk costs cannot be recovered on exit, so high sunk costs make entry risky and prevent hit-and-run competition, reducing contestability. Where assets can be leased or resold, exit is cheap and the market is highly contestable.',
    ],
    topic: 'Contestability',
  },
  {
    question: 'Explain why the demand for labour is described as a derived demand.',
    marks: 4,
    markScheme: [
      'Labour is not demanded for its own sake but for the output it produces',
      'Demand for labour therefore depends on demand for the final product',
      'A rise in demand for houses raises demand for bricklayers; a fall in demand for coal reduces demand for miners',
      'Firms demand labour up to the point where the marginal revenue product equals the wage',
      'Final answer: Firms do not want labour for itself but for what it produces, so demand for any type of labour derives from demand for the good it makes - which is why falling demand for coal reduces demand for miners.',
    ],
    topic: 'Wage Determination',
  },
  {
    question: 'Analyse, using a diagram, the effect of a large increase in the national minimum wage in a competitive labour market.',
    marks: 8,
    markScheme: [
      'Diagram: labour demand and supply, with a minimum wage line above the equilibrium wage',
      'At the higher wage, quantity of labour supplied exceeds quantity demanded',
      'This excess supply is unemployment in that labour market',
      'Those who keep their jobs gain higher incomes, reducing in-work poverty and raising consumption',
      'Size of the effect depends on the elasticity of demand for labour - inelastic demand means little job loss',
      'Evaluation point: in a monopsony labour market a minimum wage can raise both wages and employment',
      'Final answer: Above equilibrium, a minimum wage creates excess supply of labour - unemployment - though those keeping their jobs gain. The scale of job losses depends on how elastic labour demand is, and in a monopsonistic market a minimum wage can actually raise employment.',
    ],
    topic: 'Wage Determination',
  },
  {
    question: 'Explain two reasons why wage differentials exist between occupations.',
    marks: 4,
    markScheme: [
      'Differences in marginal revenue product: more productive workers generate more revenue and command higher wages',
      'Differences in the elasticity of labour supply: jobs requiring long training have inelastic supply, raising wages',
      'Compensating differentials for unpleasant, dangerous or unsocial work',
      'Non-competing groups: barriers such as qualifications prevent workers moving between markets',
      'Final answer: Wages differ because workers have different marginal revenue products, and because occupations needing long training have inelastic labour supply so wages must be higher to attract entrants - with compensating differentials paid for unpleasant or dangerous work.',
    ],
    topic: 'Labour Market Issues',
  },
  {
    question: 'Explain what is meant by monopsony in a labour market and its effect on wages and employment.',
    marks: 6,
    markScheme: [
      'A monopsony is a single (or dominant) buyer of labour, e.g. the NHS for nurses',
      'To hire an extra worker it must raise the wage for all workers, so marginal cost of labour exceeds the wage',
      'It employs where MCL = MRP, then pays the wage on the supply curve at that quantity',
      'Result: both wages and employment are lower than in a competitive labour market',
      'This is why a minimum wage or trade union can raise wages and employment simultaneously here',
      'Final answer: A monopsonist faces a marginal cost of labour above the wage, so it hires fewer workers and pays less than a competitive market would. This is why imposing a minimum wage in a monopsonistic market can raise wages and employment at the same time.',
    ],
    topic: 'Labour Market Issues',
  },
  {
    question: 'Evaluate the view that government intervention is the most effective way to reduce income inequality.',
    marks: 12,
    markScheme: [
      'Progressive taxation redistributes from high to low earners, reducing the Gini coefficient',
      'Transfer payments and benefits raise the incomes of the poorest directly',
      'A national minimum or living wage raises the wage floor',
      'State provision of education and healthcare improves equality of opportunity and long-run mobility',
      'Evaluation: high marginal tax rates may reduce work incentives and encourage avoidance or emigration',
      'Evaluation: benefits can create a poverty/unemployment trap where extra earnings are heavily withdrawn',
      'Evaluation: education improves mobility but only over decades',
      'Evaluation: some inequality is needed as an incentive to work, train and take risks',
      'Final answer: Government intervention through progressive tax, transfers and public services is the most direct route to lower inequality, and education is the most durable. But high tax rates and steep benefit withdrawal can blunt incentives, and some inequality is needed to reward effort and risk - so the policy mix and its design matter more than the amount of intervention.',
    ],
    topic: 'Government Intervention and Equity',
  },
  {
    question: 'Explain the difference between equity and equality, and between horizontal and vertical equity.',
    marks: 4,
    markScheme: [
      'Equality means everyone receiving the same; equity means fairness, which may require unequal treatment',
      'Horizontal equity: treating those in identical circumstances identically, e.g. two people on the same income paying the same tax',
      'Vertical equity: treating those in different circumstances differently, e.g. higher earners paying a higher tax rate',
      'A progressive tax system is designed to achieve vertical equity',
      'Final answer: Equality is sameness, equity is fairness - and fairness may require treating people differently. Horizontal equity means identical treatment of identical cases; vertical equity means higher earners contribute proportionately more, which is the basis of progressive taxation.',
    ],
    topic: 'Government Intervention and Equity',
  },

  // =========================================================== THEME 4
  {
    question: 'Explain, using the principle of comparative advantage, why two countries can both gain from trade even when one is more efficient at producing everything.',
    marks: 6,
    markScheme: [
      'Absolute advantage: producing more of a good with the same resources',
      'Comparative advantage: producing a good at a lower opportunity cost than the other country',
      'Even if country A has absolute advantage in both goods, its opportunity costs will differ between them',
      'Each country specialises where its opportunity cost is lower, then trades',
      'Total world output rises, so both can consume beyond their own PPF',
      'Final answer: Gains come from differences in opportunity cost, not absolute efficiency. Even a country better at producing everything gives up less of one good to make the other, so both specialise by comparative advantage, world output rises, and both consume beyond their own PPF.',
    ],
    topic: 'International Trade',
  },
  {
    question: 'Analyse two limitations of the theory of comparative advantage as a guide to trade policy.',
    marks: 8,
    markScheme: [
      'Assumes no transport costs; in reality these can exceed the cost advantage from specialising',
      'Assumes perfect factor mobility; workers displaced by imports often cannot move to the export sector - structural unemployment',
      'Assumes constant returns to scale, ignoring economies of scale that can create advantage rather than reflect it',
      'Ignores the risk of over-specialisation: dependence on one commodity leaves an economy exposed to price shocks',
      'Assumes free trade with no tariffs, and ignores externalities from transport emissions',
      'Final answer: The theory assumes zero transport costs and perfectly mobile factors, neither of which holds - so gains can be wiped out by shipping costs, and displaced workers become structurally unemployed rather than moving into exports. It also ignores the risk of over-specialising in a single volatile commodity.',
    ],
    topic: 'International Trade',
  },
  {
    question: 'Explain the difference between a customs union and a single market.',
    marks: 4,
    markScheme: [
      'A customs union has free trade between members plus a common external tariff on non-members',
      'A single market goes further: it also allows free movement of labour, capital, goods and services',
      'A single market harmonises regulations and standards to remove non-tariff barriers',
      'The EU is a single market; Mercosur is closer to a customs union',
      'Final answer: A customs union combines internal free trade with a common external tariff; a single market adds free movement of labour and capital and harmonises regulation to remove non-tariff barriers as well.',
    ],
    topic: 'Trading Blocs and the WTO',
  },
  {
    question: 'Explain what is meant by trade creation and trade diversion when a country joins a customs union.',
    marks: 4,
    markScheme: [
      'Trade creation: high-cost domestic production is replaced by lower-cost imports from a member country - welfare rises',
      'Trade diversion: low-cost imports from a non-member are replaced by higher-cost imports from a member, because of the common external tariff - welfare falls',
      'The net welfare effect depends on which dominates',
      'Final answer: Trade creation replaces expensive domestic output with cheaper output from within the bloc, raising welfare; trade diversion replaces genuinely cheaper non-member imports with dearer member imports because of the external tariff, lowering it. The net effect depends on which is larger.',
    ],
    topic: 'Trading Blocs and the WTO',
  },
  {
    question: 'Explain the difference between the current account, the capital account and the financial account of the balance of payments.',
    marks: 6,
    markScheme: [
      'Current account: trade in goods and services, primary income (investment income, wages) and secondary income (transfers)',
      'Capital account: relatively small - capital transfers and the acquisition of non-produced, non-financial assets',
      'Financial account: transactions in financial assets - FDI, portfolio investment, reserve assets',
      'The accounts must sum to zero: a current account deficit is financed by a financial account surplus',
      'Final answer: The current account records trade, income and transfers; the capital account records capital transfers and non-produced assets; the financial account records flows of financial assets such as FDI. They must balance, so a current account deficit is matched by a financial account surplus.',
    ],
    topic: 'The Balance of Payments',
  },
  {
    question: 'Analyse two policies a government could use to reduce a persistent current account deficit.',
    marks: 8,
    markScheme: [
      'Expenditure-reducing: deflationary fiscal or monetary policy lowers AD and therefore import demand',
      'Effective but at the cost of lower growth and higher unemployment',
      'Expenditure-switching: allowing or engineering a depreciation makes exports cheaper and imports dearer',
      'Success requires the Marshall-Lerner condition (PEDx + PEDm > 1) and takes time (J-curve)',
      'Supply-side policies raise long-run competitiveness through productivity - the durable solution but very slow',
      'Final answer: Expenditure-reducing policy cuts import demand by lowering AD but sacrifices growth and jobs; expenditure-switching via depreciation improves the deficit only if the Marshall-Lerner condition holds and after the J-curve lag. Supply-side improvements in productivity are the only durable fix, but act over years.',
    ],
    topic: 'The Balance of Payments',
  },
  {
    question: 'Explain the J-curve effect following a depreciation of a country’s currency.',
    marks: 6,
    markScheme: [
      'Immediately after depreciation, import prices rise and export prices fall in foreign currency',
      'In the short run demand is price inelastic - contracts are fixed and consumers take time to switch',
      'So the value of imports rises while export volumes have not yet increased: the current account worsens first',
      'Over time demand becomes more elastic as buyers switch, so export volumes rise and import volumes fall',
      'The current account then improves, tracing a J shape over time',
      'Improvement requires the Marshall-Lerner condition to be satisfied eventually',
      'Final answer: Because demand is price inelastic in the short run, a depreciation initially raises the import bill faster than export volumes can respond, worsening the current account. As demand becomes more elastic over time the balance improves, giving the characteristic J shape.',
    ],
    topic: 'Exchange Rates',
  },
  {
    question: 'Explain two factors that would cause an appreciation of a floating exchange rate.',
    marks: 4,
    markScheme: [
      'A rise in domestic interest rates relative to abroad attracts hot money inflows, raising demand for the currency',
      'An improvement in the current account raises demand for the currency to buy exports',
      'Speculation that the currency will rise becomes self-fulfilling as traders buy',
      'Inward FDI raises demand for the currency',
      'Final answer: Higher relative interest rates attract short-term capital inflows and increased demand for the country’s exports both raise demand for its currency on the foreign exchange market, causing it to appreciate.',
    ],
    topic: 'Exchange Rates',
  },
  {
    question: 'Explain the difference between absolute and relative poverty, and state one measure of each.',
    marks: 4,
    markScheme: [
      'Absolute poverty: income below a fixed subsistence level, measured against a constant real standard',
      'Measure: the World Bank international poverty line ($2.15 a day, 2017 PPP)',
      'Relative poverty: income below a proportion of the national median, so it depends on the distribution',
      'Measure: households below 60% of median income after housing costs',
      'Relative poverty can persist even as everyone becomes better off',
      'Final answer: Absolute poverty is a fixed subsistence threshold, measured by lines like the World Bank’s $2.15 a day; relative poverty is defined against the national median (commonly 60% of it), so it measures inequality and can persist even as all incomes rise.',
    ],
    topic: 'Poverty and Inequality',
  },
  {
    question: 'Explain how a Lorenz curve and the Gini coefficient are used to measure income inequality.',
    marks: 6,
    markScheme: [
      'The Lorenz curve plots the cumulative share of income against the cumulative share of population',
      'The 45° line represents perfect equality',
      'The further the Lorenz curve bows away from the 45° line, the greater the inequality',
      'The Gini coefficient is the area between the line of equality and the Lorenz curve, divided by the total area beneath the line of equality',
      'It ranges from 0 (perfect equality) to 1 (one person has all income)',
      'Final answer: The Lorenz curve shows how far the actual income distribution deviates from the 45° line of perfect equality, and the Gini coefficient converts that gap into a single number between 0 and 1 - the larger the value, the more unequal the distribution.',
    ],
    topic: 'Poverty and Inequality',
  },
  {
    question: 'Evaluate the view that foreign direct investment is the most effective strategy for promoting economic development.',
    marks: 12,
    markScheme: [
      'FDI brings capital that domestic saving cannot finance, filling the savings gap',
      'Transfers technology and management expertise; creates employment and raises incomes',
      'Raises tax revenue and can improve the current account through export earnings',
      'Multiplier effects and linkages with domestic suppliers',
      'Evaluation: profits are repatriated, so gains may leave the country',
      'Evaluation: risk of exploitation of labour and weak environmental standards; "race to the bottom" in regulation',
      'Evaluation: MNCs may use transfer pricing to minimise tax paid locally',
      'Evaluation: alternatives - investment in human capital, microfinance, infrastructure, debt relief, or trade liberalisation may be more durable',
      'Final answer: FDI is powerful because it fills the savings gap and transfers technology and skills that a developing economy cannot generate alone. But the benefits leak away through profit repatriation and transfer pricing, and can come with poor labour and environmental standards - so FDI works best alongside investment in education and institutions, not instead of it.',
    ],
    topic: 'Measures and Strategies for Development',
  },
  {
    question: 'Explain what the Human Development Index measures and one limitation of using it.',
    marks: 4,
    markScheme: [
      'HDI combines three dimensions: health (life expectancy at birth), education (mean and expected years of schooling), and income (GNI per capita at PPP)',
      'Each is indexed 0-1 and combined into a single figure',
      'Limitation: it is an average, so it hides inequality within a country',
      'Limitation: it omits political freedom, environmental quality, gender equality and inequality',
      'Final answer: HDI combines life expectancy, schooling and GNI per capita into one 0-1 index, giving a broader picture than income alone. Its main limitation is that it is a national average that conceals internal inequality and ignores political freedom and environmental quality.',
    ],
    topic: 'Measures and Strategies for Development',
  },
  {
    question: 'Explain three functions of financial markets in an economy.',
    marks: 6,
    markScheme: [
      'To facilitate saving: providing households with a secure store of wealth that earns a return',
      'To lend to businesses and individuals: channelling savings into productive investment',
      'To allocate capital efficiently between competing uses via the interest rate',
      'To provide a payments mechanism, and to provide forward markets in currencies and commodities allowing firms to hedge risk',
      'To facilitate the exchange of goods and services',
      'Final answer: Financial markets allow households to save securely, channel those savings to firms and individuals who want to borrow, and allocate that capital between competing uses through the interest rate - while also providing payments systems and forward markets that let firms hedge risk.',
    ],
    topic: 'The Role of Financial Markets',
  },
  {
    question: 'Explain, using an example, what is meant by moral hazard in financial markets.',
    marks: 4,
    markScheme: [
      'Moral hazard is where a party takes greater risk because it does not bear the full consequences',
      'Example: banks judged "too big to fail" expect a government bailout, so lend more riskily than they otherwise would',
      'The downside is socialised while the upside is retained by shareholders and executives',
      'Contributed to the excessive risk-taking behind the 2008 financial crisis',
      'Final answer: Moral hazard is taking more risk because someone else bears the cost of failure. Banks believing they are too big to fail lend more riskily, keeping the profits while expecting taxpayers to absorb the losses - a key cause of the 2008 crisis.',
    ],
    topic: 'The Role of Financial Markets',
  },
  {
    question: 'Explain three functions of a central bank.',
    marks: 6,
    markScheme: [
      'Implementation of monetary policy: setting the policy interest rate to meet the inflation target, and conducting QE',
      'Banker to the government and to the commercial banks; manager of the national debt and foreign exchange reserves',
      'Lender of last resort: providing liquidity to solvent banks facing a run, maintaining financial stability',
      'Regulation and supervision of the financial system (macroprudential policy, e.g. capital requirements and stress tests)',
      'Final answer: A central bank sets interest rates to meet the inflation target, acts as banker to the government and the banking system, and serves as lender of last resort to solvent banks - alongside regulating the financial system to maintain stability.',
    ],
    topic: 'Central Banks and Financial Regulation',
  },
  {
    question: 'Explain why a central bank acts as lender of last resort.',
    marks: 4,
    markScheme: [
      'Banks borrow short and lend long, so they are illiquid even when solvent',
      'A loss of confidence can trigger a bank run that no solvent bank could survive alone',
      'A single failure can spread through interbank exposures - systemic risk / contagion',
      'By guaranteeing liquidity the central bank prevents the run starting, maintaining financial stability',
      'Final answer: Because banks borrow short and lend long, even a solvent bank cannot meet a sudden run, and one failure can spread through the system. Standing ready to lend prevents panics from starting, protecting the wider economy from contagion.',
    ],
    topic: 'Central Banks and Financial Regulation',
  },
  {
    question: 'Explain the difference between progressive, proportional and regressive taxes, with an example of each.',
    marks: 6,
    markScheme: [
      'Progressive: the average rate of tax rises as income rises, e.g. UK income tax with its rising bands',
      'Proportional: the average rate stays constant as income rises, e.g. a flat-rate income tax',
      'Regressive: the average rate falls as income rises, e.g. VAT, since poorer households spend a larger share of income',
      'Progressive taxes reduce inequality; regressive taxes widen it',
      'Final answer: A progressive tax takes a rising share of income as income rises (UK income tax), a proportional tax a constant share (a flat tax), and a regressive tax a falling share (VAT, because the poor spend more of their income) - so progressive taxes narrow inequality while regressive taxes widen it.',
    ],
    topic: 'Public Expenditure and Taxation',
  },
  {
    question: 'Analyse the possible economic effects of a significant increase in the higher rate of income tax.',
    marks: 8,
    markScheme: [
      'Raises tax revenue and can fund public services or reduce the deficit - but only if the economy is left of the Laffer curve peak',
      'Reduces post-tax income inequality, lowering the Gini coefficient',
      'Reduces disposable income of high earners, lowering consumption - though their MPC is low, so the AD effect is modest',
      'May reduce the incentive to work, or encourage avoidance, evasion and emigration of high earners',
      'Beyond the Laffer curve peak, a higher rate could actually reduce total revenue',
      'May discourage entrepreneurship and inward migration of skilled labour, harming LRAS',
      'Final answer: A higher top rate raises revenue and reduces inequality, with only a modest fall in AD since high earners have a low MPC. The risks are weaker work incentives, increased avoidance and emigration - and beyond the Laffer curve peak the rise would reduce total revenue.',
    ],
    topic: 'Public Expenditure and Taxation',
  },
  {
    question: 'Explain the difference between the budget deficit and the national debt.',
    marks: 4,
    markScheme: [
      'The budget deficit is a flow: the amount by which government spending exceeds revenue in a single year',
      'The national debt is a stock: the total accumulated amount the government owes',
      'Each year of deficit adds to the national debt',
      'The debt can rise even as the deficit falls, because a smaller deficit is still an addition to the stock',
      'Final answer: The deficit is an annual flow - one year’s excess of spending over revenue - while the national debt is the accumulated stock of what is owed. Reducing the deficit still adds to the debt; the debt only falls when the budget is in surplus.',
    ],
    topic: 'The National Debt',
  },
  {
    question: 'Evaluate the view that a high national debt is always damaging to an economy.',
    marks: 12,
    markScheme: [
      'Costs: debt interest payments are an opportunity cost, crowding out spending on public services',
      'Higher borrowing may raise interest rates, crowding out private investment',
      'Risk of a credit rating downgrade raising future borrowing costs',
      'Intergenerational burden if borrowing funds current consumption',
      'Evaluation: what matters is debt as a share of GDP and the interest rate relative to the growth rate - if g > r, debt/GDP falls without repayment',
      'Evaluation: borrowing to fund capital investment raises future productive capacity and can pay for itself',
      'Evaluation: much UK debt is held domestically and in sterling, so default risk is minimal',
      'Evaluation: austerity to cut debt quickly can reduce growth and raise the debt/GDP ratio (self-defeating)',
      'Final answer: High debt is damaging when it funds current consumption at interest rates above the growth rate, since debt interest crowds out public services. But debt used for capital investment can raise the capacity to repay, and when growth exceeds the interest rate the ratio falls without repayment - so the composition of the borrowing matters far more than its level.',
    ],
    topic: 'The National Debt',
  },
]
