/*
  AI-generated revision packs for additional subjects, merged into REVISION
  by library.js. Generated by the expand-revision-subjects workflow.
*/

export const EXTRA_REVISION = [
  {
    "id": "economics",
    "name": "Economics",
    "topics": [
      "Supply, Demand and Market Equilibrium",
      "Elasticity (PED, PES, YED, XED)",
      "Market Failure and Government Intervention",
      "Macroeconomic Objectives and Indicators",
      "Fiscal, Monetary and Supply-side Policy",
      "Competition and Market Structures",
      "International Trade and the Balance of Payments"
    ],
    "flashcards": [
      {
        "front": "State the law of demand and the law of supply.",
        "back": "The law of demand states that, all else equal, as the price of a good rises the quantity demanded falls, giving a downward-sloping demand curve. The law of supply states that as price rises the quantity supplied rises, giving an upward-sloping supply curve."
      },
      {
        "front": "Define price elasticity of demand (PED) and give its formula.",
        "back": "PED measures the responsiveness of quantity demanded to a change in price. It is calculated as the percentage change in quantity demanded divided by the percentage change in price; demand is elastic if the value is greater than 1 (ignoring the sign) and inelastic if less than 1."
      },
      {
        "front": "What is market failure? Give two examples.",
        "back": "Market failure occurs when the free market fails to allocate resources efficiently, leading to a loss of social welfare. Examples include negative externalities (such as pollution), public goods, information gaps, and monopoly power."
      },
      {
        "front": "Distinguish between fiscal policy and monetary policy.",
        "back": "Fiscal policy is the use of government spending and taxation to influence aggregate demand and the economy. Monetary policy is the use of interest rates and the money supply, controlled by the central bank (the Bank of England in the UK), to influence demand and inflation."
      },
      {
        "front": "Define the four main macroeconomic objectives.",
        "back": "Governments aim for economic growth (rising real GDP), low and stable inflation (the UK target is 2% CPI), low unemployment, and a stable balance of payments on the current account. A fairer distribution of income and sound public finances are often added."
      },
      {
        "front": "What is a negative externality and how can the government correct it?",
        "back": "A negative externality is a cost imposed on a third party not involved in a transaction, such as pollution, causing the social cost to exceed the private cost and over-production. Governments can correct it through indirect taxes, regulation, or tradable pollution permits to internalise the external cost."
      }
    ],
    "mcq": [
      {
        "question": "A good has a price elasticity of demand of -0.4. If its price rises, what happens to total revenue?",
        "options": [
          "Total revenue falls",
          "Total revenue rises",
          "Total revenue stays the same",
          "Total revenue falls to zero"
        ],
        "answer": 1,
        "explanation": "Demand is inelastic (less than 1), so a price rise reduces quantity by proportionally less, raising total revenue."
      },
      {
        "question": "Which of the following is the Bank of England's main tool of monetary policy?",
        "options": [
          "Income tax rates",
          "The Bank Rate (base interest rate)",
          "Government spending on the NHS",
          "Tariffs on imports"
        ],
        "answer": 1,
        "explanation": "The Bank of England influences the economy mainly by setting the Bank Rate, which affects borrowing and saving."
      },
      {
        "question": "A shift of the demand curve to the right is most likely caused by:",
        "options": [
          "A fall in the price of the good itself",
          "A rise in consumer incomes for a normal good",
          "An increase in the good's own production costs",
          "An improvement in production technology"
        ],
        "answer": 1,
        "explanation": "Higher incomes raise demand for a normal good at every price, shifting the demand curve rightwards; a change in the good's own price is a movement along the curve."
      },
      {
        "question": "Which best describes a public good?",
        "options": [
          "A good provided only by the government",
          "A good that is non-rival and non-excludable",
          "A good with no external costs",
          "A good that is always free to consumers"
        ],
        "answer": 1,
        "explanation": "Public goods are non-rival (one person's use does not reduce another's) and non-excludable (people cannot be prevented from using them), causing the free-rider problem."
      }
    ],
    "examQuestions": [
      {
        "question": "Explain, using a supply and demand diagram, how an increase in the price of a substitute good affects the market for a product.",
        "marks": 6,
        "markScheme": [
          "Define substitute goods (goods that can be used in place of one another)",
          "State that a rise in the price of the substitute makes the original good relatively cheaper/more attractive",
          "Explain that demand for the original good increases, shifting the demand curve to the right",
          "Reference to a correctly drawn/labelled diagram showing the rightward shift of demand",
          "Conclude that equilibrium price and quantity of the original good both rise"
        ]
      },
      {
        "question": "Analyse how the government can use indirect taxation to reduce the consumption of a demerit good such as cigarettes.",
        "marks": 9,
        "markScheme": [
          "Define a demerit good (over-consumed; more harmful than consumers realise) and negative externality",
          "Explain that an indirect tax raises the price and internalises the external cost",
          "Reference the tax shifting the supply curve upwards/leftwards, raising price and lowering quantity",
          "Note that effectiveness depends on price elasticity of demand (inelastic demand limits the fall in quantity)",
          "Evaluation: risks such as black markets, regressive impact on low-income consumers, or setting the tax at the wrong level"
        ]
      },
      {
        "question": "Evaluate the use of expansionary fiscal policy to reduce unemployment in an economy.",
        "marks": 12,
        "markScheme": [
          "Define expansionary fiscal policy (higher government spending and/or lower taxes) and unemployment",
          "Explain the transmission: higher aggregate demand raises output and derived demand for labour, cutting cyclical unemployment",
          "Use of the multiplier effect to strengthen the analysis",
          "Reference to an AD/AS diagram showing AD shifting right",
          "Evaluation of limitations: risk of demand-pull inflation, budget deficit and rising national debt, time lags",
          "Judgement: effectiveness depends on the type of unemployment (works for cyclical, not structural) and the amount of spare capacity in the economy"
        ]
      }
    ]
  },
  {
    "id": "geography",
    "name": "Geography",
    "topics": [
      "Tectonic hazards (plate boundaries, earthquakes and volcanoes)",
      "Weather, climate change and atmospheric systems",
      "Rivers and coastal landscapes and processes",
      "Ecosystems and the water and carbon cycles",
      "Urbanisation and changing cities",
      "Development, globalisation and the economic world",
      "Resource management (food, water and energy)"
    ],
    "flashcards": [
      {
        "front": "What are the four main types of plate boundary and what happens at each?",
        "back": "Constructive (divergent) boundaries pull apart, forming new crust and shield volcanoes. Destructive (convergent) boundaries push together, causing subduction, explosive volcanoes and violent earthquakes. Conservative (transform) boundaries slide past each other causing earthquakes but no volcanoes, and collision boundaries push continental crust up into fold mountains."
      },
      {
        "front": "Define the demographic transition model (DTM) and what happens to birth and death rates across its stages.",
        "back": "The DTM is a model showing how birth rates, death rates and total population change as a country develops through five stages. Death rates fall first (Stage 2) due to better healthcare, sanitation and food, then birth rates fall later (Stage 3 onward) as contraception, education and urbanisation reduce family size, so natural increase slows and eventually stabilises or declines."
      },
      {
        "front": "Explain the difference between hard and soft coastal engineering, with an example of each.",
        "back": "Hard engineering uses artificial structures to resist the sea, such as sea walls, groynes and rock armour, and is effective but expensive and can look unnatural. Soft engineering works with natural processes, such as beach nourishment and managed retreat, and is cheaper and more sustainable but often needs regular maintenance."
      },
      {
        "front": "What is the greenhouse effect and how do human activities enhance it?",
        "back": "The greenhouse effect is the natural trapping of outgoing long-wave radiation by gases such as carbon dioxide, methane and water vapour, keeping the Earth warm enough to support life. Human activities like burning fossil fuels, deforestation and farming release extra greenhouse gases, enhancing the effect and causing global warming and climate change."
      },
      {
        "front": "Describe the formation of a waterfall.",
        "back": "A waterfall forms where a river flows over a band of hard rock onto softer rock, which erodes faster through hydraulic action and abrasion, creating a step. Undercutting forms a plunge pool and an overhang of hard rock, which eventually collapses; repeated collapse makes the waterfall retreat upstream, leaving a steep-sided gorge."
      },
      {
        "front": "What is globalisation and what are two of its main causes?",
        "back": "Globalisation is the growing interconnection and interdependence of the world's economies, cultures and populations through trade, investment and technology. Key causes include improvements in transport and containerisation that cut freight costs, and advances in communication technology such as the internet, alongside the growth of transnational corporations (TNCs)."
      }
    ],
    "mcq": [
      {
        "question": "At which type of plate boundary would you most expect to find explosive volcanoes and deep ocean trenches?",
        "options": [
          "Constructive (divergent) boundary",
          "Destructive (convergent) boundary",
          "Conservative (transform) boundary",
          "Collision boundary"
        ],
        "answer": 1,
        "explanation": "At destructive boundaries oceanic crust subducts, forming trenches and viscous, gas-rich magma that produces explosive volcanoes."
      },
      {
        "question": "Which of the following is an example of soft engineering used to manage coastlines?",
        "options": [
          "Sea wall",
          "Rock armour (rip-rap)",
          "Beach nourishment",
          "Groynes"
        ],
        "answer": 2,
        "explanation": "Beach nourishment adds sand or shingle to work with natural processes, whereas sea walls, rock armour and groynes are hard engineering."
      },
      {
        "question": "In the demographic transition model, which stage is characterised by high birth rates but rapidly falling death rates and therefore rapid population growth?",
        "options": [
          "Stage 1",
          "Stage 2",
          "Stage 4",
          "Stage 5"
        ],
        "answer": 1,
        "explanation": "In Stage 2 death rates fall sharply due to improved healthcare and sanitation while birth rates stay high, causing rapid natural increase."
      },
      {
        "question": "Which greenhouse gas is most strongly associated with rice paddies, livestock and landfill sites?",
        "options": [
          "Carbon dioxide",
          "Methane",
          "Nitrogen",
          "Ozone"
        ],
        "answer": 1,
        "explanation": "Methane is released from waterlogged rice fields, cattle digestion and decomposing waste, and is a potent greenhouse gas."
      }
    ],
    "examQuestions": [
      {
        "question": "Using a named example, explain the primary and secondary effects of a tectonic hazard such as an earthquake. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Names a specific located example, e.g. the 2010 Haiti or 2011 Japan (Tohoku) earthquake, with a valid detail such as magnitude or date",
          "Identifies primary effects that happen immediately, e.g. buildings collapse, roads destroyed, people killed or injured",
          "Identifies secondary effects that follow on, e.g. fires, disease, tsunami, homelessness, loss of jobs or economic disruption",
          "Clearly distinguishes primary from secondary effects",
          "Uses place-specific facts or figures rather than only general statements"
        ]
      },
      {
        "question": "Assess the extent to which urbanisation brings both opportunities and challenges for people living in cities in lower income countries (LICs) or newly emerging economies (NEEs). (9 marks)",
        "marks": 9,
        "markScheme": [
          "Defines urbanisation and refers to a named LIC or NEE city, e.g. Rio de Janeiro, Lagos or Mumbai",
          "Explains opportunities such as jobs, better services (education, healthcare) and higher wages attracting rural-urban migration",
          "Explains challenges such as squatter settlements or favelas, congestion, pollution and inadequate services",
          "Considers social, economic and environmental dimensions with specific supporting evidence",
          "Reaches a supported judgement on the balance of opportunities versus challenges with a clear conclusion"
        ]
      },
      {
        "question": "Explain how physical and human factors can increase the risk of river flooding. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Explains physical factors such as prolonged or heavy rainfall increasing discharge",
          "Explains impermeable rock, saturated or frozen ground reducing infiltration and increasing surface runoff",
          "Explains relief such as steep slopes speeding water into the channel",
          "Explains human factors such as deforestation reducing interception",
          "Explains urbanisation and impermeable surfaces (concrete, drains) increasing runoff speed and shortening lag time"
        ]
      }
    ]
  },
  {
    "id": "psychology",
    "name": "Psychology",
    "topics": [
      "Memory (Multi-Store and Working Memory Models)",
      "Social Influence (Conformity and Obedience)",
      "Attachment",
      "Psychopathology (Definitions and Treatments)",
      "Approaches in Psychology (Behaviourist, Cognitive, Biological)",
      "Research Methods and Ethics",
      "The Brain and Neuropsychology"
    ],
    "flashcards": [
      {
        "front": "What are the three stages of the Multi-Store Model of Memory (Atkinson and Shiffrin)?",
        "back": "Sensory register (very brief, large capacity, encoded by sense), short-term memory (around 7 items, 18-30 seconds, mostly acoustic encoding) and long-term memory (potentially unlimited capacity and duration, mostly semantic encoding). Information passes between stores through attention and rehearsal."
      },
      {
        "front": "Define conformity and name Kelman's three types.",
        "back": "Conformity is changing behaviour or beliefs in response to real or imagined group pressure. The three types are compliance (public agreement only), identification (adopting behaviour to belong to a group) and internalisation (genuine private acceptance of the group's view)."
      },
      {
        "front": "What did Milgram's (1963) obedience study find?",
        "back": "65 percent of participants administered the maximum 450-volt shock to a confederate when ordered by an authority figure. It showed ordinary people will obey destructive orders under situational pressure, supporting the agentic state explanation of obedience."
      },
      {
        "front": "What are the four behaviours measured in Ainsworth's Strange Situation, and the three attachment types?",
        "back": "It measures proximity seeking, exploration/secure-base behaviour, stranger anxiety and separation anxiety, plus reunion behaviour. The types are secure (Type B), insecure-avoidant (Type A) and insecure-resistant (Type C)."
      },
      {
        "front": "What are the two-process model explanations for how phobias are acquired and maintained?",
        "back": "Phobias are acquired through classical conditioning (associating a neutral stimulus with a fear response) and maintained through operant conditioning via negative reinforcement (avoiding the phobic stimulus reduces anxiety, reinforcing the avoidance)."
      },
      {
        "front": "What are the assumptions of the behaviourist approach?",
        "back": "Behaviour is learned from the environment, only observable behaviour should be studied (not internal mental processes), and humans learn in the same way as animals. Learning occurs through classical conditioning (Pavlov) and operant conditioning (Skinner: reinforcement and punishment)."
      }
    ],
    "mcq": [
      {
        "question": "According to research by Jacobs and others, what is the typical capacity of short-term memory?",
        "options": [
          "3 plus or minus 2 items",
          "7 plus or minus 2 items",
          "12 plus or minus 2 items",
          "Unlimited"
        ],
        "answer": 1,
        "explanation": "Miller's 'magic number' established STM capacity as 7 plus or minus 2 items, expandable through chunking."
      },
      {
        "question": "In Asch's conformity study, which factor was found to DECREASE conformity levels?",
        "options": [
          "Increasing group size beyond three",
          "Making the task more ambiguous",
          "The presence of a dissenting ally",
          "Answering privately then publicly"
        ],
        "answer": 2,
        "explanation": "A dissenter breaking the unanimous majority reduced conformity from 37 percent to around 5.5 percent, as it provides social support."
      },
      {
        "question": "Bowlby's monotropic theory of attachment proposes a critical period of roughly:",
        "options": [
          "Up to 6 months",
          "Up to 2.5 years (around 30 months)",
          "Up to 5 years",
          "Up to 10 years"
        ],
        "answer": 1,
        "explanation": "Bowlby argued attachment must form within a critical period of about 30 months, or the child struggles to form one later."
      },
      {
        "question": "Which neurotransmitter is most strongly linked to obsessive-compulsive disorder (OCD)?",
        "options": [
          "Dopamine",
          "Serotonin",
          "Acetylcholine",
          "GABA"
        ],
        "answer": 1,
        "explanation": "Low serotonin levels are implicated in OCD, which is why SSRIs (serotonin reuptake inhibitors) are the main drug treatment."
      }
    ],
    "examQuestions": [
      {
        "question": "Outline and evaluate the Working Memory Model of memory. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Identify the central executive as the attentional control system that directs slave subsystems and has limited capacity",
          "Describe the phonological loop (phonological store and articulatory process) handling auditory/verbal information",
          "Describe the visuo-spatial sketchpad handling visual and spatial information, and the episodic buffer integrating information",
          "Strength: supporting evidence from dual-task studies (e.g. Baddeley) showing two tasks using the same component are harder",
          "Strength: case study evidence such as patient KF, who had impaired STM for verbal but not visual information",
          "Limitation: the central executive is vague and difficult to test/measure, lacking clear definition"
        ]
      },
      {
        "question": "Explain how situational variables affect obedience, using evidence from Milgram's variations. (8 marks)",
        "marks": 8,
        "markScheme": [
          "Define obedience as following a direct order from an authority figure",
          "Proximity: obedience dropped to 40 percent when teacher and learner were in the same room, and to 30 percent for touch-proximity",
          "Location: obedience fell to around 47.5 percent in a run-down office rather than prestigious Yale University",
          "Uniform: obedience dropped to around 20 percent when the experimenter was replaced by an ordinary member of the public",
          "Link variables to explanations such as the agentic state or legitimacy of authority",
          "Brief evaluation point (e.g. Bickman field experiment supporting uniform, or lacking internal/ecological validity)"
        ]
      },
      {
        "question": "Discuss two definitions of abnormality. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Deviation from social norms: behaviour that violates unwritten societal rules/expectations",
          "Failure to function adequately: inability to cope with day-to-day living (link to Rosenhan and Seligman criteria)",
          "Statistical infrequency: behaviour that is numerically rare, far from the average (e.g. IQ below 70)",
          "Deviation from ideal mental health: not meeting Jahoda's criteria such as self-actualisation and autonomy",
          "Evaluation: social norms are culturally and time relative, risking abuse/social control",
          "Evaluation: failure to function is subjective, and some abnormality does not cause distress (or some normal states like grief do)"
        ]
      }
    ]
  },
  {
    "id": "business",
    "name": "Business Studies",
    "topics": [
      "Business ownership and objectives",
      "Marketing and the marketing mix (4Ps)",
      "Finance, cash flow and profitability",
      "Operations and production",
      "Human resources and organisational structure",
      "External environment and stakeholders"
    ],
    "flashcards": [
      {
        "front": "What is the difference between limited and unlimited liability?",
        "back": "Limited liability means the owners' personal assets are protected and they can only lose the money they invested in the business. Unlimited liability means owners are personally responsible for all business debts, so personal assets can be seized to pay creditors."
      },
      {
        "front": "Define the four elements of the marketing mix (4Ps).",
        "back": "Product (the good or service and its features), Price (the amount charged and pricing strategy), Place (how and where the product reaches the customer) and Promotion (how the business communicates and persuades customers to buy)."
      },
      {
        "front": "What is cash flow, and why can a profitable business still fail?",
        "back": "Cash flow is the movement of money into and out of a business over time. A profitable business can still fail if it runs out of cash to pay immediate costs such as wages and suppliers, for example when too much money is tied up in stock or in credit given to customers."
      },
      {
        "front": "What is the break-even point and how is it calculated?",
        "back": "Break-even is the level of output where total revenue exactly equals total costs, so the business makes neither a profit nor a loss. It is calculated as fixed costs divided by the contribution per unit (selling price per unit minus variable cost per unit)."
      },
      {
        "front": "Explain the difference between an economy of scale and a diseconomy of scale.",
        "back": "Economies of scale are the cost advantages a business gains as it grows, reducing average cost per unit (for example bulk buying). Diseconomies of scale occur when a business grows too large and average costs rise, often due to poor communication and weak coordination."
      },
      {
        "front": "What is market segmentation?",
        "back": "Market segmentation is dividing a market into distinct groups of customers who share similar characteristics, such as age, income, location or lifestyle. It allows a business to target its products and marketing more effectively at the needs of each group."
      }
    ],
    "mcq": [
      {
        "question": "Which source of finance is most appropriate for a sole trader wanting to buy a new delivery van?",
        "options": [
          "Selling shares on the stock market",
          "A bank loan repaid over several years",
          "An overdraft used for daily expenses",
          "Retained profit from a public limited company"
        ],
        "answer": 1,
        "explanation": "A medium-term bank loan suits a fixed asset like a van; sole traders cannot issue shares and overdrafts are for short-term needs."
      },
      {
        "question": "A product has a selling price of 20 pounds and a variable cost of 12 pounds. What is the contribution per unit?",
        "options": [
          "32 pounds",
          "12 pounds",
          "8 pounds",
          "20 pounds"
        ],
        "answer": 2,
        "explanation": "Contribution per unit equals selling price minus variable cost, so 20 minus 12 equals 8 pounds."
      },
      {
        "question": "Which of the following is a benefit of operating as a private limited company (Ltd)?",
        "options": [
          "Shares can be sold freely to the general public",
          "Owners have unlimited liability",
          "Owners benefit from limited liability",
          "The business pays no tax at all"
        ],
        "answer": 2,
        "explanation": "A key advantage of an Ltd is limited liability; its shares are not sold to the general public, unlike a plc."
      },
      {
        "question": "What does the 'Place' element of the marketing mix refer to?",
        "options": [
          "The price charged to customers",
          "How the product is advertised",
          "The channels through which a product reaches the customer",
          "The features and design of the product"
        ],
        "answer": 2,
        "explanation": "Place refers to distribution: how and where the product is made available to customers, such as shops or online."
      }
    ],
    "examQuestions": [
      {
        "question": "Analyse two benefits to a small business of producing a cash flow forecast. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Identifies a relevant benefit, e.g. helps identify future cash shortfalls in advance",
          "Explains that the business can arrange finance such as an overdraft or loan before a shortage occurs",
          "Identifies a second benefit, e.g. supports planning and decision making on spending or timing of payments",
          "Explains how it helps the business avoid running out of cash and reassures lenders or investors",
          "Applies points to a small business context (limited cash reserves, vulnerable to failure)",
          "Develops a chain of reasoning linking the benefit to improved survival or stability"
        ]
      },
      {
        "question": "Evaluate whether a business should use price skimming or price penetration when launching a new product. (9 marks)",
        "marks": 9,
        "markScheme": [
          "Defines price skimming (high initial price) and price penetration (low initial price to gain market share)",
          "Argues for skimming, e.g. maximises revenue from early adopters and recovers development costs",
          "Argues for penetration, e.g. attracts customers quickly and discourages competitors",
          "Considers the type of product and market (innovative or unique vs highly competitive)",
          "Reaches a justified conclusion stating which strategy is more suitable and why",
          "Shows balanced judgement weighing risks such as skimming limiting sales volume or penetration reducing profit margins"
        ]
      },
      {
        "question": "Discuss the impact of an increase in interest rates on a business that has taken out a large bank loan. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Explains that higher interest rates increase the cost of repaying existing and new loans",
          "Analyses reduced profits due to higher interest payments and possible cash flow pressure",
          "Considers reduced consumer spending as customers have less disposable income, lowering demand",
          "Explains a possible fall in investment as borrowing becomes more expensive",
          "Considers factors affecting the size of the impact, e.g. amount borrowed, whether the rate is fixed or variable, and the type of business",
          "Reaches a supported judgement on the overall impact and how the business might respond, e.g. cutting costs or raising prices"
        ]
      }
    ]
  },
  {
    "id": "computer-science",
    "name": "Computer Science",
    "topics": [
      "Data representation (binary, hexadecimal, and character encoding)",
      "Computer architecture and the fetch-decode-execute cycle",
      "Algorithms, searching, and sorting",
      "Programming fundamentals and computational thinking",
      "Networks and network security",
      "Boolean logic and logic gates",
      "Databases and data storage"
    ],
    "flashcards": [
      {
        "front": "What is the difference between RAM and ROM?",
        "back": "RAM (Random Access Memory) is volatile, read/write memory that temporarily stores data and programs currently in use, losing its contents when power is off. ROM (Read Only Memory) is non-volatile and holds permanent instructions such as the bootstrap loader/BIOS that start the computer."
      },
      {
        "front": "Describe the fetch-decode-execute cycle.",
        "back": "The CPU fetches an instruction from memory using the address in the Program Counter, decodes it in the Control Unit to work out what it means, then executes it (for example performing a calculation in the ALU). The cycle then repeats for the next instruction."
      },
      {
        "front": "What is the difference between a compiler and an interpreter?",
        "back": "A compiler translates the entire source code into machine code in one go before execution, producing a standalone executable. An interpreter translates and runs the code line by line, which is easier for debugging but generally runs more slowly."
      },
      {
        "front": "How does a binary search work and what is its requirement?",
        "back": "A binary search repeatedly checks the middle item of an ordered list, discarding the half that cannot contain the target, until the item is found or none remain. It requires the list to be sorted and is far faster than a linear search on large datasets, with O(log n) time complexity."
      },
      {
        "front": "What is the purpose of the two-dimensional parity or a checksum in data transmission?",
        "back": "It is an error-detection method: extra calculated bits are sent with the data so the receiver can recompute the value and check whether it matches. If the values differ, an error occurred during transmission and the data can be re-requested."
      },
      {
        "front": "Define an IP address and a MAC address, and state how they differ.",
        "back": "An IP address is a logical address assigned to a device on a network that can change and is used for routing between networks. A MAC address is a permanent physical address hard-coded into the network interface card, used to identify the device on a local network."
      }
    ],
    "mcq": [
      {
        "question": "What is the denary (decimal) value of the 8-bit binary number 00101101?",
        "options": [
          "37",
          "45",
          "43",
          "53"
        ],
        "answer": 1,
        "explanation": "The set bits have place values 32 + 8 + 4 + 1 = 45."
      },
      {
        "question": "Which of these is a characteristic of the Random Access Memory (RAM) in a computer?",
        "options": [
          "It is non-volatile and stores the boot instructions",
          "It is volatile and loses its contents when powered off",
          "It permanently stores the operating system files",
          "It is a type of secondary storage such as a hard disk"
        ],
        "answer": 1,
        "explanation": "RAM is volatile working memory whose contents are lost when power is removed."
      },
      {
        "question": "What does the logic gate expression A AND B output when A = 1 and B = 0?",
        "options": [
          "1",
          "0",
          "It depends on a third input",
          "Both 1 and 0"
        ],
        "answer": 1,
        "explanation": "An AND gate only outputs 1 when both inputs are 1, so 1 AND 0 gives 0."
      },
      {
        "question": "Which sorting algorithm repeatedly steps through the list, comparing adjacent items and swapping them if they are in the wrong order?",
        "options": [
          "Merge sort",
          "Binary sort",
          "Bubble sort",
          "Insertion search"
        ],
        "answer": 2,
        "explanation": "Bubble sort compares and swaps adjacent elements on repeated passes until no swaps are needed."
      }
    ],
    "examQuestions": [
      {
        "question": "Explain the difference between lossy and lossless compression, giving one example of when each would be appropriate. (4 marks)",
        "marks": 4,
        "markScheme": [
          "Lossy compression permanently removes some data/detail to reduce file size, so the original cannot be fully restored",
          "Lossless compression reduces file size without losing any data, so the original file can be restored exactly",
          "Appropriate example of lossy (e.g. streaming music or photos where small quality loss is acceptable)",
          "Appropriate example of lossless (e.g. text files, spreadsheets or program code where every bit must be preserved)"
        ]
      },
      {
        "question": "Describe how a packet-switched network sends data from one computer to another. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Data is split into small units called packets",
          "Each packet is given a header containing the source and destination addresses",
          "Packets also carry a sequence number so they can be reassembled in order",
          "Packets can travel independently by different routes across the network",
          "Routers direct each packet towards its destination",
          "At the destination the packets are reassembled in the correct order and any missing packets are re-requested"
        ]
      },
      {
        "question": "A programmer must choose between a linear search and a binary search for a dataset. Compare the two algorithms and explain when each should be used. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Linear search checks each item in turn from the start until the target is found or the list ends",
          "Binary search repeatedly checks the middle item and discards half the remaining list each time",
          "Linear search works on unordered lists, whereas binary search requires the list to be sorted first",
          "Binary search is much faster on large datasets (O(log n) versus O(n) for linear search)",
          "Linear search is simpler and better for small or unsorted lists",
          "Binary search is preferable for large sorted datasets where speed matters"
        ]
      }
    ]
  },
  {
    "id": "sociology",
    "name": "Sociology",
    "topics": [
      "Sociological Theories and Perspectives",
      "Research Methods",
      "Families and Households",
      "Education",
      "Crime and Deviance",
      "Social Stratification and Inequality",
      "Socialisation, Culture and Identity"
    ],
    "flashcards": [
      {
        "front": "Define socialisation and distinguish primary from secondary socialisation.",
        "back": "Socialisation is the lifelong process by which people learn the norms, values and culture of their society. Primary socialisation happens in early childhood, mainly through the family; secondary socialisation occurs later through agents such as education, peers, religion and the media."
      },
      {
        "front": "What is the difference between the consensus and conflict views of society?",
        "back": "Consensus theories (like functionalism) see society as based on shared values and cooperation, with institutions working together for stability. Conflict theories (like Marxism and feminism) see society as divided by inequality and competition, with powerful groups exploiting or dominating others."
      },
      {
        "front": "Outline the Marxist view of the role of education.",
        "back": "Marxists argue education reproduces class inequality and serves capitalism by transmitting ruling-class ideology and legitimising inequality as fair. Bowles and Gintis' correspondence principle claims school mirrors the workplace, producing an obedient, exploitable workforce through the hidden curriculum."
      },
      {
        "front": "What are the key differences between quantitative and qualitative data?",
        "back": "Quantitative data is numerical and is favoured by positivists for producing reliable, generalisable statistics that reveal social patterns. Qualitative data is descriptive and in-depth, favoured by interpretivists for achieving validity and understanding the meanings behind people's behaviour."
      },
      {
        "front": "Define anomie and identify the sociologist associated with it.",
        "back": "Anomie is a state of normlessness where social norms are weak, unclear or breaking down, leaving behaviour poorly regulated. Durkheim linked it to rapid social change, while Merton used it to explain the strain between cultural goals and legitimate means to achieve them."
      },
      {
        "front": "What is the difference between sex and gender in sociology?",
        "back": "Sex refers to the biological differences between males and females, such as chromosomes and reproductive organs. Gender refers to the socially constructed roles, behaviours and expectations attached to being masculine or feminine, which vary across cultures and are learned through socialisation."
      }
    ],
    "mcq": [
      {
        "question": "Which sociological perspective argues that institutions work together like organs in a body to maintain social order?",
        "options": [
          "Marxism",
          "Functionalism",
          "Feminism",
          "Interactionism"
        ],
        "answer": 1,
        "explanation": "Functionalism uses the organic analogy, seeing institutions as interdependent parts that keep society stable."
      },
      {
        "question": "A researcher wants highly reliable, generalisable data on educational achievement. Which method is most suitable?",
        "options": [
          "Participant observation",
          "Unstructured interviews",
          "Structured questionnaires",
          "Personal diaries"
        ],
        "answer": 2,
        "explanation": "Structured questionnaires produce standardised, quantitative data that is reliable and easy to generalise, favoured by positivists."
      },
      {
        "question": "Which term describes the informal lessons and values pupils learn in school beyond the formal timetable?",
        "options": [
          "The hidden curriculum",
          "Streaming",
          "Material deprivation",
          "Cultural capital"
        ],
        "answer": 0,
        "explanation": "The hidden curriculum refers to the unofficial norms and values, such as obedience, learned indirectly at school."
      },
      {
        "question": "According to Merton's strain theory, which response involves rejecting both society's goals and the legitimate means to achieve them?",
        "options": [
          "Innovation",
          "Ritualism",
          "Retreatism",
          "Conformity"
        ],
        "answer": 2,
        "explanation": "Retreatism means dropping out, rejecting both the goals of success and the approved means, as seen with some addicts."
      }
    ],
    "examQuestions": [
      {
        "question": "Using sociological examples, explain how the family acts as an agent of primary socialisation. (6 marks)",
        "marks": 6,
        "markScheme": [
          "Define primary socialisation as the earliest learning of norms and values in childhood",
          "Identify the family as the main agent of primary socialisation",
          "Explain teaching of norms and values, e.g. manners, right and wrong",
          "Reference gender role socialisation through canalisation or imitation of parents",
          "Use a relevant concept or sociologist, e.g. Parsons on the family teaching shared values",
          "Show that this shapes the child's identity and prepares them for wider society"
        ]
      },
      {
        "question": "Discuss the strengths and limitations of using participant observation in sociological research. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Define participant observation and distinguish overt from covert forms",
          "Strength: produces high validity and rich, in-depth qualitative data (interpretivist favour)",
          "Strength: allows study of hard-to-reach groups and verstehen (empathetic understanding)",
          "Limitation: low reliability as it is hard to replicate and is time-consuming",
          "Limitation: risk of researcher bias, going native, and the observer effect",
          "Evaluate ethical issues (consent, deception in covert work) and reach a balanced judgement"
        ]
      },
      {
        "question": "Assess the view that education mainly serves to reproduce social class inequality. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Outline the Marxist view that education reproduces and legitimises class inequality",
          "Use evidence such as Bowles and Gintis' correspondence principle and the hidden curriculum",
          "Refer to cultural capital (Bourdieu) and material deprivation disadvantaging working-class pupils",
          "Offer the functionalist counter-view: meritocracy, role allocation and equal opportunity (Davis and Moore, Parsons)",
          "Include a further perspective, e.g. feminist or interactionist views (labelling, self-fulfilling prophecy)",
          "Reach a supported conclusion weighing reproduction of inequality against other functions of education"
        ]
      }
    ]
  },
  {
    "id": "religious-studies",
    "name": "Religious Studies",
    "topics": [
      "Christian beliefs and teachings",
      "Islamic beliefs and teachings",
      "The existence of God (arguments and challenges)",
      "Religion and ethics (crime, punishment, war and peace)",
      "Life and death (sanctity of life, afterlife)",
      "Religion, relationships and families",
      "Religious practices and worship"
    ],
    "flashcards": [
      {
        "front": "What is the Christian doctrine of the Trinity?",
        "back": "The belief that God is one being existing in three distinct persons: the Father, the Son (Jesus Christ) and the Holy Spirit. Each person is fully God, yet there is only one God, as expressed in the Nicene Creed."
      },
      {
        "front": "What are the Five Pillars of Sunni Islam?",
        "back": "Shahadah (declaration of faith), Salah (five daily prayers), Zakah (almsgiving), Sawm (fasting during Ramadan) and Hajj (pilgrimage to Makkah). They are the foundational acts of worship that structure a Muslim's life."
      },
      {
        "front": "State and briefly explain the Cosmological argument for the existence of God.",
        "back": "It argues that everything that exists has a cause, so the universe must have a first, uncaused cause, which is God. Aquinas developed this in his Five Ways, reasoning that an infinite regress of causes is impossible."
      },
      {
        "front": "What is the difference between the Sanctity of Life and the Quality of Life?",
        "back": "Sanctity of Life is the belief that life is sacred and God-given, so it has intrinsic value and should be protected. Quality of Life judges the value of a life by its condition or wellbeing, an idea often raised in debates on euthanasia and abortion."
      },
      {
        "front": "Define 'omnipotent', 'omnibenevolent' and 'omniscient'.",
        "back": "Omnipotent means all-powerful, omnibenevolent means all-loving or all-good, and omniscient means all-knowing. These classical attributes of God are central to debates such as the Problem of Evil."
      },
      {
        "front": "What are the three main aims of punishment discussed in Religious Studies?",
        "back": "Deterrence (discouraging others from crime), retribution (making the offender pay for the wrong) and reformation (changing the offender for the better). Many religious believers emphasise reformation, linked to forgiveness and mercy."
      }
    ],
    "mcq": [
      {
        "question": "Which term describes the Christian belief that God became human in the person of Jesus?",
        "options": [
          "Resurrection",
          "Incarnation",
          "Ascension",
          "Atonement"
        ],
        "answer": 1,
        "explanation": "Incarnation means God taking on human flesh in Jesus; resurrection and ascension are later events, and atonement is the reconciling of humanity with God."
      },
      {
        "question": "The Problem of Evil is most often used as an argument for which conclusion?",
        "options": [
          "That God must be all-powerful",
          "That miracles prove God exists",
          "That an omnipotent, omnibenevolent God may not exist",
          "That suffering has no cause"
        ],
        "answer": 2,
        "explanation": "The existence of evil and suffering appears to conflict with a God who is both all-loving and all-powerful, challenging belief in such a God."
      },
      {
        "question": "In Islam, the belief in one, single, indivisible God is known as:",
        "options": [
          "Tawhid",
          "Risalah",
          "Akhirah",
          "Ummah"
        ],
        "answer": 0,
        "explanation": "Tawhid is the oneness of God; Risalah is prophethood, Akhirah is the afterlife, and Ummah is the worldwide Muslim community."
      },
      {
        "question": "Which of these is a Just War theory condition for a war to be considered justified?",
        "options": [
          "It must be fought for economic gain",
          "It must be a last resort with a just cause",
          "It must always use nuclear weapons",
          "It must be declared in secret"
        ],
        "answer": 1,
        "explanation": "Just War theory requires conditions such as a just cause, proper authority, and war as a last resort, with proportionate and discriminate conduct."
      }
    ],
    "examQuestions": [
      {
        "question": "Explain two Christian beliefs about the afterlife. (4 marks)",
        "marks": 4,
        "markScheme": [
          "Identify a first belief, e.g. belief in resurrection to eternal life with God in heaven",
          "Develop it with reference to a source of authority, e.g. Jesus' resurrection or John 14 ('In my Father's house are many rooms')",
          "Identify a second belief, e.g. judgement, where God assesses a person's life leading to heaven or hell",
          "Develop it with reference to teaching such as the Parable of the Sheep and the Goats (Matthew 25)"
        ]
      },
      {
        "question": "'Science has made belief in God unnecessary.' Evaluate this statement, showing you have considered more than one point of view. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Arguments for: science (e.g. the Big Bang, evolution) offers natural explanations that seem to remove the need for God",
          "Arguments for: apparent conflicts between scientific evidence and literal religious texts",
          "Arguments against: many believers see science and religion as compatible, with God as the ultimate cause behind natural processes (non-literal interpretation)",
          "Arguments against: science explains 'how' but not 'why', and cannot address purpose, morality or the existence of the universe itself",
          "Reference to religious teachings or thinkers to support each side",
          "A clear, justified conclusion weighing the arguments and reaching a reasoned judgement"
        ]
      },
      {
        "question": "Explain two religious beliefs about the aims of punishment. Refer to sacred writings or another source of religious belief and teaching in your answer. (5 marks)",
        "marks": 5,
        "markScheme": [
          "Identify a first aim, e.g. reformation, changing the offender so they do not reoffend",
          "Explain it, linking to religious emphasis on forgiveness and mercy",
          "Identify a second aim, e.g. deterrence or retribution",
          "Explain it with reference to justice and protecting society",
          "Include a relevant source of authority, e.g. 'Love your enemies' (Matthew 5) or 'an eye for an eye' (Exodus 21), used accurately"
        ]
      }
    ]
  },
  {
    "id": "politics",
    "name": "Politics",
    "topics": [
      "Democracy and Participation",
      "Political Parties and Party Systems",
      "Elections and Voting Systems",
      "Parliament and the Legislature",
      "The Prime Minister, Executive and Cabinet",
      "The Constitution and the Judiciary",
      "Political Ideologies (Liberalism, Conservatism, Socialism)"
    ],
    "flashcards": [
      {
        "front": "What is the difference between direct and representative democracy?",
        "back": "In direct democracy citizens make political decisions themselves, for example through referendums, with no intermediary. In representative democracy citizens elect representatives (such as MPs) to make decisions on their behalf and hold them accountable at elections."
      },
      {
        "front": "What is meant by parliamentary sovereignty?",
        "back": "Parliamentary sovereignty is the principle that Parliament is the supreme legal authority in the UK: it can make or repeal any law, and no Parliament can bind its successors. In theory no other body, including the courts, can override an Act of Parliament."
      },
      {
        "front": "How does the First Past the Post (FPTP) voting system work, and what is one criticism of it?",
        "back": "Under FPTP the country is divided into single-member constituencies and the candidate with the most votes (a plurality) wins each seat. A key criticism is that it produces disproportionate results, so a party's share of seats often differs sharply from its share of the national vote, and many votes are wasted."
      },
      {
        "front": "What is the royal prerogative?",
        "back": "The royal prerogative is the set of historic powers formally held by the Crown but now exercised in practice by the Prime Minister and ministers. It includes powers such as deploying the armed forces, making treaties, and appointing ministers, and is largely uncodified."
      },
      {
        "front": "What is the difference between a manifesto and a mandate?",
        "back": "A manifesto is the document a party publishes before an election setting out the policies it intends to implement if elected. A mandate is the authority to govern and enact those manifesto policies that the winning party gains from securing an election victory."
      },
      {
        "front": "Outline one core value of classical liberalism.",
        "back": "Classical liberalism stresses individual liberty and a limited (minimal) state, holding that government should exist mainly to protect natural rights such as life, liberty and property. It favours a free-market economy and views individuals as rational, self-interested and capable of self-determination."
      }
    ],
    "mcq": [
      {
        "question": "Which voting system is used to elect Members of Parliament to the House of Commons in UK general elections?",
        "options": [
          "Single Transferable Vote",
          "First Past the Post",
          "Additional Member System",
          "Closed Party List"
        ],
        "answer": 1,
        "explanation": "UK MPs are elected in single-member constituencies using First Past the Post, where the candidate with the most votes wins."
      },
      {
        "question": "What is the main function of the House of Lords in the UK legislative process?",
        "options": [
          "To choose the Prime Minister",
          "To scrutinise and revise legislation",
          "To hold general elections",
          "To declare Acts unconstitutional"
        ],
        "answer": 1,
        "explanation": "The Lords acts as a revising chamber, scrutinising and suggesting amendments to bills, but the elected Commons ultimately prevails."
      },
      {
        "question": "Which principle means that government ministers must resign if they are personally responsible for a serious failure in their department?",
        "options": [
          "Collective responsibility",
          "Individual ministerial responsibility",
          "Parliamentary privilege",
          "The separation of powers"
        ],
        "answer": 1,
        "explanation": "Individual ministerial responsibility holds each minister personally accountable to Parliament for their own conduct and their department."
      },
      {
        "question": "Which of the following is a key feature of a socialist ideology?",
        "options": [
          "Belief in a minimal state and free markets",
          "Emphasis on tradition and hierarchy",
          "Commitment to greater equality and collective/cooperative action",
          "Rejection of all state intervention"
        ],
        "answer": 2,
        "explanation": "Socialism prioritises social equality and cooperation, favouring collective action and, often, state intervention to reduce inequality."
      }
    ],
    "examQuestions": [
      {
        "question": "Explain and analyse three ways in which the UK could be described as suffering from a 'democratic deficit'. (9 marks)",
        "marks": 9,
        "markScheme": [
          "Low turnout at elections and referendums weakens the legitimacy of the result and of those elected",
          "The disproportionate outcomes of First Past the Post mean seats do not reflect votes, producing wasted votes and under-represented parties",
          "The unelected House of Lords and (historically) hereditary elements lack democratic accountability",
          "The concentration of power in the executive/PM through the royal prerogative reduces meaningful scrutiny",
          "Lack of a codified constitution or entrenched bill of rights limits protection of citizens' rights against government",
          "Each point should be developed with explanation and, where possible, a relevant example"
        ]
      },
      {
        "question": "Evaluate the view that the Prime Minister has become too powerful in the UK political system. (25 marks)",
        "marks": 12,
        "markScheme": [
          "AO1: knowledge of PM powers, e.g. patronage/appointing ministers, control of the cabinet agenda, use of the royal prerogative, party leadership and role as chief policy-maker",
          "Argument that the PM is too powerful: dominance over cabinet, large majorities, media focus creating 'presidentialisation', control of the whips and party",
          "Counter-argument: constraints from the cabinet, party (risk of removal), Parliament, backbench rebellions, coalition/minority situations and public opinion",
          "Use of relevant contemporary or historical examples to support both sides",
          "A clear line of argument and a justified, balanced conclusion that reaches a supported judgement",
          "Analysis and evaluation weighing the strength of arguments rather than simply describing"
        ]
      },
      {
        "question": "Explain the difference between a referendum and a general election, and give one advantage of each. (6 marks)",
        "marks": 6,
        "markScheme": [
          "A referendum is a form of direct democracy where voters decide a single specific issue (usually yes/no)",
          "A general election is a form of representative democracy where voters choose MPs/representatives to make decisions for them",
          "Advantage of a referendum: gives a clear popular mandate on a specific issue and increases direct participation",
          "Advantage of a general election: allows voters to choose a government and hold representatives accountable across many issues",
          "Clear contrast drawn between the two rather than describing them in isolation"
        ]
      }
    ]
  },
  {
    "id": "french",
    "name": "French",
    "topics": [
      "Verb tenses (present, perfect, imperfect, future, conditional)",
      "The subjunctive mood",
      "Gender, articles and adjective agreement",
      "Pronouns (object, y, en, relative)",
      "Negatives, questions and connectives",
      "Common topics: family, school, work, environment, holidays",
      "Higher-tier structures: si clauses, passive, depuis"
    ],
    "flashcards": [
      {
        "front": "How do you form the perfect tense (le passe compose)?",
        "back": "Use the present tense of avoir or etre plus a past participle, e.g. j'ai mange (I ate/have eaten). A set of movement/reflexive verbs (the DR MRS VANDERTRAMP group) take etre, and with etre the participle agrees with the subject, e.g. elle est allee."
      },
      {
        "front": "When do you use the imperfect (l'imparfait) versus the perfect tense?",
        "back": "The imperfect describes ongoing, repeated or background actions in the past (descriptions, habits, 'was doing'/'used to do'), e.g. je jouais. The perfect describes single completed actions, e.g. j'ai joue. They are often combined: je regardais la tele quand le telephone a sonne."
      },
      {
        "front": "What does the subjunctive express and what commonly triggers it?",
        "back": "The subjunctive expresses doubt, emotion, necessity, wish or opinion rather than fact. It is triggered by phrases such as il faut que, je veux que, bien que, avant que and pour que, e.g. il faut que je fasse mes devoirs."
      },
      {
        "front": "Translate and give the rule: 'I have been learning French for three years.'",
        "back": "J'apprends le francais depuis trois ans. With depuis, French uses the present tense (not the perfect as in English) for an action that started in the past and is still continuing."
      },
      {
        "front": "How do you form the near future (le futur proche) and give an example.",
        "back": "Use the present tense of aller plus an infinitive, e.g. je vais partir (I am going to leave). It expresses plans or intentions and is a common, high-frequency alternative to the simple future."
      },
      {
        "front": "How does adjective agreement work, and where do adjectives usually go?",
        "back": "Adjectives agree in gender and number with the noun: add -e for feminine and -s for plural, e.g. un petit chat / une petite maison / des petits chats. Most adjectives follow the noun, but a small group (BAGS: beauty, age, goodness, size) come before it, e.g. une grande maison."
      }
    ],
    "mcq": [
      {
        "question": "Which sentence correctly uses the perfect tense with etre and correct agreement?",
        "options": [
          "Elle a allee au marche",
          "Elle est allee au marche",
          "Elle est alle au marche",
          "Elle a alle au marche"
        ],
        "answer": 1,
        "explanation": "Aller takes etre, and the past participle agrees with the feminine subject, giving 'est allee'."
      },
      {
        "question": "Choose the correct completion: 'Il faut que tu ___ tes devoirs.'",
        "options": [
          "fais",
          "fait",
          "fasses",
          "feras"
        ],
        "answer": 2,
        "explanation": "'Il faut que' triggers the subjunctive, so the correct form of faire is 'fasses'."
      },
      {
        "question": "Which is the correct translation of 'I am going to eat'?",
        "options": [
          "Je mangeais",
          "Je vais manger",
          "J'ai mange",
          "Je mangerais"
        ],
        "answer": 1,
        "explanation": "The futur proche is 'aller' in the present plus an infinitive: 'je vais manger'."
      },
      {
        "question": "Which sentence correctly uses a 'si' clause about a hypothetical situation?",
        "options": [
          "Si j'aurais de l'argent, je voyagerais",
          "Si j'avais de l'argent, je voyagerais",
          "Si j'avais de l'argent, je voyageais",
          "Si j'ai de l'argent, je voyagerais"
        ],
        "answer": 1,
        "explanation": "The pattern is 'si' plus imperfect followed by the conditional: 'Si j'avais... je voyagerais'. The conditional is never used directly after 'si'."
      }
    ],
    "examQuestions": [
      {
        "question": "Translate into French: 'Last weekend I went to the cinema with my friends and we watched a film.' (Higher-tier translation, GCSE style)",
        "marks": 6,
        "markScheme": [
          "Correct time phrase, e.g. 'Le week-end dernier' or 'Le weekend dernier'",
          "Perfect tense of aller with etre and correct agreement: 'je suis alle(e)'",
          "'au cinema' with correct preposition/article",
          "'avec mes amis' with correct possessive and plural",
          "Perfect tense of regarder with avoir: 'nous avons regarde' (or 'on a regarde')",
          "'un film' with correct article and overall accurate spelling/word order"
        ]
      },
      {
        "question": "Ecrivez environ 90 mots en francais sur votre routine quotidienne et ce que vous avez fait le week-end dernier. (GCSE writing task)",
        "marks": 10,
        "markScheme": [
          "Uses present tense correctly for daily routine (e.g. je me leve, je vais)",
          "Uses at least one past tense (perfect or imperfect) for the weekend",
          "Includes a range of vocabulary and time markers (d'habitude, ensuite, hier)",
          "Uses at least one opinion with a reason (e.g. j'aime... parce que)",
          "Includes a connective or more complex structure (parce que, quand, qui)",
          "Communication is clear and largely accurate; roughly meets the word count"
        ]
      },
      {
        "question": "Explain, with examples, when a French verb takes 'etre' rather than 'avoir' in the perfect tense, and how this affects the past participle. (Grammar explanation, A-level style)",
        "marks": 8,
        "markScheme": [
          "States that a set of intransitive verbs of movement/change of state take etre (DR MRS VANDERTRAMP)",
          "Gives correct examples such as aller, venir, arriver, partir, rester, tomber, naitre, mourir",
          "States that all reflexive/pronominal verbs also take etre (e.g. se lever: je me suis leve(e))",
          "Explains that with etre the past participle agrees with the subject in gender and number",
          "Gives a correct agreement example (e.g. elles sont arrivees)",
          "Contrasts with avoir verbs, where the participle does not agree with the subject (but agrees with a preceding direct object)"
        ]
      }
    ]
  },
  {
    "id": "english-language",
    "name": "English Language",
    "topics": [
      "Reading and analysing non-fiction texts",
      "Creative and descriptive writing",
      "Persuasive and transactional writing (form, audience, purpose)",
      "Language analysis: word classes and figurative devices",
      "Structural devices and text organisation",
      "Comparing writers' viewpoints and methods",
      "Spelling, punctuation, grammar and sentence variety"
    ],
    "flashcards": [
      {
        "front": "What is the difference between denotation and connotation?",
        "back": "Denotation is the literal, dictionary meaning of a word, while connotation is the set of ideas, feelings or associations it suggests. For example, 'home' denotes a place of residence but connotes warmth, safety and belonging."
      },
      {
        "front": "Define 'sibilance' and explain its effect.",
        "back": "Sibilance is the repetition of soft 's', 'sh' or 'z' sounds close together in a phrase or line. It can create a hushed, soothing, whispering or sometimes sinister and unsettling tone depending on context."
      },
      {
        "front": "What does GAP (or GAPS) stand for when planning a piece of writing?",
        "back": "Genre (or Form), Audience and Purpose, with Subject sometimes added. Identifying these before writing ensures the tone, register, structure and vocabulary suit the task, such as a formal letter to persuade a council versus a lively article to entertain teenagers."
      },
      {
        "front": "What is the difference between a simile and a metaphor?",
        "back": "A simile compares two things using 'like' or 'as' (for example, 'the water was as smooth as glass'), whereas a metaphor states that one thing is another (for example, 'the water was a sheet of glass'). Both create vivid imagery, but the metaphor is more direct and forceful."
      },
      {
        "front": "Name and describe three sentence types used to vary writing.",
        "back": "A simple sentence has one main clause; a compound sentence joins two main clauses with a coordinating conjunction such as 'and', 'but' or 'so'; and a complex sentence contains a main clause plus one or more subordinate clauses. Varying these controls pace, emphasis and reader engagement."
      },
      {
        "front": "What is a formal register and when should it be used?",
        "back": "Register is the level of formality in language, shaped by audience and purpose. A formal register uses standard English, avoids slang and contractions, and often uses the passive voice or Latinate vocabulary; it suits letters of application, reports, speeches to authority and academic responses."
      }
    ],
    "mcq": [
      {
        "question": "Which of the following is an example of a metaphor?",
        "options": [
          "The wind howled like a wolf.",
          "Her smile was a burst of sunshine.",
          "He ran as fast as a cheetah.",
          "The classroom was quiet as a grave."
        ],
        "answer": 1,
        "explanation": "'Her smile was a burst of sunshine' directly states one thing is another; the others use 'like' or 'as' and are similes."
      },
      {
        "question": "A writer repeats the phrase 'We will fight' at the start of three consecutive sentences. Which device is this?",
        "options": [
          "Anaphora",
          "Onomatopoeia",
          "Hyperbole",
          "Oxymoron"
        ],
        "answer": 0,
        "explanation": "Anaphora is the deliberate repetition of the same words at the beginning of successive clauses or sentences for emphasis and rhythm."
      },
      {
        "question": "Which word class describes 'quickly', 'very' and 'yesterday'?",
        "options": [
          "Adjectives",
          "Adverbs",
          "Pronouns",
          "Prepositions"
        ],
        "answer": 1,
        "explanation": "Adverbs modify verbs, adjectives or other adverbs, describing how, when, where or to what degree something happens."
      },
      {
        "question": "Which sentence uses a semicolon correctly?",
        "options": [
          "I love reading; and writing too.",
          "The rain fell heavily; the streets soon flooded.",
          "She packed her bags; because the taxi arrived.",
          "Buy milk; eggs; and bread."
        ],
        "answer": 1,
        "explanation": "A semicolon joins two closely related independent clauses that could each stand alone as a sentence, which only the second option does correctly."
      }
    ],
    "examQuestions": [
      {
        "question": "Read the opening of a source text describing a storm. How does the writer use language to create a sense of danger? Refer to specific words, phrases and language techniques in your answer. (8 marks)",
        "marks": 8,
        "markScheme": [
          "Selects relevant quotations that clearly relate to danger and threat",
          "Identifies specific language devices such as personification, powerful verbs or violent imagery",
          "Analyses the effect of individual word choices and their connotations on the reader",
          "Uses accurate subject terminology throughout (for example verb, adjective, metaphor)",
          "Develops a range of points rather than repeating one idea, with a clear focus on the question",
          "Comments on how the cumulative effect builds tension or fear for the reader"
        ]
      },
      {
        "question": "Compare how the two writers convey their attitudes towards city life in Source A and Source B. Compare their ideas and perspectives and the methods they use to convey them. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Identifies each writer's overall attitude or viewpoint towards city life",
          "Compares similarities and differences in their ideas and perspectives explicitly",
          "Selects well-chosen supporting quotations from both sources",
          "Analyses methods used by each writer such as tone, structure, imagery or word choice",
          "Links methods clearly to the effect on the reader and to the writer's purpose",
          "Sustains a comparative structure using connectives such as whereas, similarly and in contrast rather than treating sources separately"
        ]
      },
      {
        "question": "'Social media does more harm than good to young people.' Write the text of a speech for a school debate in which you argue for or against this statement. (12 marks)",
        "marks": 12,
        "markScheme": [
          "Adopts a clear and consistent viewpoint that directly addresses the statement",
          "Matches form, tone and register to a speech and a student audience using direct address and rhetorical questions",
          "Uses persuasive devices effectively, for example rhetoric, anecdote, statistics, triples or emotive language",
          "Organises ideas with a strong opening, logically sequenced paragraphs and a memorable conclusion",
          "Demonstrates varied vocabulary and sentence structures for deliberate effect",
          "Maintains accurate spelling, punctuation and grammar with controlled use of Standard English"
        ]
      }
    ]
  }
]
