/*
  A second batch of Edexcel A-level Maths multiple-choice questions, for the
  Pure Year 2, Statistics and Mechanics chapters.

  Every Maths chapter shipped with exactly 4 MCQs, which is one short
  session and then repeats. These add 4 more to each of the 25 A2 /
  Statistics / Mechanics chapters - the ones a Year 13 is actually revising.

  Distractors are the mistakes students really make - sign slips, using
  degrees where radians are required, forgetting to flip an inequality,
  confusing variance with standard deviation - so a wrong answer tells you
  which misconception you have rather than just that you were wrong.
*/
export const MATHS_MCQ_3 = [
  // ------------------------------------------------------ PURE · YEAR 2
  {
    question: 'Express 5 / ((x + 1)(x - 4)) in partial fractions. What is the numerator over (x - 4)?',
    options: ['1', '-1', '5', '1/5'],
    answer: 0,
    explanation: 'Write 5 = A(x - 4) + B(x + 1). Substituting x = 4 gives 5 = 5B, so B = 1.',
    topic: 'Algebraic Methods (Partial Fractions)',
  },
  {
    question: 'How many separate fractions does (x + 2) / ((x - 1)(x + 3)²) split into?',
    options: ['3', '2', '4', '1'],
    answer: 0,
    explanation: 'A repeated factor needs one fraction per power: A/(x-1) + B/(x+3) + C/(x+3)². That is three.',
    topic: 'Algebraic Methods (Partial Fractions)',
  },
  {
    question: 'Which is the first step when writing (x³ + 2x) / (x² - 1) in partial fractions?',
    options: [
      'Divide, since the fraction is improper',
      'Factorise the numerator',
      'Substitute x = 1 immediately',
      'Multiply both sides by (x² - 1)',
    ],
    answer: 0,
    explanation: 'The numerator has a higher degree than the denominator, so it is improper. Divide first to get a polynomial plus a proper fraction.',
    topic: 'Algebraic Methods (Partial Fractions)',
  },
  {
    question: 'In a proof by contradiction that √2 is irrational, what is assumed at the start?',
    options: [
      'That √2 can be written as a/b in its lowest terms',
      'That √2 is irrational',
      'That a and b are both even',
      'That 2 is prime',
    ],
    answer: 0,
    explanation: 'You assume the opposite of what you want to prove - that √2 is rational, so equals a/b in lowest terms - then derive a contradiction.',
    topic: 'Algebraic Methods (Partial Fractions)',
  },
  {
    question: 'If f(x) = 2x + 1 and g(x) = x², what is fg(3)?',
    options: ['19', '49', '10', '37'],
    answer: 0,
    explanation: 'fg means do g first: g(3) = 9, then f(9) = 2(9) + 1 = 19. (gf(3) would be 49 - a common slip.)',
    topic: 'Functions and Graphs',
  },
  {
    question: 'The function f has domain x ≥ 2 and range f(x) ≥ 5. What is the domain of f⁻¹?',
    options: ['x ≥ 5', 'x ≥ 2', 'x ≤ 5', 'all real x'],
    answer: 0,
    explanation: 'The domain of the inverse is the range of the original function, so x ≥ 5.',
    topic: 'Functions and Graphs',
  },
  {
    question: 'How does the graph of y = |f(x)| differ from y = f(x)?',
    options: [
      'Any part below the x-axis is reflected above it',
      'Any part left of the y-axis is deleted',
      'The whole graph is reflected in the y-axis',
      'The graph is stretched vertically',
    ],
    answer: 0,
    explanation: 'The modulus makes every output non-negative, so sections below the x-axis flip up. (y = f(|x|) is the one that reflects in the y-axis.)',
    topic: 'Functions and Graphs',
  },
  {
    question: 'Solve |2x - 6| = 4. What are the solutions?',
    options: ['x = 5 and x = 1', 'x = 5 only', 'x = 1 only', 'x = 5 and x = -1'],
    answer: 0,
    explanation: 'Either 2x - 6 = 4 giving x = 5, or 2x - 6 = -4 giving x = 1. Both check out in the original equation.',
    topic: 'Functions and Graphs',
  },
  {
    question: 'A geometric series has a = 8 and r = 1/2. What is the sum to infinity?',
    options: ['16', '8', '4', 'It diverges'],
    answer: 0,
    explanation: 'S∞ = a/(1 - r) = 8/(1 - 0.5) = 8/0.5 = 16. Valid because |r| < 1.',
    topic: 'Sequences and Series',
  },
  {
    question: 'An arithmetic sequence has a = 3 and d = 4. What is the 10th term?',
    options: ['39', '43', '40', '36'],
    answer: 0,
    explanation: 'u₁₀ = a + (n - 1)d = 3 + 9 × 4 = 39. Using n rather than (n - 1) gives 43 - the classic error.',
    topic: 'Sequences and Series',
  },
  {
    question: 'For which values of r does a geometric series have a sum to infinity?',
    options: ['|r| < 1', 'r < 1', 'r > 0', 'all values of r'],
    answer: 0,
    explanation: 'The series converges only when |r| < 1, i.e. -1 < r < 1. Writing r < 1 wrongly admits values like r = -3.',
    topic: 'Sequences and Series',
  },
  {
    question: 'A sequence is defined by uₙ₊₁ = uₙ + 5 with u₁ = 2. This sequence is:',
    options: ['increasing', 'decreasing', 'periodic', 'convergent'],
    answer: 0,
    explanation: 'Each term is 5 more than the last, so uₙ₊₁ > uₙ for all n - it is increasing (and arithmetic with d = 5).',
    topic: 'Sequences and Series',
  },
  {
    question: 'For what values of x is the expansion of (1 + 4x)⁻² valid?',
    options: ['|x| < 1/4', '|x| < 1', '|x| < 4', 'all x'],
    answer: 0,
    explanation: 'Validity requires |4x| < 1, so |x| < 1/4. Quoting |x| < 1 ignores the coefficient of x.',
    topic: 'The Binomial Expansion (General n)',
  },
  {
    question: 'What is the first step in expanding (4 + x)¹ᐟ² using the binomial theorem?',
    options: [
      'Factor out 4 to get 2(1 + x/4)¹ᐟ²',
      'Expand directly using n = 1/2',
      'Square both sides',
      'Write it as √4 + √x',
    ],
    answer: 0,
    explanation: 'The general expansion needs the form (1 + something). Factor out 4¹ᐟ² = 2 first, leaving 2(1 + x/4)¹ᐟ².',
    topic: 'The Binomial Expansion (General n)',
  },
  {
    question: 'In the expansion of (1 + x)⁻¹, what is the coefficient of x²?',
    options: ['1', '-1', '2', '-2'],
    answer: 0,
    explanation: 'n(n-1)/2! = (-1)(-2)/2 = 1. The series is 1 - x + x² - x³ + …, so the x² coefficient is +1.',
    topic: 'The Binomial Expansion (General n)',
  },
  {
    question: 'Why does the expansion of (1 + x)ⁿ terminate when n is a positive integer but not otherwise?',
    options: [
      'A factor of (n - r) eventually becomes zero',
      'The terms become too small to matter',
      'The validity condition changes',
      'It does terminate for all n',
    ],
    answer: 0,
    explanation: 'For positive integer n, the numerator n(n-1)(n-2)… eventually contains a zero factor, killing all later terms. For fractional or negative n it never does.',
    topic: 'The Binomial Expansion (General n)',
  },
  {
    question: 'A sector has radius 6 cm and angle 0.5 radians. What is its area?',
    options: ['9 cm²', '18 cm²', '3 cm²', '4.5 cm²'],
    answer: 0,
    explanation: 'A = ½r²θ = ½ × 36 × 0.5 = 9 cm². Forgetting the ½ gives 18.',
    topic: 'Radians',
  },
  {
    question: 'Convert 135° to radians.',
    options: ['3π/4', '4π/3', '3π/2', '2π/3'],
    answer: 0,
    explanation: 'Multiply by π/180: 135 × π/180 = 135π/180 = 3π/4.',
    topic: 'Radians',
  },
  {
    question: 'Using the small angle approximation, cos(0.02) is approximately:',
    options: ['0.9998', '0.02', '1', '0.98'],
    answer: 0,
    explanation: 'cos θ ≈ 1 - θ²/2 = 1 - 0.0002 = 0.9998. Answering 1 uses too crude an approximation for 4 d.p.',
    topic: 'Radians',
  },
  {
    question: 'An arc subtends an angle of 2 radians at the centre of a circle of radius 5 cm. What is the arc length?',
    options: ['10 cm', '5 cm', '20 cm', '2.5 cm'],
    answer: 0,
    explanation: 's = rθ = 5 × 2 = 10 cm. This formula requires θ in radians.',
    topic: 'Radians',
  },
  {
    question: 'Which identity follows from dividing sin²θ + cos²θ = 1 by cos²θ?',
    options: ['1 + tan²θ = sec²θ', '1 + cot²θ = cosec²θ', 'tan²θ = sec²θ', 'sec²θ - cosec²θ = 1'],
    answer: 0,
    explanation: 'Dividing each term by cos²θ gives tan²θ + 1 = sec²θ. Dividing by sin²θ instead gives the cot/cosec version.',
    topic: 'Trigonometric Functions',
  },
  {
    question: 'What is sec θ equal to?',
    options: ['1 / cos θ', '1 / sin θ', 'cos θ / sin θ', 'sin θ / cos θ'],
    answer: 0,
    explanation: 'Use the third-letter rule: se-c pairs with cos. cosec is 1/sin.',
    topic: 'Trigonometric Functions',
  },
  {
    question: 'What is the range of y = arccos x?',
    options: ['0 ≤ y ≤ π', '-π/2 ≤ y ≤ π/2', '-π ≤ y ≤ π', '0 ≤ y ≤ π/2'],
    answer: 0,
    explanation: 'arccos is restricted to 0 to π. The -π/2 to π/2 range belongs to arcsin and arctan.',
    topic: 'Trigonometric Functions',
  },
  {
    question: 'Where does the graph of y = cosec x have vertical asymptotes?',
    options: ['Where sin x = 0', 'Where cos x = 0', 'Where tan x = 0', 'It has none'],
    answer: 0,
    explanation: 'cosec x = 1/sin x, so it is undefined wherever sin x = 0, i.e. at x = 0, π, 2π and so on.',
    topic: 'Trigonometric Functions',
  },
  {
    question: 'Which is a correct form of the double angle formula for cos 2A?',
    options: ['1 - 2sin²A', '2sin A cos A', '1 + 2sin²A', '2cos²A + 1'],
    answer: 0,
    explanation: 'cos 2A = cos²A - sin²A = 2cos²A - 1 = 1 - 2sin²A. The option 2 sinA cosA is sin 2A.',
    topic: 'Trigonometry and Modelling',
  },
  {
    question: 'Express 3 sin x + 4 cos x in the form R sin(x + α). What is R?',
    options: ['5', '7', '25', '√7'],
    answer: 0,
    explanation: 'R = √(a² + b²) = √(9 + 16) = √25 = 5. Adding the coefficients gives 7 - a common error.',
    topic: 'Trigonometry and Modelling',
  },
  {
    question: 'What is the maximum value of 5 sin(x - 30°) + 2?',
    options: ['7', '5', '3', '10'],
    answer: 0,
    explanation: 'sin has a maximum of 1, so the maximum is 5(1) + 2 = 7. The vertical shift must be included.',
    topic: 'Trigonometry and Modelling',
  },
  {
    question: 'What is the correct expansion of sin(A - B)?',
    options: ['sinA cosB - cosA sinB', 'sinA cosB + cosA sinB', 'cosA cosB - sinA sinB', 'sinA sinB - cosA cosB'],
    answer: 0,
    explanation: 'For sine the sign follows the bracket. (The cosine formula is the one where the sign flips.)',
    topic: 'Trigonometry and Modelling',
  },
  {
    question: 'A curve has x = t², y = 2t. What is the Cartesian equation?',
    options: ['x = y²/4', 'y = x²/4', 'x = 2y', 'y = 2√x'],
    answer: 0,
    explanation: 'From y = 2t, t = y/2. Substituting: x = (y/2)² = y²/4.',
    topic: 'Parametric Equations',
  },
  {
    question: 'For a curve given parametrically, dy/dx is found by:',
    options: ['(dy/dt) ÷ (dx/dt)', '(dx/dt) ÷ (dy/dt)', '(dy/dt) × (dx/dt)', 'differentiating y with respect to x directly'],
    answer: 0,
    explanation: 'By the chain rule, dy/dx = dy/dt × dt/dx = (dy/dt) ÷ (dx/dt). Inverting this is the standard error.',
    topic: 'Parametric Equations',
  },
  {
    question: 'For x = 3cos t, y = 3sin t, the Cartesian equation is:',
    options: ['x² + y² = 9', 'x² + y² = 3', 'x² - y² = 9', 'x + y = 3'],
    answer: 0,
    explanation: 'x/3 = cos t and y/3 = sin t. Since sin²t + cos²t = 1, (x/3)² + (y/3)² = 1, so x² + y² = 9.',
    topic: 'Parametric Equations',
  },
  {
    question: 'When finding the area under a parametric curve using ∫ y (dx/dt) dt, what must you remember about the limits?',
    options: [
      'Convert them from x values to t values',
      'Leave them as x values',
      'They are always 0 and 1',
      'Swap them around',
    ],
    answer: 0,
    explanation: 'The variable of integration is t, so the limits must be the t values corresponding to the given x values.',
    topic: 'Parametric Equations',
  },
  {
    question: 'Differentiate y = x sin x.',
    options: ['sin x + x cos x', 'cos x', 'x cos x', 'sin x - x cos x'],
    answer: 0,
    explanation: 'Product rule with u = x, v = sin x: u(dv/dx) + v(du/dx) = x cos x + sin x.',
    topic: 'Differentiation (Year 2)',
  },
  {
    question: 'What is the derivative of ln(3x)?',
    options: ['1/x', '3/x', '1/(3x)', '3 ln x'],
    answer: 0,
    explanation: 'By the chain rule, d/dx ln(3x) = 3/(3x) = 1/x. (Equivalently ln(3x) = ln3 + ln x, and ln3 differentiates to 0.)',
    topic: 'Differentiation (Year 2)',
  },
  {
    question: 'Differentiating y² implicitly with respect to x gives:',
    options: ['2y (dy/dx)', '2y', '2 (dy/dx)', 'y²(dy/dx)'],
    answer: 0,
    explanation: 'The chain rule applies: d/dx(y²) = 2y × dy/dx. Omitting the dy/dx factor is the classic implicit-differentiation error.',
    topic: 'Differentiation (Year 2)',
  },
  {
    question: 'A curve has d²y/dx² > 0 on an interval. On that interval the curve is:',
    options: ['convex', 'concave', 'stationary', 'decreasing'],
    answer: 0,
    explanation: 'A positive second derivative means the gradient is increasing, so the curve is convex (curves upwards).',
    topic: 'Differentiation (Year 2)',
  },
  {
    question: 'The Newton-Raphson method fails when:',
    options: [
      "f'(xₙ) is zero or close to zero",
      'f(xₙ) is negative',
      'the root is irrational',
      'the starting value is too large',
    ],
    answer: 0,
    explanation: 'The formula divides by f′(xₙ). A near-horizontal tangent throws the next approximation far away, or the method breaks down entirely.',
    topic: 'Numerical Methods',
  },
  {
    question: 'The trapezium rule is used with 5 strips. How many ordinates (y values) are needed?',
    options: ['6', '5', '4', '10'],
    answer: 0,
    explanation: 'There is always one more ordinate than strips: n strips need n + 1 ordinates.',
    topic: 'Numerical Methods',
  },
  {
    question: 'f(1) = -2 and f(2) = 3, and f is continuous. What can you conclude?',
    options: [
      'There is at least one root between 1 and 2',
      'There is exactly one root between 1 and 2',
      'There are no roots between 1 and 2',
      'f is increasing on [1, 2]',
    ],
    answer: 0,
    explanation: 'A sign change with continuity guarantees at least one root, but there could be three, five, or any odd number.',
    topic: 'Numerical Methods',
  },
  {
    question: 'For a curve that is convex on the interval, the trapezium rule gives:',
    options: ['an overestimate', 'an underestimate', 'the exact value', 'an unpredictable result'],
    answer: 0,
    explanation: 'On a convex curve each chord lies above the curve, so the trapezia include extra area - an overestimate.',
    topic: 'Numerical Methods',
  },
  {
    question: 'What is ∫ 1/x dx?',
    options: ['ln|x| + c', 'ln x + c', '1/x² + c', 'x⁻² + c'],
    answer: 0,
    explanation: 'The modulus matters: it keeps the result defined for negative x. Dropping it loses a mark.',
    topic: 'Integration (Year 2)',
  },
  {
    question: 'Which method is best for ∫ x eˣ dx?',
    options: ['Integration by parts', 'Substitution u = x²', 'Partial fractions', 'The reverse chain rule'],
    answer: 0,
    explanation: 'A product of two unrelated functions calls for parts, with u = x since it simplifies to 1 when differentiated.',
    topic: 'Integration (Year 2)',
  },
  {
    question: '∫ (2x + 3)/(x² + 3x + 1) dx equals:',
    options: [
      'ln|x² + 3x + 1| + c',
      '(2x + 3)ln|x² + 3x + 1| + c',
      '2ln|x² + 3x + 1| + c',
      '(x² + 3x + 1)² + c',
    ],
    answer: 0,
    explanation: 'The numerator is exactly the derivative of the denominator, so this is the standard ∫f′/f = ln|f| form.',
    topic: 'Integration (Year 2)',
  },
  {
    question: 'To integrate sin²x, you should first:',
    options: [
      'Use cos 2x = 1 - 2sin²x to rewrite it',
      'Use integration by parts',
      'Use the substitution u = sin x',
      'Use partial fractions',
    ],
    answer: 0,
    explanation: 'Rearranging gives sin²x = (1 - cos 2x)/2, which integrates directly. There is no standard integral for sin²x itself.',
    topic: 'Integration (Year 2)',
  },
  {
    question: 'What is the magnitude of the vector 2i - 3j + 6k?',
    options: ['7', '11', '5', '√11'],
    answer: 0,
    explanation: '|v| = √(4 + 9 + 36) = √49 = 7. Adding the components instead gives 5.',
    topic: 'Vectors (3D)',
  },
  {
    question: 'A has position vector a and B has position vector b. The vector AB is:',
    options: ['b - a', 'a - b', 'a + b', '(a + b)/2'],
    answer: 0,
    explanation: 'AB goes from A to B, so it is the endpoint minus the start: b - a. Reversing gives BA.',
    topic: 'Vectors (3D)',
  },
  {
    question: 'Two non-zero vectors are parallel if:',
    options: [
      'one is a scalar multiple of the other',
      'they have the same magnitude',
      'their components sum to zero',
      'they share a common point',
    ],
    answer: 0,
    explanation: 'Parallel means the same or opposite direction, so v = kw for some scalar k. Sharing a point is what upgrades parallel to collinear.',
    topic: 'Vectors (3D)',
  },
  {
    question: 'What is the unit vector in the direction of 3i + 4j?',
    options: ['(3i + 4j)/5', '(3i + 4j)/7', '3i + 4j', '(3i + 4j)/25'],
    answer: 0,
    explanation: 'Divide by the magnitude: |3i + 4j| = √(9 + 16) = 5, so the unit vector is (3i + 4j)/5.',
    topic: 'Vectors (3D)',
  },

  // ------------------------------------------------------- STATISTICS
  {
    question: 'A school has 600 girls and 400 boys. A stratified sample of 50 is taken. How many boys should be sampled?',
    options: ['20', '25', '30', '15'],
    answer: 0,
    explanation: '400/1000 × 50 = 20. Stratified sampling takes from each group in proportion to its size.',
    topic: 'Statistical Sampling',
  },
  {
    question: 'Which sampling method does NOT require a sampling frame?',
    options: ['Quota sampling', 'Simple random sampling', 'Systematic sampling', 'Stratified sampling'],
    answer: 0,
    explanation: 'Quota sampling just fills set numbers per group, so no list of the population is needed - which is its main practical advantage.',
    topic: 'Statistical Sampling',
  },
  {
    question: 'What is the main disadvantage of opportunity sampling?',
    options: [
      'It is unlikely to be representative of the population',
      'It requires a complete sampling frame',
      'It is very expensive',
      'It takes a long time to carry out',
    ],
    answer: 0,
    explanation: 'It samples whoever happens to be available, so it is highly prone to bias - though it is the cheapest and fastest method.',
    topic: 'Statistical Sampling',
  },
  {
    question: 'A census differs from a sample because it:',
    options: [
      'observes every member of the population',
      'is always more convenient',
      'uses random selection',
      'only applies to people',
    ],
    answer: 0,
    explanation: 'A census covers the whole population - completely accurate but expensive, slow, and impossible where testing destroys the item.',
    topic: 'Statistical Sampling',
  },
  {
    question: 'On a histogram, what is plotted on the vertical axis?',
    options: ['Frequency density', 'Frequency', 'Cumulative frequency', 'Class width'],
    answer: 0,
    explanation: 'Frequency density = frequency ÷ class width, so that area (not height) is proportional to frequency across unequal class widths.',
    topic: 'Data Presentation and Interpretation',
  },
  {
    question: 'The data is coded using y = (x - 20)/5. If the mean of y is 4, what is the mean of x?',
    options: ['40', '24', '100', '0.8'],
    answer: 0,
    explanation: 'Reverse the coding: x = 5y + 20 = 5(4) + 20 = 40.',
    topic: 'Data Presentation and Interpretation',
  },
  {
    question: 'Using y = (x - 20)/5, if the standard deviation of y is 3, what is the standard deviation of x?',
    options: ['15', '35', '3', '0.6'],
    answer: 0,
    explanation: 'Only the divisor affects spread: σx = 5 × σy = 15. Adding or subtracting a constant does not change the standard deviation.',
    topic: 'Data Presentation and Interpretation',
  },
  {
    question: 'On a cumulative frequency curve, points are plotted at the:',
    options: ['upper class boundary', 'midpoint of the class', 'lower class boundary', 'class width'],
    answer: 0,
    explanation: 'Cumulative frequency counts everything up to and including that class, so the point belongs at its upper boundary.',
    topic: 'Data Presentation and Interpretation',
  },
  {
    question: 'P(A) = 0.5, P(B) = 0.4 and P(A ∩ B) = 0.2. What is P(A ∪ B)?',
    options: ['0.7', '0.9', '0.5', '1.1'],
    answer: 0,
    explanation: 'P(A ∪ B) = 0.5 + 0.4 - 0.2 = 0.7. Forgetting to subtract the intersection double-counts the overlap.',
    topic: 'Probability',
  },
  {
    question: 'Two events A and B are mutually exclusive. What is P(A ∩ B)?',
    options: ['0', 'P(A) × P(B)', 'P(A) + P(B)', '1'],
    answer: 0,
    explanation: 'Mutually exclusive means they cannot both occur, so the intersection is empty and its probability is zero.',
    topic: 'Probability',
  },
  {
    question: 'Two counters are drawn without replacement from a bag of 5 red and 3 blue. On a tree diagram, the second set of branches:',
    options: [
      'has different probabilities from the first',
      'has the same probabilities as the first',
      'always sums to more than 1',
      'is not needed',
    ],
    answer: 0,
    explanation: 'Without replacement the bag has changed, so the second-layer probabilities have denominator 7, not 8.',
    topic: 'Probability',
  },
  {
    question: 'If A and B are independent, which statement is true?',
    options: ['P(A ∩ B) = P(A) × P(B)', 'P(A ∩ B) = 0', 'P(A ∪ B) = P(A) + P(B)', 'P(A) = P(B)'],
    answer: 0,
    explanation: 'Independence means one event does not affect the other, so their joint probability is the product. Zero intersection is mutual exclusivity, a different idea.',
    topic: 'Probability',
  },
  {
    question: 'X ~ B(20, 0.3). Which condition is NOT required for a binomial model?',
    options: [
      'The probability of success varies between trials',
      'There is a fixed number of trials',
      'Each trial has two outcomes',
      'The trials are independent',
    ],
    answer: 0,
    explanation: 'The binomial requires p to be constant. A varying probability breaks the model.',
    topic: 'Statistical Distributions (Binomial)',
  },
  {
    question: 'For X ~ B(n, p), how do you write P(X ≥ 4) using cumulative probabilities?',
    options: ['1 - P(X ≤ 3)', '1 - P(X ≤ 4)', 'P(X ≤ 4)', 'P(X ≤ 3)'],
    answer: 0,
    explanation: 'X ≥ 4 is the complement of X ≤ 3. Using P(X ≤ 4) is the classic off-by-one error.',
    topic: 'Statistical Distributions (Binomial)',
  },
  {
    question: 'X ~ B(10, 0.5). What is P(X = 10)?',
    options: ['0.5¹⁰', '10 × 0.5', '0.5', '1'],
    answer: 0,
    explanation: 'P(X = 10) = ¹⁰C₁₀ × 0.5¹⁰ × 0.5⁰ = 1 × 0.5¹⁰ ≈ 0.000977.',
    topic: 'Statistical Distributions (Binomial)',
  },
  {
    question: 'In the binomial formula, what does ⁿCᵣ represent?',
    options: [
      'The number of ways r successes can occur in n trials',
      'The probability of r successes',
      'The mean number of successes',
      'The number of failures',
    ],
    answer: 0,
    explanation: 'It counts the arrangements of r successes among n trials - the combinatorial part of the formula.',
    topic: 'Statistical Distributions (Binomial)',
  },
  {
    question: 'A test is carried out at the 5% significance level with H₁: p ≠ 0.4. What probability is used in each tail?',
    options: ['2.5%', '5%', '10%', '1%'],
    answer: 0,
    explanation: 'A two-tailed test splits the significance level between the tails, so 2.5% each.',
    topic: 'Statistical Hypothesis Testing',
  },
  {
    question: 'Which is a correctly stated null hypothesis?',
    options: ['H₀: p = 0.25', 'H₀: p > 0.25', 'H₀: p ≠ 0.25', 'H₀: x̄ = 0.25'],
    answer: 0,
    explanation: 'H₀ always states equality, and must be in terms of the population parameter p, not a sample statistic.',
    topic: 'Statistical Hypothesis Testing',
  },
  {
    question: 'The actual significance level of a binomial test is:',
    options: [
      'the true probability of the critical region',
      'always exactly 5%',
      'the p-value of the observed result',
      'the probability of H₀ being true',
    ],
    answer: 0,
    explanation: 'Because the binomial is discrete you cannot usually hit the nominal level exactly, so the actual level is the real probability of the region used.',
    topic: 'Statistical Hypothesis Testing',
  },
  {
    question: 'A test gives a p-value of 0.08 at the 5% significance level. The correct conclusion is:',
    options: [
      'Insufficient evidence to reject H₀',
      'H₀ is true',
      'Reject H₀',
      'H₁ is true',
    ],
    answer: 0,
    explanation: '0.08 > 0.05, so H₀ is not rejected. Never say H₀ "is true" - failing to reject is not proof.',
    topic: 'Statistical Hypothesis Testing',
  },
  {
    question: 'The regression line of y on x should be used to:',
    options: ['predict y from x', 'predict x from y', 'predict either way', 'measure correlation strength'],
    answer: 0,
    explanation: 'It minimises vertical distances, so it is only valid for predicting the dependent variable y from x.',
    topic: 'Regression, Correlation and Hypothesis Testing',
  },
  {
    question: 'Predicting a value outside the range of the collected data is called:',
    options: ['extrapolation', 'interpolation', 'regression', 'correlation'],
    answer: 0,
    explanation: 'Extrapolation is unreliable because there is no evidence the relationship continues beyond the observed range.',
    topic: 'Regression, Correlation and Hypothesis Testing',
  },
  {
    question: 'In a hypothesis test for correlation, the hypotheses are stated in terms of:',
    options: ['ρ, the population correlation coefficient', 'r, the sample correlation coefficient', 'the gradient of the regression line', 'the sample mean'],
    answer: 0,
    explanation: 'Hypotheses are always about the population parameter ρ; r is the sample statistic used to test it.',
    topic: 'Regression, Correlation and Hypothesis Testing',
  },
  {
    question: 'To linearise the model y = axⁿ, you would plot:',
    options: ['log y against log x', 'y against log x', 'log y against x', 'y against x²'],
    answer: 0,
    explanation: 'Taking logs gives log y = log a + n log x, a straight line of log y against log x with gradient n.',
    topic: 'Regression, Correlation and Hypothesis Testing',
  },
  {
    question: 'P(A ∩ B) = 0.12 and P(B) = 0.4. What is P(A | B)?',
    options: ['0.3', '0.048', '0.52', '3.33'],
    answer: 0,
    explanation: 'P(A | B) = P(A ∩ B)/P(B) = 0.12/0.4 = 0.3.',
    topic: 'Conditional Probability',
  },
  {
    question: 'Which is equivalent to (A ∪ B)′?',
    options: ["A′ ∩ B′", "A′ ∪ B′", "A ∩ B", "A′ ∩ B"],
    answer: 0,
    explanation: 'By De Morgan’s law, the complement of a union is the intersection of the complements.',
    topic: 'Conditional Probability',
  },
  {
    question: 'If P(A | B) = P(A), then A and B are:',
    options: ['independent', 'mutually exclusive', 'complementary', 'equally likely'],
    answer: 0,
    explanation: 'If knowing B occurred does not change the probability of A, the events are independent.',
    topic: 'Conditional Probability',
  },
  {
    question: 'On a Venn diagram, which region represents P(A | B)?',
    options: [
      'The overlap, divided by the whole of B',
      'The overlap, divided by the whole rectangle',
      'The whole of A, divided by the whole of B',
      'The part of A outside B',
    ],
    answer: 0,
    explanation: 'Conditioning on B restricts the sample space to B, so you divide the intersection by all of B - not by the grand total.',
    topic: 'Conditional Probability',
  },
  {
    question: 'X ~ N(50, 16). What is the standard deviation?',
    options: ['4', '16', '50', '8'],
    answer: 0,
    explanation: 'The second parameter is the variance σ², so σ = √16 = 4. Entering 16 as the standard deviation is the most common calculator error.',
    topic: 'The Normal Distribution',
  },
  {
    question: 'For a normal distribution, P(X = 5) equals:',
    options: ['0', '0.5', 'depends on σ', '1'],
    answer: 0,
    explanation: 'The normal is continuous, so the probability of any single exact value is zero - which is why P(X < a) = P(X ≤ a).',
    topic: 'The Normal Distribution',
  },
  {
    question: 'X ~ B(100, 0.5) is approximated by a normal distribution. To find P(X ≤ 40) you calculate:',
    options: ['P(Y < 40.5)', 'P(Y < 40)', 'P(Y < 39.5)', 'P(Y ≤ 41)'],
    answer: 0,
    explanation: 'The continuity correction extends the boundary by 0.5 outwards for ≤, giving 40.5.',
    topic: 'The Normal Distribution',
  },
  {
    question: 'For a sample of size n from N(μ, σ²), the distribution of the sample mean is:',
    options: ['N(μ, σ²/n)', 'N(μ, σ²)', 'N(μ/n, σ²)', 'N(nμ, nσ²)'],
    answer: 0,
    explanation: 'The sample mean has the same mean but variance divided by n, so its standard deviation is σ/√n.',
    topic: 'The Normal Distribution',
  },

  // -------------------------------------------------- MECHANICS · YEAR 2
  {
    question: 'A force of 10 N acts at the end of a 3 m rod, at 30° to the rod. What is its moment about the other end?',
    options: ['15 Nm', '30 Nm', '26 Nm', '5 Nm'],
    answer: 0,
    explanation: 'Use the perpendicular component: 10 sin30° × 3 = 5 × 3 = 15 Nm. Using the full 10 N gives 30 - the standard error.',
    topic: 'Moments',
  },
  {
    question: 'For a rigid body in equilibrium, which pair of conditions must hold?',
    options: [
      'Resultant force zero and resultant moment zero',
      'Resultant force zero only',
      'Resultant moment zero only',
      'All forces equal in magnitude',
    ],
    answer: 0,
    explanation: 'Both are needed. Zero resultant force alone still permits rotation about a point.',
    topic: 'Moments',
  },
  {
    question: 'A non-uniform rod is in equilibrium on two supports. Its weight acts:',
    options: [
      'at its centre of mass, which is not the midpoint',
      'at its midpoint',
      'at whichever support is nearer',
      'at the end of the rod',
    ],
    answer: 0,
    explanation: 'Only a uniform rod has its centre of mass at the midpoint; for a non-uniform rod its position is usually the unknown to find.',
    topic: 'Moments',
  },
  {
    question: 'A rod rests on two supports and is about to tilt about support B. What is true at that instant?',
    options: [
      'The reaction at the other support is zero',
      'The reaction at B is zero',
      'Both reactions are equal',
      'The weight acts at B',
    ],
    answer: 0,
    explanation: 'On the point of tilting about B the rod is losing contact elsewhere, so the other reaction is zero - this is the extra equation you need.',
    topic: 'Moments',
  },
  {
    question: 'A block of mass m rests on a slope inclined at α. What is the normal reaction?',
    options: ['mg cos α', 'mg', 'mg sin α', 'mg tan α'],
    answer: 0,
    explanation: 'Resolving perpendicular to the slope gives R = mg cos α. Using R = mg on a slope is the most common mechanics error.',
    topic: 'Forces and Friction',
  },
  {
    question: 'A body is in equilibrium on a rough surface but not on the point of moving. The friction force is:',
    options: ['less than μR', 'exactly μR', 'greater than μR', 'zero'],
    answer: 0,
    explanation: 'Friction satisfies F ≤ μR. It only equals μR at the point of slipping (limiting equilibrium); otherwise find it from the equilibrium equation.',
    topic: 'Forces and Friction',
  },
  {
    question: 'The phrase "in limiting equilibrium" tells you that:',
    options: ['F = μR exactly', 'F = 0', 'R = mg', 'the body is accelerating'],
    answer: 0,
    explanation: 'Limiting equilibrium means friction has reached its maximum, so F = μR - the extra equation the question is handing you.',
    topic: 'Forces and Friction',
  },
  {
    question: 'The component of weight acting down a slope inclined at α is:',
    options: ['mg sin α', 'mg cos α', 'mg tan α', 'mg'],
    answer: 0,
    explanation: 'Resolving parallel to the slope gives mg sin α. Check with α = 0: on flat ground the component down the slope is zero, and sin 0 = 0.',
    topic: 'Forces and Friction',
  },
  {
    question: 'A projectile is launched at 20 m/s at 30° to the horizontal. What is the initial vertical component of velocity?',
    options: ['10 m/s', '17.3 m/s', '20 m/s', '5 m/s'],
    answer: 0,
    explanation: 'Vertical component = u sin θ = 20 sin30° = 20 × 0.5 = 10 m/s. Using cos gives the horizontal component, 17.3.',
    topic: 'Projectiles',
  },
  {
    question: 'At the highest point of a projectile’s flight:',
    options: [
      'the vertical velocity is zero but the horizontal is not',
      'the velocity is zero',
      'the acceleration is zero',
      'the horizontal velocity is zero',
    ],
    answer: 0,
    explanation: 'Only the vertical component vanishes. The horizontal velocity is unchanged throughout, and acceleration stays at g downwards.',
    topic: 'Projectiles',
  },
  {
    question: 'Which launch angle gives maximum range on level ground (ignoring air resistance)?',
    options: ['45°', '30°', '60°', '90°'],
    answer: 0,
    explanation: 'Range = u² sin2θ / g, maximised when sin 2θ = 1, i.e. 2θ = 90°, so θ = 45°.',
    topic: 'Projectiles',
  },
  {
    question: 'What is the horizontal acceleration of a projectile (ignoring air resistance)?',
    options: ['0', 'g', '-g', 'u cos θ'],
    answer: 0,
    explanation: 'Gravity acts only vertically, so horizontal velocity is constant and horizontal acceleration is zero.',
    topic: 'Projectiles',
  },
  {
    question: 'Two particles are connected by an inextensible string over a smooth pulley. Which is true?',
    options: [
      'The tension is the same on both sides',
      'The tension is greater on the heavier side',
      'The accelerations have different magnitudes',
      'The tension equals the weight of the heavier particle',
    ],
    answer: 0,
    explanation: 'A smooth pulley and inextensible string give equal tension throughout and equal acceleration magnitudes.',
    topic: 'Application of Forces',
  },
  {
    question: 'When writing F = ma for two connected particles, you should take the positive direction as:',
    options: [
      "each particle's own direction of motion",
      'upwards for both',
      'downwards for both',
      'to the right for both',
    ],
    answer: 0,
    explanation: 'Taking each particle’s direction of travel as positive keeps both accelerations positive and avoids sign errors.',
    topic: 'Application of Forces',
  },
  {
    question: 'A ladder rests against a smooth wall on rough ground. At the wall there is:',
    options: [
      'a normal reaction only',
      'a normal reaction and friction',
      'friction only',
      'no force at all',
    ],
    answer: 0,
    explanation: '"Smooth" means frictionless, so the wall exerts only a normal reaction perpendicular to it.',
    topic: 'Application of Forces',
  },
  {
    question: 'When a string connecting two particles breaks, the particle that was moving upward:',
    options: [
      'decelerates under gravity alone as a projectile',
      'stops immediately',
      'continues at constant velocity',
      'accelerates upwards',
    ],
    answer: 0,
    explanation: 'With the tension gone the only force is weight, so it decelerates at g, stops momentarily, then falls.',
    topic: 'Application of Forces',
  },
  {
    question: 'Which suvat equation has NO valid vector form?',
    options: ['v² = u² + 2as', 'v = u + at', 's = ut + ½at²', 's = ½(u + v)t'],
    answer: 0,
    explanation: 'It relies on squaring, which is not defined for vectors at this level - the other three work component by component.',
    topic: 'Further Kinematics',
  },
  {
    question: 'A particle has velocity v = (3t)i + (t² - 4)j. What is its acceleration?',
    options: ['3i + 2tj', '3i + (t³/3)j', '(3t)i + (2t)j', '3i - 4j'],
    answer: 0,
    explanation: 'Differentiate each component with respect to t: d/dt(3t) = 3 and d/dt(t² - 4) = 2t.',
    topic: 'Further Kinematics',
  },
  {
    question: 'A particle is instantaneously at rest when:',
    options: [
      'both components of velocity are zero',
      'one component of velocity is zero',
      'the acceleration is zero',
      'the displacement is zero',
    ],
    answer: 0,
    explanation: 'At rest means the whole velocity vector is zero, so both components must vanish at the same value of t.',
    topic: 'Further Kinematics',
  },
  {
    question: 'Integrating an acceleration vector to find velocity introduces:',
    options: [
      'a constant vector, found from the initial conditions',
      'a scalar constant',
      'no constant',
      'two constants',
    ],
    answer: 0,
    explanation: 'Each integration adds a constant of integration, which here is a vector - fixed by the initial velocity given in the question.',
    topic: 'Further Kinematics',
  },
]
