/*
  Edexcel A-level Maths multiple-choice questions, topic-tagged to match the
  `topic` strings used by the Maths pack's chapter picker.

  The Maths pack shipped with an empty `mcq: []`, so choosing the MCQ
  technique on Maths hit a dead-end empty state for every one of its 43
  topics. These fill that gap.

  Each option set is written so the distractors are the mistakes students
  actually make (sign slips, off-by-one, confusing d/dx with ∫), not obvious
  throwaways - a wrong pick should be diagnostic.
*/
export const MATHS_MCQ = [
  // ---------------------------------------------------- PURE · YEAR 1 (AS)
  {
    question: 'Simplify (x⁵)³ ÷ x⁹',
    options: ['x⁶', 'x⁵', 'x²⁷', 'x⁻¹'],
    answer: 0,
    explanation: '(x⁵)³ = x¹⁵ (multiply the powers), then x¹⁵ ÷ x⁹ = x⁶ (subtract the powers).',
    topic: 'Algebraic Expressions',
  },
  {
    question: 'Rationalise the denominator of 6 / √3',
    options: ['2√3', '6√3', '√3 / 2', '3√2'],
    answer: 0,
    explanation: 'Multiply top and bottom by √3: 6√3 / 3 = 2√3.',
    topic: 'Algebraic Expressions',
  },
  {
    question: 'What is the discriminant of 2x² − 4x + 5?',
    options: ['−24', '16', '56', '−16'],
    answer: 0,
    explanation: 'b² − 4ac = (−4)² − 4(2)(5) = 16 − 40 = −24, so there are no real roots.',
    topic: 'Quadratics',
  },
  {
    question: 'Written in completed-square form, x² − 6x + 11 is',
    options: ['(x − 3)² + 2', '(x − 3)² − 2', '(x + 3)² + 2', '(x − 6)² + 11'],
    answer: 0,
    explanation: 'Half of −6 is −3, and (x − 3)² = x² − 6x + 9, so we need +2 to reach 11.',
    topic: 'Quadratics',
  },
  {
    question: 'Solve the inequality x² − 5x + 6 < 0',
    options: ['2 < x < 3', 'x < 2 or x > 3', 'x < 3', '−3 < x < −2'],
    answer: 0,
    explanation: 'Roots are 2 and 3. The parabola opens upward, so it is below zero strictly between the roots.',
    topic: 'Equations and Inequalities',
  },
  {
    question: 'The graph of y = f(x) is transformed to y = f(x + 2). The curve moves',
    options: ['2 left', '2 right', '2 up', '2 down'],
    answer: 0,
    explanation: 'A change inside the bracket shifts horizontally and in the opposite direction to the sign: +2 moves left.',
    topic: 'Graphs and Transformations',
  },
  {
    question: 'A line has gradient 3 and passes through (2, 1). Its equation is',
    options: ['y = 3x − 5', 'y = 3x + 5', 'y = 3x − 1', 'y = 2x + 1'],
    answer: 0,
    explanation: 'y − 1 = 3(x − 2) gives y = 3x − 6 + 1 = 3x − 5.',
    topic: 'Straight Line Graphs',
  },
  {
    question: 'A line perpendicular to y = 2x + 7 has gradient',
    options: ['−1/2', '2', '1/2', '−2'],
    answer: 0,
    explanation: 'Perpendicular gradients multiply to −1, so m = −1/2.',
    topic: 'Straight Line Graphs',
  },
  {
    question: 'The circle (x − 3)² + (y + 1)² = 25 has centre and radius',
    options: ['(3, −1), r = 5', '(−3, 1), r = 5', '(3, −1), r = 25', '(3, 1), r = 5'],
    answer: 0,
    explanation: 'For (x − a)² + (y − b)² = r², the centre is (a, b) and the radius is √25 = 5.',
    topic: 'Circles',
  },
  {
    question: 'To prove a statement false, it is enough to',
    options: [
      'give one counter-example',
      'check several cases that work',
      'rearrange the statement',
      'show it works for n = 1',
    ],
    answer: 0,
    explanation: 'A single counter-example disproves a universal statement; confirming cases never proves one.',
    topic: 'Algebraic Methods (Proof & Division)',
  },
  {
    question: 'In the expansion of (1 + x)⁵, the coefficient of x² is',
    options: ['10', '5', '20', '15'],
    answer: 0,
    explanation: 'The coefficient is ⁵C₂ = 10.',
    topic: 'The Binomial Expansion',
  },
  {
    question: 'What is the exact value of sin 30°?',
    options: ['1/2', '√3/2', '√2/2', '1'],
    answer: 0,
    explanation: 'From the 30-60-90 triangle, sin 30° = 1/2.',
    topic: 'Trigonometric Ratios',
  },
  {
    question: 'Which identity is correct?',
    options: [
      'sin²θ + cos²θ = 1',
      'sin²θ − cos²θ = 1',
      'tan²θ + 1 = sin²θ',
      'sin²θ + cos²θ = 2',
    ],
    answer: 0,
    explanation: 'The Pythagorean identity: sin²θ + cos²θ = 1.',
    topic: 'Trigonometric Identities and Equations',
  },
  {
    question: 'If a = 3i + 4j, what is |a|?',
    options: ['5', '7', '25', '√7'],
    answer: 0,
    explanation: '|a| = √(3² + 4²) = √25 = 5.',
    topic: 'Vectors (2D)',
  },
  {
    question: 'Differentiate y = 4x³ with respect to x',
    options: ['12x²', '4x²', '12x³', 'x⁴'],
    answer: 0,
    explanation: 'Multiply by the power and reduce it by one: 4 × 3 x² = 12x².',
    topic: 'Differentiation',
  },
  {
    question: 'Find ∫ 6x² dx',
    options: ['2x³ + c', '12x + c', '6x³ + c', '3x³ + c'],
    answer: 0,
    explanation: 'Raise the power and divide by the new power: 6x³/3 = 2x³, plus the constant.',
    topic: 'Integration',
  },
  {
    question: 'Solve 2ˣ = 8',
    options: ['x = 3', 'x = 4', 'x = 2', 'x = 16'],
    answer: 0,
    explanation: '8 = 2³, so x = 3.',
    topic: 'Exponentials and Logarithms',
  },
  {
    question: 'log₁₀ a + log₁₀ b is equal to',
    options: ['log₁₀(ab)', 'log₁₀(a + b)', 'log₁₀(a/b)', '(log₁₀ a)(log₁₀ b)'],
    answer: 0,
    explanation: 'The addition law of logarithms: log a + log b = log(ab).',
    topic: 'Exponentials and Logarithms',
  },

  // ---------------------------------------------------- PURE · YEAR 2 (A2)
  {
    question: 'Partial fractions are used to',
    options: [
      'split one algebraic fraction into simpler ones',
      'combine fractions into a single fraction',
      'differentiate a quotient',
      'factorise a quadratic',
    ],
    answer: 0,
    explanation: 'They decompose a fraction into simpler terms, which makes integration far easier.',
    topic: 'Algebraic Methods (Partial Fractions)',
  },
  {
    question: 'For f(x) = x², the inverse f⁻¹ exists only if the domain is restricted because f is',
    options: ['many-to-one', 'one-to-one', 'undefined at 0', 'discontinuous'],
    answer: 0,
    explanation: 'x² is many-to-one (2 and −2 both map to 4), so the domain must be restricted for an inverse to exist.',
    topic: 'Functions and Graphs',
  },
  {
    question: 'The sum of the first n terms of an arithmetic series is',
    options: ['n/2 [2a + (n − 1)d]', 'a(1 − rⁿ)/(1 − r)', 'a + (n − 1)d', 'n(a + d)'],
    answer: 0,
    explanation: 'That is the standard arithmetic sum; the second option is the geometric sum.',
    topic: 'Sequences and Series',
  },
  {
    question: 'The expansion of (1 + x)ⁿ for non-integer n is valid only when',
    options: ['|x| < 1', 'x > 1', 'x is an integer', 'always'],
    answer: 0,
    explanation: 'The infinite binomial series converges only for |x| < 1.',
    topic: 'The Binomial Expansion (General n)',
  },
  {
    question: '180° expressed in radians is',
    options: ['π', '2π', 'π/2', 'π/180'],
    answer: 0,
    explanation: 'A half turn is π radians.',
    topic: 'Radians',
  },
  {
    question: 'sec θ is defined as',
    options: ['1 / cos θ', '1 / sin θ', 'cos θ / sin θ', '1 / tan θ'],
    answer: 0,
    explanation: 'sec is the reciprocal of cosine; 1/sin is cosec and 1/tan is cot.',
    topic: 'Trigonometric Functions',
  },
  {
    question: 'a sin θ + b cos θ can always be written in the form',
    options: ['R sin(θ + α)', 'R sin θ cos θ', 'R tan(θ + α)', 'R + sin θ'],
    answer: 0,
    explanation: 'The harmonic form R sin(θ + α), with R = √(a² + b²), is what makes max/min values easy to read off.',
    topic: 'Trigonometry and Modelling',
  },
  {
    question: 'For parametric equations x = f(t), y = g(t), dy/dx equals',
    options: ['(dy/dt) ÷ (dx/dt)', '(dy/dt) × (dx/dt)', 'dy/dt', 'dx/dt ÷ dy/dt'],
    answer: 0,
    explanation: 'By the chain rule, dy/dx = (dy/dt)/(dx/dt).',
    topic: 'Parametric Equations',
  },
  {
    question: 'Differentiate y = sin x',
    options: ['cos x', '−cos x', '−sin x', 'sec² x'],
    answer: 0,
    explanation: 'd/dx (sin x) = cos x. (It is −sin x that differentiates to −cos x.)',
    topic: 'Differentiation (Year 2)',
  },
  {
    question: 'The Newton-Raphson iteration formula is',
    options: [
      'xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ)',
      'xₙ₊₁ = xₙ + f(xₙ)/f′(xₙ)',
      'xₙ₊₁ = f(xₙ)/f′(xₙ)',
      'xₙ₊₁ = xₙ − f′(xₙ)/f(xₙ)',
    ],
    answer: 0,
    explanation: 'Subtract f(x)/f′(x); flipping the fraction or the sign is the usual slip.',
    topic: 'Numerical Methods',
  },
  {
    question: 'Integration by parts uses the formula',
    options: [
      '∫u dv/dx dx = uv − ∫v du/dx dx',
      '∫u dv = uv + ∫v du',
      '∫uv dx = ∫u dx ∫v dx',
      '∫u/v dx = ∫u dx / ∫v dx',
    ],
    answer: 0,
    explanation: 'The minus sign in front of the second integral is essential.',
    topic: 'Integration (Year 2)',
  },
  {
    question: 'The magnitude of the 3D vector 2i + 3j + 6k is',
    options: ['7', '11', '√11', '36'],
    answer: 0,
    explanation: '√(4 + 9 + 36) = √49 = 7.',
    topic: 'Vectors (3D)',
  },

  // -------------------------------------------------------- STATISTICS
  {
    question: 'In a simple random sample, every member of the population has',
    options: [
      'an equal chance of being selected',
      'been ranked by size first',
      'been chosen by the researcher',
      'volunteered to take part',
    ],
    answer: 0,
    explanation: 'Equal probability of selection is exactly what makes a sample simple random.',
    topic: 'Statistical Sampling',
  },
  {
    question: 'Which measure of spread is least affected by an outlier?',
    options: ['Interquartile range', 'Range', 'Standard deviation', 'Mean'],
    answer: 0,
    explanation: 'The IQR uses only the middle 50%, so extreme values do not move it.',
    topic: 'Data Presentation and Interpretation',
  },
  {
    question: 'For mutually exclusive events A and B, P(A ∪ B) equals',
    options: ['P(A) + P(B)', 'P(A) × P(B)', 'P(A) + P(B) − P(A ∩ B)', 'P(A) − P(B)'],
    answer: 0,
    explanation: 'Mutually exclusive means P(A ∩ B) = 0, so the general addition rule reduces to P(A) + P(B).',
    topic: 'Probability',
  },
  {
    question: 'For X ~ B(n, p), the mean of X is',
    options: ['np', 'np(1 − p)', 'p/n', 'n + p'],
    answer: 0,
    explanation: 'The binomial mean is np; np(1 − p) is the variance.',
    topic: 'Statistical Distributions (Binomial)',
  },
  {
    question: 'In hypothesis testing, you reject H₀ when',
    options: [
      'the p-value is less than the significance level',
      'the p-value is greater than the significance level',
      'the sample is small',
      'H₁ is one-tailed',
    ],
    answer: 0,
    explanation: 'A p-value below the significance level means the result is unlikely enough under H₀ to reject it.',
    topic: 'Statistical Hypothesis Testing',
  },
  {
    question: 'A product moment correlation coefficient of −0.9 indicates',
    options: [
      'strong negative linear correlation',
      'weak negative correlation',
      'strong positive correlation',
      'no correlation',
    ],
    answer: 0,
    explanation: 'Values near −1 mean strong negative linear correlation.',
    topic: 'Regression, Correlation and Hypothesis Testing',
  },
  {
    question: 'P(A | B) is defined as',
    options: ['P(A ∩ B) / P(B)', 'P(A ∩ B) / P(A)', 'P(A) × P(B)', 'P(A ∪ B) / P(B)'],
    answer: 0,
    explanation: 'Conditional probability divides by the probability of the event being conditioned on.',
    topic: 'Conditional Probability',
  },
  {
    question: 'Approximately what percentage of normally distributed data lies within one standard deviation of the mean?',
    options: ['68%', '95%', '99.7%', '50%'],
    answer: 0,
    explanation: 'The empirical rule: about 68% within 1σ, 95% within 2σ, 99.7% within 3σ.',
    topic: 'The Normal Distribution',
  },

  // --------------------------------------------------------- MECHANICS
  {
    question: 'Modelling an object as a particle means assuming',
    options: [
      'its size can be ignored',
      'it has no mass',
      'it cannot move',
      'there is no gravity',
    ],
    answer: 0,
    explanation: 'A particle keeps its mass but has negligible dimensions, so rotation is ignored.',
    topic: 'Modelling in Mechanics',
  },
  {
    question: 'Which SUVAT equation does not involve time?',
    options: ['v² = u² + 2as', 'v = u + at', 's = ut + ½at²', 's = ½(u + v)t'],
    answer: 0,
    explanation: 'v² = u² + 2as links velocity, acceleration and displacement with no t.',
    topic: 'Constant Acceleration (SUVAT)',
  },
  {
    question: "Newton's Second Law states that",
    options: ['F = ma', 'F = mv', 'F = m/a', 'F = ma²'],
    answer: 0,
    explanation: 'Resultant force equals mass times acceleration.',
    topic: "Forces and Newton's Laws",
  },
  {
    question: 'If displacement is given by s(t), the acceleration is',
    options: [
      'the second derivative of s',
      'the integral of s',
      'the first derivative of s',
      's divided by t²',
    ],
    answer: 0,
    explanation: 'Differentiate once for velocity and twice for acceleration.',
    topic: 'Variable Acceleration',
  },
  {
    question: 'The moment of a force about a point is',
    options: [
      'force × perpendicular distance from the point',
      'force × mass',
      'force ÷ distance',
      'force × time',
    ],
    answer: 0,
    explanation: 'The distance must be perpendicular to the line of action of the force.',
    topic: 'Moments',
  },
  {
    question: 'The maximum friction force before sliding begins is',
    options: ['μR', 'μ/R', 'R/μ', 'μmg sin θ'],
    answer: 0,
    explanation: 'Limiting friction is μR, where R is the normal reaction.',
    topic: 'Forces and Friction',
  },
  {
    question: 'For a projectile (ignoring air resistance), the horizontal acceleration is',
    options: ['zero', '9.8 m s⁻²', 'equal to the vertical acceleration', 'constant but negative'],
    answer: 0,
    explanation: 'With no air resistance there is no horizontal force, so horizontal velocity stays constant.',
    topic: 'Projectiles',
  },
  {
    question: 'A body in equilibrium has',
    options: [
      'zero resultant force',
      'zero mass',
      'constant acceleration',
      'no forces acting on it at all',
    ],
    answer: 0,
    explanation: 'Forces may act, but they must cancel so the resultant is zero.',
    topic: 'Application of Forces',
  },
  {
    question: 'Integrating an acceleration vector with respect to time gives',
    options: ['velocity', 'displacement', 'force', 'momentum'],
    answer: 0,
    explanation: 'Integrate acceleration once for velocity, twice for displacement.',
    topic: 'Further Kinematics',
  },
]
